// Code generated by ent, DO NOT EDIT.

package tribute

import (
	"backend/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldLTE(FieldID, id))
}

// MemorialID applies equality check predicate on the "memorial_id" field. It's identical to MemorialIDEQ.
func MemorialID(v uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldMemorialID, v))
}

// AuthorName applies equality check predicate on the "author_name" field. It's identical to AuthorNameEQ.
func AuthorName(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldAuthorName, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldMessage, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldCreatedAt, v))
}

// MemorialIDEQ applies the EQ predicate on the "memorial_id" field.
func MemorialIDEQ(v uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldMemorialID, v))
}

// MemorialIDNEQ applies the NEQ predicate on the "memorial_id" field.
func MemorialIDNEQ(v uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldNEQ(FieldMemorialID, v))
}

// MemorialIDIn applies the In predicate on the "memorial_id" field.
func MemorialIDIn(vs ...uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldIn(FieldMemorialID, vs...))
}

// MemorialIDNotIn applies the NotIn predicate on the "memorial_id" field.
func MemorialIDNotIn(vs ...uuid.UUID) predicate.Tribute {
	return predicate.Tribute(sql.FieldNotIn(FieldMemorialID, vs...))
}

// AuthorNameEQ applies the EQ predicate on the "author_name" field.
func AuthorNameEQ(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldAuthorName, v))
}

// AuthorNameNEQ applies the NEQ predicate on the "author_name" field.
func AuthorNameNEQ(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldNEQ(FieldAuthorName, v))
}

// AuthorNameIn applies the In predicate on the "author_name" field.
func AuthorNameIn(vs ...string) predicate.Tribute {
	return predicate.Tribute(sql.FieldIn(FieldAuthorName, vs...))
}

// AuthorNameNotIn applies the NotIn predicate on the "author_name" field.
func AuthorNameNotIn(vs ...string) predicate.Tribute {
	return predicate.Tribute(sql.FieldNotIn(FieldAuthorName, vs...))
}

// AuthorNameGT applies the GT predicate on the "author_name" field.
func AuthorNameGT(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldGT(FieldAuthorName, v))
}

// AuthorNameGTE applies the GTE predicate on the "author_name" field.
func AuthorNameGTE(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldGTE(FieldAuthorName, v))
}

// AuthorNameLT applies the LT predicate on the "author_name" field.
func AuthorNameLT(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldLT(FieldAuthorName, v))
}

// AuthorNameLTE applies the LTE predicate on the "author_name" field.
func AuthorNameLTE(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldLTE(FieldAuthorName, v))
}

// AuthorNameContains applies the Contains predicate on the "author_name" field.
func AuthorNameContains(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldContains(FieldAuthorName, v))
}

// AuthorNameHasPrefix applies the HasPrefix predicate on the "author_name" field.
func AuthorNameHasPrefix(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldHasPrefix(FieldAuthorName, v))
}

// AuthorNameHasSuffix applies the HasSuffix predicate on the "author_name" field.
func AuthorNameHasSuffix(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldHasSuffix(FieldAuthorName, v))
}

// AuthorNameEqualFold applies the EqualFold predicate on the "author_name" field.
func AuthorNameEqualFold(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldEqualFold(FieldAuthorName, v))
}

// AuthorNameContainsFold applies the ContainsFold predicate on the "author_name" field.
func AuthorNameContainsFold(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldContainsFold(FieldAuthorName, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.Tribute {
	return predicate.Tribute(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.Tribute {
	return predicate.Tribute(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.Tribute {
	return predicate.Tribute(sql.FieldContainsFold(FieldMessage, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Tribute {
	return predicate.Tribute(sql.FieldLTE(FieldCreatedAt, v))
}

// HasMemorial applies the HasEdge predicate on the "memorial" edge.
func HasMemorial() predicate.Tribute {
	return predicate.Tribute(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, MemorialTable, MemorialColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMemorialWith applies the HasEdge predicate on the "memorial" edge with a given conditions (other predicates).
func HasMemorialWith(preds ...predicate.Memorial) predicate.Tribute {
	return predicate.Tribute(func(s *sql.Selector) {
		step := newMemorialStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Tribute) predicate.Tribute {
	return predicate.Tribute(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Tribute) predicate.Tribute {
	return predicate.Tribute(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Tribute) predicate.Tribute {
	return predicate.Tribute(sql.NotPredicates(p))
}
