// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/agentexperience"
	"backend/ent/agentskill"
	"backend/ent/agenttask"
	"backend/ent/channelconnection"
	"backend/ent/conversation"
	"backend/ent/conversationmessage"
	"backend/ent/conversationparticipant"
	"backend/ent/memorial"
	"backend/ent/post"
	"backend/ent/predicate"
	"backend/ent/timertransaction"
	"backend/ent/user"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AgentQuery is the builder for querying Agent entities.
type AgentQuery struct {
	config
	ctx                            *QueryContext
	order                          []agent.OrderOption
	inters                         []Interceptor
	predicates                     []predicate.Agent
	withCreator                    *UserQuery
	withPosts                      *PostQuery
	withTimerTransactions          *TimerTransactionQuery
	withChannelConnections         *ChannelConnectionQuery
	withMemorial                   *MemorialQuery
	withSkills                     *AgentSkillQuery
	withTasks                      *AgentTaskQuery
	withExperiences                *AgentExperienceQuery
	withCreatedConversations       *ConversationQuery
	withConversationParticipations *ConversationParticipantQuery
	withSentMessages               *ConversationMessageQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AgentQuery builder.
func (aq *AgentQuery) Where(ps ...predicate.Agent) *AgentQuery {
	aq.predicates = append(aq.predicates, ps...)
	return aq
}

// Limit the number of records to be returned by this query.
func (aq *AgentQuery) Limit(limit int) *AgentQuery {
	aq.ctx.Limit = &limit
	return aq
}

// Offset to start from.
func (aq *AgentQuery) Offset(offset int) *AgentQuery {
	aq.ctx.Offset = &offset
	return aq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (aq *AgentQuery) Unique(unique bool) *AgentQuery {
	aq.ctx.Unique = &unique
	return aq
}

// Order specifies how the records should be ordered.
func (aq *AgentQuery) Order(o ...agent.OrderOption) *AgentQuery {
	aq.order = append(aq.order, o...)
	return aq
}

// QueryCreator chains the current query on the "creator" edge.
func (aq *AgentQuery) QueryCreator() *UserQuery {
	query := (&UserClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, agent.CreatorTable, agent.CreatorColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPosts chains the current query on the "posts" edge.
func (aq *AgentQuery) QueryPosts() *PostQuery {
	query := (&PostClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(post.Table, post.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.PostsTable, agent.PostsColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTimerTransactions chains the current query on the "timer_transactions" edge.
func (aq *AgentQuery) QueryTimerTransactions() *TimerTransactionQuery {
	query := (&TimerTransactionClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(timertransaction.Table, timertransaction.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.TimerTransactionsTable, agent.TimerTransactionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryChannelConnections chains the current query on the "channel_connections" edge.
func (aq *AgentQuery) QueryChannelConnections() *ChannelConnectionQuery {
	query := (&ChannelConnectionClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(channelconnection.Table, channelconnection.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.ChannelConnectionsTable, agent.ChannelConnectionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMemorial chains the current query on the "memorial" edge.
func (aq *AgentQuery) QueryMemorial() *MemorialQuery {
	query := (&MemorialClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(memorial.Table, memorial.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, agent.MemorialTable, agent.MemorialColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySkills chains the current query on the "skills" edge.
func (aq *AgentQuery) QuerySkills() *AgentSkillQuery {
	query := (&AgentSkillClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(agentskill.Table, agentskill.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.SkillsTable, agent.SkillsColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryTasks chains the current query on the "tasks" edge.
func (aq *AgentQuery) QueryTasks() *AgentTaskQuery {
	query := (&AgentTaskClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(agenttask.Table, agenttask.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.TasksTable, agent.TasksColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryExperiences chains the current query on the "experiences" edge.
func (aq *AgentQuery) QueryExperiences() *AgentExperienceQuery {
	query := (&AgentExperienceClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(agentexperience.Table, agentexperience.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.ExperiencesTable, agent.ExperiencesColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCreatedConversations chains the current query on the "created_conversations" edge.
func (aq *AgentQuery) QueryCreatedConversations() *ConversationQuery {
	query := (&ConversationClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(conversation.Table, conversation.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.CreatedConversationsTable, agent.CreatedConversationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryConversationParticipations chains the current query on the "conversation_participations" edge.
func (aq *AgentQuery) QueryConversationParticipations() *ConversationParticipantQuery {
	query := (&ConversationParticipantClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(conversationparticipant.Table, conversationparticipant.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.ConversationParticipationsTable, agent.ConversationParticipationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySentMessages chains the current query on the "sent_messages" edge.
func (aq *AgentQuery) QuerySentMessages() *ConversationMessageQuery {
	query := (&ConversationMessageClient{config: aq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := aq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := aq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(agent.Table, agent.FieldID, selector),
			sqlgraph.To(conversationmessage.Table, conversationmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, agent.SentMessagesTable, agent.SentMessagesColumn),
		)
		fromU = sqlgraph.SetNeighbors(aq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Agent entity from the query.
// Returns a *NotFoundError when no Agent was found.
func (aq *AgentQuery) First(ctx context.Context) (*Agent, error) {
	nodes, err := aq.Limit(1).All(setContextOp(ctx, aq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{agent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (aq *AgentQuery) FirstX(ctx context.Context) *Agent {
	node, err := aq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Agent ID from the query.
// Returns a *NotFoundError when no Agent ID was found.
func (aq *AgentQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aq.Limit(1).IDs(setContextOp(ctx, aq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{agent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (aq *AgentQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := aq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Agent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Agent entity is found.
// Returns a *NotFoundError when no Agent entities are found.
func (aq *AgentQuery) Only(ctx context.Context) (*Agent, error) {
	nodes, err := aq.Limit(2).All(setContextOp(ctx, aq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{agent.Label}
	default:
		return nil, &NotSingularError{agent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (aq *AgentQuery) OnlyX(ctx context.Context) *Agent {
	node, err := aq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Agent ID in the query.
// Returns a *NotSingularError when more than one Agent ID is found.
// Returns a *NotFoundError when no entities are found.
func (aq *AgentQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = aq.Limit(2).IDs(setContextOp(ctx, aq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{agent.Label}
	default:
		err = &NotSingularError{agent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (aq *AgentQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := aq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Agents.
func (aq *AgentQuery) All(ctx context.Context) ([]*Agent, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryAll)
	if err := aq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Agent, *AgentQuery]()
	return withInterceptors[[]*Agent](ctx, aq, qr, aq.inters)
}

// AllX is like All, but panics if an error occurs.
func (aq *AgentQuery) AllX(ctx context.Context) []*Agent {
	nodes, err := aq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Agent IDs.
func (aq *AgentQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if aq.ctx.Unique == nil && aq.path != nil {
		aq.Unique(true)
	}
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryIDs)
	if err = aq.Select(agent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (aq *AgentQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := aq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (aq *AgentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryCount)
	if err := aq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, aq, querierCount[*AgentQuery](), aq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (aq *AgentQuery) CountX(ctx context.Context) int {
	count, err := aq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (aq *AgentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, aq.ctx, ent.OpQueryExist)
	switch _, err := aq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (aq *AgentQuery) ExistX(ctx context.Context) bool {
	exist, err := aq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AgentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (aq *AgentQuery) Clone() *AgentQuery {
	if aq == nil {
		return nil
	}
	return &AgentQuery{
		config:                         aq.config,
		ctx:                            aq.ctx.Clone(),
		order:                          append([]agent.OrderOption{}, aq.order...),
		inters:                         append([]Interceptor{}, aq.inters...),
		predicates:                     append([]predicate.Agent{}, aq.predicates...),
		withCreator:                    aq.withCreator.Clone(),
		withPosts:                      aq.withPosts.Clone(),
		withTimerTransactions:          aq.withTimerTransactions.Clone(),
		withChannelConnections:         aq.withChannelConnections.Clone(),
		withMemorial:                   aq.withMemorial.Clone(),
		withSkills:                     aq.withSkills.Clone(),
		withTasks:                      aq.withTasks.Clone(),
		withExperiences:                aq.withExperiences.Clone(),
		withCreatedConversations:       aq.withCreatedConversations.Clone(),
		withConversationParticipations: aq.withConversationParticipations.Clone(),
		withSentMessages:               aq.withSentMessages.Clone(),
		// clone intermediate query.
		sql:  aq.sql.Clone(),
		path: aq.path,
	}
}

// WithCreator tells the query-builder to eager-load the nodes that are connected to
// the "creator" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithCreator(opts ...func(*UserQuery)) *AgentQuery {
	query := (&UserClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withCreator = query
	return aq
}

// WithPosts tells the query-builder to eager-load the nodes that are connected to
// the "posts" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithPosts(opts ...func(*PostQuery)) *AgentQuery {
	query := (&PostClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withPosts = query
	return aq
}

// WithTimerTransactions tells the query-builder to eager-load the nodes that are connected to
// the "timer_transactions" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithTimerTransactions(opts ...func(*TimerTransactionQuery)) *AgentQuery {
	query := (&TimerTransactionClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withTimerTransactions = query
	return aq
}

// WithChannelConnections tells the query-builder to eager-load the nodes that are connected to
// the "channel_connections" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithChannelConnections(opts ...func(*ChannelConnectionQuery)) *AgentQuery {
	query := (&ChannelConnectionClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withChannelConnections = query
	return aq
}

// WithMemorial tells the query-builder to eager-load the nodes that are connected to
// the "memorial" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithMemorial(opts ...func(*MemorialQuery)) *AgentQuery {
	query := (&MemorialClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withMemorial = query
	return aq
}

// WithSkills tells the query-builder to eager-load the nodes that are connected to
// the "skills" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithSkills(opts ...func(*AgentSkillQuery)) *AgentQuery {
	query := (&AgentSkillClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withSkills = query
	return aq
}

// WithTasks tells the query-builder to eager-load the nodes that are connected to
// the "tasks" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithTasks(opts ...func(*AgentTaskQuery)) *AgentQuery {
	query := (&AgentTaskClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withTasks = query
	return aq
}

// WithExperiences tells the query-builder to eager-load the nodes that are connected to
// the "experiences" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithExperiences(opts ...func(*AgentExperienceQuery)) *AgentQuery {
	query := (&AgentExperienceClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withExperiences = query
	return aq
}

// WithCreatedConversations tells the query-builder to eager-load the nodes that are connected to
// the "created_conversations" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithCreatedConversations(opts ...func(*ConversationQuery)) *AgentQuery {
	query := (&ConversationClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withCreatedConversations = query
	return aq
}

// WithConversationParticipations tells the query-builder to eager-load the nodes that are connected to
// the "conversation_participations" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithConversationParticipations(opts ...func(*ConversationParticipantQuery)) *AgentQuery {
	query := (&ConversationParticipantClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withConversationParticipations = query
	return aq
}

// WithSentMessages tells the query-builder to eager-load the nodes that are connected to
// the "sent_messages" edge. The optional arguments are used to configure the query builder of the edge.
func (aq *AgentQuery) WithSentMessages(opts ...func(*ConversationMessageQuery)) *AgentQuery {
	query := (&ConversationMessageClient{config: aq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	aq.withSentMessages = query
	return aq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Agent.Query().
//		GroupBy(agent.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (aq *AgentQuery) GroupBy(field string, fields ...string) *AgentGroupBy {
	aq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AgentGroupBy{build: aq}
	grbuild.flds = &aq.ctx.Fields
	grbuild.label = agent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.Agent.Query().
//		Select(agent.FieldCreatedAt).
//		Scan(ctx, &v)
func (aq *AgentQuery) Select(fields ...string) *AgentSelect {
	aq.ctx.Fields = append(aq.ctx.Fields, fields...)
	sbuild := &AgentSelect{AgentQuery: aq}
	sbuild.label = agent.Label
	sbuild.flds, sbuild.scan = &aq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AgentSelect configured with the given aggregations.
func (aq *AgentQuery) Aggregate(fns ...AggregateFunc) *AgentSelect {
	return aq.Select().Aggregate(fns...)
}

func (aq *AgentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range aq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, aq); err != nil {
				return err
			}
		}
	}
	for _, f := range aq.ctx.Fields {
		if !agent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if aq.path != nil {
		prev, err := aq.path(ctx)
		if err != nil {
			return err
		}
		aq.sql = prev
	}
	return nil
}

func (aq *AgentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Agent, error) {
	var (
		nodes       = []*Agent{}
		_spec       = aq.querySpec()
		loadedTypes = [11]bool{
			aq.withCreator != nil,
			aq.withPosts != nil,
			aq.withTimerTransactions != nil,
			aq.withChannelConnections != nil,
			aq.withMemorial != nil,
			aq.withSkills != nil,
			aq.withTasks != nil,
			aq.withExperiences != nil,
			aq.withCreatedConversations != nil,
			aq.withConversationParticipations != nil,
			aq.withSentMessages != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Agent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Agent{config: aq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, aq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := aq.withCreator; query != nil {
		if err := aq.loadCreator(ctx, query, nodes, nil,
			func(n *Agent, e *User) { n.Edges.Creator = e }); err != nil {
			return nil, err
		}
	}
	if query := aq.withPosts; query != nil {
		if err := aq.loadPosts(ctx, query, nodes,
			func(n *Agent) { n.Edges.Posts = []*Post{} },
			func(n *Agent, e *Post) { n.Edges.Posts = append(n.Edges.Posts, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withTimerTransactions; query != nil {
		if err := aq.loadTimerTransactions(ctx, query, nodes,
			func(n *Agent) { n.Edges.TimerTransactions = []*TimerTransaction{} },
			func(n *Agent, e *TimerTransaction) { n.Edges.TimerTransactions = append(n.Edges.TimerTransactions, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withChannelConnections; query != nil {
		if err := aq.loadChannelConnections(ctx, query, nodes,
			func(n *Agent) { n.Edges.ChannelConnections = []*ChannelConnection{} },
			func(n *Agent, e *ChannelConnection) {
				n.Edges.ChannelConnections = append(n.Edges.ChannelConnections, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := aq.withMemorial; query != nil {
		if err := aq.loadMemorial(ctx, query, nodes, nil,
			func(n *Agent, e *Memorial) { n.Edges.Memorial = e }); err != nil {
			return nil, err
		}
	}
	if query := aq.withSkills; query != nil {
		if err := aq.loadSkills(ctx, query, nodes,
			func(n *Agent) { n.Edges.Skills = []*AgentSkill{} },
			func(n *Agent, e *AgentSkill) { n.Edges.Skills = append(n.Edges.Skills, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withTasks; query != nil {
		if err := aq.loadTasks(ctx, query, nodes,
			func(n *Agent) { n.Edges.Tasks = []*AgentTask{} },
			func(n *Agent, e *AgentTask) { n.Edges.Tasks = append(n.Edges.Tasks, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withExperiences; query != nil {
		if err := aq.loadExperiences(ctx, query, nodes,
			func(n *Agent) { n.Edges.Experiences = []*AgentExperience{} },
			func(n *Agent, e *AgentExperience) { n.Edges.Experiences = append(n.Edges.Experiences, e) }); err != nil {
			return nil, err
		}
	}
	if query := aq.withCreatedConversations; query != nil {
		if err := aq.loadCreatedConversations(ctx, query, nodes,
			func(n *Agent) { n.Edges.CreatedConversations = []*Conversation{} },
			func(n *Agent, e *Conversation) {
				n.Edges.CreatedConversations = append(n.Edges.CreatedConversations, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := aq.withConversationParticipations; query != nil {
		if err := aq.loadConversationParticipations(ctx, query, nodes,
			func(n *Agent) { n.Edges.ConversationParticipations = []*ConversationParticipant{} },
			func(n *Agent, e *ConversationParticipant) {
				n.Edges.ConversationParticipations = append(n.Edges.ConversationParticipations, e)
			}); err != nil {
			return nil, err
		}
	}
	if query := aq.withSentMessages; query != nil {
		if err := aq.loadSentMessages(ctx, query, nodes,
			func(n *Agent) { n.Edges.SentMessages = []*ConversationMessage{} },
			func(n *Agent, e *ConversationMessage) { n.Edges.SentMessages = append(n.Edges.SentMessages, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (aq *AgentQuery) loadCreator(ctx context.Context, query *UserQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *User)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*Agent)
	for i := range nodes {
		fk := nodes[i].CreatorID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "creator_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (aq *AgentQuery) loadPosts(ctx context.Context, query *PostQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *Post)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(post.FieldAgentID)
	}
	query.Where(predicate.Post(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.PostsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadTimerTransactions(ctx context.Context, query *TimerTransactionQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *TimerTransaction)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(timertransaction.FieldAgentID)
	}
	query.Where(predicate.TimerTransaction(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.TimerTransactionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadChannelConnections(ctx context.Context, query *ChannelConnectionQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *ChannelConnection)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(channelconnection.FieldAgentID)
	}
	query.Where(predicate.ChannelConnection(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.ChannelConnectionsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadMemorial(ctx context.Context, query *MemorialQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *Memorial)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(memorial.FieldAgentID)
	}
	query.Where(predicate.Memorial(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.MemorialColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadSkills(ctx context.Context, query *AgentSkillQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *AgentSkill)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agentskill.FieldAgentID)
	}
	query.Where(predicate.AgentSkill(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.SkillsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentID
		if fk == nil {
			return fmt.Errorf(`foreign-key "agent_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadTasks(ctx context.Context, query *AgentTaskQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *AgentTask)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agenttask.FieldAgentID)
	}
	query.Where(predicate.AgentTask(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.TasksColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadExperiences(ctx context.Context, query *AgentExperienceQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *AgentExperience)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(agentexperience.FieldAgentID)
	}
	query.Where(predicate.AgentExperience(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.ExperiencesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadCreatedConversations(ctx context.Context, query *ConversationQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *Conversation)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(conversation.FieldCreatorAgentID)
	}
	query.Where(predicate.Conversation(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.CreatedConversationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.CreatorAgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "creator_agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadConversationParticipations(ctx context.Context, query *ConversationParticipantQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *ConversationParticipant)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(conversationparticipant.FieldAgentID)
	}
	query.Where(predicate.ConversationParticipant(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.ConversationParticipationsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.AgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (aq *AgentQuery) loadSentMessages(ctx context.Context, query *ConversationMessageQuery, nodes []*Agent, init func(*Agent), assign func(*Agent, *ConversationMessage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*Agent)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(conversationmessage.FieldSenderAgentID)
	}
	query.Where(predicate.ConversationMessage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(agent.SentMessagesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.SenderAgentID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "sender_agent_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (aq *AgentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := aq.querySpec()
	_spec.Node.Columns = aq.ctx.Fields
	if len(aq.ctx.Fields) > 0 {
		_spec.Unique = aq.ctx.Unique != nil && *aq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, aq.driver, _spec)
}

func (aq *AgentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	_spec.From = aq.sql
	if unique := aq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if aq.path != nil {
		_spec.Unique = true
	}
	if fields := aq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for i := range fields {
			if fields[i] != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if aq.withCreator != nil {
			_spec.Node.AddColumnOnce(agent.FieldCreatorID)
		}
	}
	if ps := aq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := aq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := aq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := aq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (aq *AgentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(aq.driver.Dialect())
	t1 := builder.Table(agent.Table)
	columns := aq.ctx.Fields
	if len(columns) == 0 {
		columns = agent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if aq.sql != nil {
		selector = aq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if aq.ctx.Unique != nil && *aq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range aq.predicates {
		p(selector)
	}
	for _, p := range aq.order {
		p(selector)
	}
	if offset := aq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := aq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AgentGroupBy is the group-by builder for Agent entities.
type AgentGroupBy struct {
	selector
	build *AgentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (agb *AgentGroupBy) Aggregate(fns ...AggregateFunc) *AgentGroupBy {
	agb.fns = append(agb.fns, fns...)
	return agb
}

// Scan applies the selector query and scans the result into the given value.
func (agb *AgentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, agb.build.ctx, ent.OpQueryGroupBy)
	if err := agb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentQuery, *AgentGroupBy](ctx, agb.build, agb, agb.build.inters, v)
}

func (agb *AgentGroupBy) sqlScan(ctx context.Context, root *AgentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(agb.fns))
	for _, fn := range agb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*agb.flds)+len(agb.fns))
		for _, f := range *agb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*agb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := agb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AgentSelect is the builder for selecting fields of Agent entities.
type AgentSelect struct {
	*AgentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (as *AgentSelect) Aggregate(fns ...AggregateFunc) *AgentSelect {
	as.fns = append(as.fns, fns...)
	return as
}

// Scan applies the selector query and scans the result into the given value.
func (as *AgentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, as.ctx, ent.OpQuerySelect)
	if err := as.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AgentQuery, *AgentSelect](ctx, as.AgentQuery, as, as.inters, v)
}

func (as *AgentSelect) sqlScan(ctx context.Context, root *AgentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(as.fns))
	for _, fn := range as.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*as.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := as.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
