// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/agentskill"
	"backend/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// AgentSkill is the model entity for the AgentSkill schema.
type AgentSkill struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// OwnerUserID holds the value of the "owner_user_id" field.
	OwnerUserID uuid.UUID `json:"owner_user_id,omitempty"`
	// AgentID holds the value of the "agent_id" field.
	AgentID *uuid.UUID `json:"agent_id,omitempty"`
	// SourceSkillID holds the value of the "source_skill_id" field.
	SourceSkillID *uuid.UUID `json:"source_skill_id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Instructions holds the value of the "instructions" field.
	Instructions string `json:"instructions,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Category holds the value of the "category" field.
	Category string `json:"category,omitempty"`
	// Version holds the value of the "version" field.
	Version *string `json:"version,omitempty"`
	// TaughtAt holds the value of the "taught_at" field.
	TaughtAt *time.Time `json:"taught_at,omitempty"`
	// AliveAgentGatewayID holds the value of the "alive_agent_gateway_id" field.
	AliveAgentGatewayID *string `json:"alive_agent_gateway_id,omitempty"`
	// AliveAgentSkillID holds the value of the "alive_agent_skill_id" field.
	AliveAgentSkillID *string `json:"alive_agent_skill_id,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AgentSkillQuery when eager-loading is set.
	Edges        AgentSkillEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AgentSkillEdges holds the relations/edges for other nodes in the graph.
type AgentSkillEdges struct {
	// Owner holds the value of the owner edge.
	Owner *User `json:"owner,omitempty"`
	// Agent holds the value of the agent edge.
	Agent *Agent `json:"agent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentSkillEdges) OwnerOrErr() (*User, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// AgentOrErr returns the Agent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AgentSkillEdges) AgentOrErr() (*Agent, error) {
	if e.Agent != nil {
		return e.Agent, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: agent.Label}
	}
	return nil, &NotLoadedError{edge: "agent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AgentSkill) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case agentskill.FieldAgentID, agentskill.FieldSourceSkillID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case agentskill.FieldName, agentskill.FieldDescription, agentskill.FieldInstructions, agentskill.FieldStatus, agentskill.FieldCategory, agentskill.FieldVersion, agentskill.FieldAliveAgentGatewayID, agentskill.FieldAliveAgentSkillID:
			values[i] = new(sql.NullString)
		case agentskill.FieldCreatedAt, agentskill.FieldUpdatedAt, agentskill.FieldTaughtAt, agentskill.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case agentskill.FieldID, agentskill.FieldOwnerUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AgentSkill fields.
func (_m *AgentSkill) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case agentskill.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case agentskill.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case agentskill.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case agentskill.FieldOwnerUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_user_id", values[i])
			} else if value != nil {
				_m.OwnerUserID = *value
			}
		case agentskill.FieldAgentID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field agent_id", values[i])
			} else if value.Valid {
				_m.AgentID = new(uuid.UUID)
				*_m.AgentID = *value.S.(*uuid.UUID)
			}
		case agentskill.FieldSourceSkillID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field source_skill_id", values[i])
			} else if value.Valid {
				_m.SourceSkillID = new(uuid.UUID)
				*_m.SourceSkillID = *value.S.(*uuid.UUID)
			}
		case agentskill.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case agentskill.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case agentskill.FieldInstructions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field instructions", values[i])
			} else if value.Valid {
				_m.Instructions = value.String
			}
		case agentskill.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case agentskill.FieldCategory:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field category", values[i])
			} else if value.Valid {
				_m.Category = value.String
			}
		case agentskill.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = new(string)
				*_m.Version = value.String
			}
		case agentskill.FieldTaughtAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field taught_at", values[i])
			} else if value.Valid {
				_m.TaughtAt = new(time.Time)
				*_m.TaughtAt = value.Time
			}
		case agentskill.FieldAliveAgentGatewayID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alive_agent_gateway_id", values[i])
			} else if value.Valid {
				_m.AliveAgentGatewayID = new(string)
				*_m.AliveAgentGatewayID = value.String
			}
		case agentskill.FieldAliveAgentSkillID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alive_agent_skill_id", values[i])
			} else if value.Valid {
				_m.AliveAgentSkillID = new(string)
				*_m.AliveAgentSkillID = value.String
			}
		case agentskill.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AgentSkill.
// This includes values selected through modifiers, order, etc.
func (_m *AgentSkill) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the AgentSkill entity.
func (_m *AgentSkill) QueryOwner() *UserQuery {
	return NewAgentSkillClient(_m.config).QueryOwner(_m)
}

// QueryAgent queries the "agent" edge of the AgentSkill entity.
func (_m *AgentSkill) QueryAgent() *AgentQuery {
	return NewAgentSkillClient(_m.config).QueryAgent(_m)
}

// Update returns a builder for updating this AgentSkill.
// Note that you need to call AgentSkill.Unwrap() before calling this method if this AgentSkill
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AgentSkill) Update() *AgentSkillUpdateOne {
	return NewAgentSkillClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AgentSkill entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AgentSkill) Unwrap() *AgentSkill {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AgentSkill is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AgentSkill) String() string {
	var builder strings.Builder
	builder.WriteString("AgentSkill(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("owner_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OwnerUserID))
	builder.WriteString(", ")
	if v := _m.AgentID; v != nil {
		builder.WriteString("agent_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SourceSkillID; v != nil {
		builder.WriteString("source_skill_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("instructions=")
	builder.WriteString(_m.Instructions)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("category=")
	builder.WriteString(_m.Category)
	builder.WriteString(", ")
	if v := _m.Version; v != nil {
		builder.WriteString("version=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.TaughtAt; v != nil {
		builder.WriteString("taught_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.AliveAgentGatewayID; v != nil {
		builder.WriteString("alive_agent_gateway_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AliveAgentSkillID; v != nil {
		builder.WriteString("alive_agent_skill_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// AgentSkills is a parsable slice of AgentSkill.
type AgentSkills []*AgentSkill
