// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/agentskill"
	"backend/ent/predicate"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AgentSkillUpdate is the builder for updating AgentSkill entities.
type AgentSkillUpdate struct {
	config
	hooks    []Hook
	mutation *AgentSkillMutation
}

// Where appends a list predicates to the AgentSkillUpdate builder.
func (_u *AgentSkillUpdate) Where(ps ...predicate.AgentSkill) *AgentSkillUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentSkillUpdate) SetUpdatedAt(v time.Time) *AgentSkillUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *AgentSkillUpdate) SetOwnerUserID(v uuid.UUID) *AgentSkillUpdate {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableOwnerUserID(v *uuid.UUID) *AgentSkillUpdate {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentSkillUpdate) SetAgentID(v uuid.UUID) *AgentSkillUpdate {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableAgentID(v *uuid.UUID) *AgentSkillUpdate {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *AgentSkillUpdate) ClearAgentID() *AgentSkillUpdate {
	_u.mutation.ClearAgentID()
	return _u
}

// SetSourceSkillID sets the "source_skill_id" field.
func (_u *AgentSkillUpdate) SetSourceSkillID(v uuid.UUID) *AgentSkillUpdate {
	_u.mutation.SetSourceSkillID(v)
	return _u
}

// SetNillableSourceSkillID sets the "source_skill_id" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableSourceSkillID(v *uuid.UUID) *AgentSkillUpdate {
	if v != nil {
		_u.SetSourceSkillID(*v)
	}
	return _u
}

// ClearSourceSkillID clears the value of the "source_skill_id" field.
func (_u *AgentSkillUpdate) ClearSourceSkillID() *AgentSkillUpdate {
	_u.mutation.ClearSourceSkillID()
	return _u
}

// SetName sets the "name" field.
func (_u *AgentSkillUpdate) SetName(v string) *AgentSkillUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableName(v *string) *AgentSkillUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AgentSkillUpdate) SetDescription(v string) *AgentSkillUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableDescription(v *string) *AgentSkillUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetInstructions sets the "instructions" field.
func (_u *AgentSkillUpdate) SetInstructions(v string) *AgentSkillUpdate {
	_u.mutation.SetInstructions(v)
	return _u
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableInstructions(v *string) *AgentSkillUpdate {
	if v != nil {
		_u.SetInstructions(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentSkillUpdate) SetStatus(v string) *AgentSkillUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableStatus(v *string) *AgentSkillUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *AgentSkillUpdate) SetCategory(v string) *AgentSkillUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableCategory(v *string) *AgentSkillUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentSkillUpdate) SetVersion(v string) *AgentSkillUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableVersion(v *string) *AgentSkillUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *AgentSkillUpdate) ClearVersion() *AgentSkillUpdate {
	_u.mutation.ClearVersion()
	return _u
}

// SetTaughtAt sets the "taught_at" field.
func (_u *AgentSkillUpdate) SetTaughtAt(v time.Time) *AgentSkillUpdate {
	_u.mutation.SetTaughtAt(v)
	return _u
}

// SetNillableTaughtAt sets the "taught_at" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableTaughtAt(v *time.Time) *AgentSkillUpdate {
	if v != nil {
		_u.SetTaughtAt(*v)
	}
	return _u
}

// ClearTaughtAt clears the value of the "taught_at" field.
func (_u *AgentSkillUpdate) ClearTaughtAt() *AgentSkillUpdate {
	_u.mutation.ClearTaughtAt()
	return _u
}

// SetAliveAgentGatewayID sets the "alive_agent_gateway_id" field.
func (_u *AgentSkillUpdate) SetAliveAgentGatewayID(v string) *AgentSkillUpdate {
	_u.mutation.SetAliveAgentGatewayID(v)
	return _u
}

// SetNillableAliveAgentGatewayID sets the "alive_agent_gateway_id" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableAliveAgentGatewayID(v *string) *AgentSkillUpdate {
	if v != nil {
		_u.SetAliveAgentGatewayID(*v)
	}
	return _u
}

// ClearAliveAgentGatewayID clears the value of the "alive_agent_gateway_id" field.
func (_u *AgentSkillUpdate) ClearAliveAgentGatewayID() *AgentSkillUpdate {
	_u.mutation.ClearAliveAgentGatewayID()
	return _u
}

// SetAliveAgentSkillID sets the "alive_agent_skill_id" field.
func (_u *AgentSkillUpdate) SetAliveAgentSkillID(v string) *AgentSkillUpdate {
	_u.mutation.SetAliveAgentSkillID(v)
	return _u
}

// SetNillableAliveAgentSkillID sets the "alive_agent_skill_id" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableAliveAgentSkillID(v *string) *AgentSkillUpdate {
	if v != nil {
		_u.SetAliveAgentSkillID(*v)
	}
	return _u
}

// ClearAliveAgentSkillID clears the value of the "alive_agent_skill_id" field.
func (_u *AgentSkillUpdate) ClearAliveAgentSkillID() *AgentSkillUpdate {
	_u.mutation.ClearAliveAgentSkillID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentSkillUpdate) SetDeletedAt(v time.Time) *AgentSkillUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentSkillUpdate) SetNillableDeletedAt(v *time.Time) *AgentSkillUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AgentSkillUpdate) ClearDeletedAt() *AgentSkillUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *AgentSkillUpdate) SetOwnerID(id uuid.UUID) *AgentSkillUpdate {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *AgentSkillUpdate) SetOwner(v *User) *AgentSkillUpdate {
	return _u.SetOwnerID(v.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *AgentSkillUpdate) SetAgent(v *Agent) *AgentSkillUpdate {
	return _u.SetAgentID(v.ID)
}

// Mutation returns the AgentSkillMutation object of the builder.
func (_u *AgentSkillUpdate) Mutation() *AgentSkillMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *AgentSkillUpdate) ClearOwner() *AgentSkillUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *AgentSkillUpdate) ClearAgent() *AgentSkillUpdate {
	_u.mutation.ClearAgent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentSkillUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentSkillUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentSkillUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentSkillUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentSkillUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentskill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentSkillUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agentskill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := agentskill.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Instructions(); ok {
		if err := agentskill.InstructionsValidator(v); err != nil {
			return &ValidationError{Name: "instructions", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.instructions": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentSkill.owner"`)
	}
	return nil
}

func (_u *AgentSkillUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentskill.Table, agentskill.Columns, sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentskill.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceSkillID(); ok {
		_spec.SetField(agentskill.FieldSourceSkillID, field.TypeUUID, value)
	}
	if _u.mutation.SourceSkillIDCleared() {
		_spec.ClearField(agentskill.FieldSourceSkillID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentskill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(agentskill.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Instructions(); ok {
		_spec.SetField(agentskill.FieldInstructions, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentskill.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(agentskill.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agentskill.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(agentskill.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.TaughtAt(); ok {
		_spec.SetField(agentskill.FieldTaughtAt, field.TypeTime, value)
	}
	if _u.mutation.TaughtAtCleared() {
		_spec.ClearField(agentskill.FieldTaughtAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AliveAgentGatewayID(); ok {
		_spec.SetField(agentskill.FieldAliveAgentGatewayID, field.TypeString, value)
	}
	if _u.mutation.AliveAgentGatewayIDCleared() {
		_spec.ClearField(agentskill.FieldAliveAgentGatewayID, field.TypeString)
	}
	if value, ok := _u.mutation.AliveAgentSkillID(); ok {
		_spec.SetField(agentskill.FieldAliveAgentSkillID, field.TypeString, value)
	}
	if _u.mutation.AliveAgentSkillIDCleared() {
		_spec.ClearField(agentskill.FieldAliveAgentSkillID, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentskill.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(agentskill.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.OwnerTable,
			Columns: []string{agentskill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.OwnerTable,
			Columns: []string{agentskill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.AgentTable,
			Columns: []string{agentskill.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.AgentTable,
			Columns: []string{agentskill.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentskill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentSkillUpdateOne is the builder for updating a single AgentSkill entity.
type AgentSkillUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentSkillMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentSkillUpdateOne) SetUpdatedAt(v time.Time) *AgentSkillUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerUserID sets the "owner_user_id" field.
func (_u *AgentSkillUpdateOne) SetOwnerUserID(v uuid.UUID) *AgentSkillUpdateOne {
	_u.mutation.SetOwnerUserID(v)
	return _u
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableOwnerUserID(v *uuid.UUID) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetOwnerUserID(*v)
	}
	return _u
}

// SetAgentID sets the "agent_id" field.
func (_u *AgentSkillUpdateOne) SetAgentID(v uuid.UUID) *AgentSkillUpdateOne {
	_u.mutation.SetAgentID(v)
	return _u
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableAgentID(v *uuid.UUID) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetAgentID(*v)
	}
	return _u
}

// ClearAgentID clears the value of the "agent_id" field.
func (_u *AgentSkillUpdateOne) ClearAgentID() *AgentSkillUpdateOne {
	_u.mutation.ClearAgentID()
	return _u
}

// SetSourceSkillID sets the "source_skill_id" field.
func (_u *AgentSkillUpdateOne) SetSourceSkillID(v uuid.UUID) *AgentSkillUpdateOne {
	_u.mutation.SetSourceSkillID(v)
	return _u
}

// SetNillableSourceSkillID sets the "source_skill_id" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableSourceSkillID(v *uuid.UUID) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetSourceSkillID(*v)
	}
	return _u
}

// ClearSourceSkillID clears the value of the "source_skill_id" field.
func (_u *AgentSkillUpdateOne) ClearSourceSkillID() *AgentSkillUpdateOne {
	_u.mutation.ClearSourceSkillID()
	return _u
}

// SetName sets the "name" field.
func (_u *AgentSkillUpdateOne) SetName(v string) *AgentSkillUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableName(v *string) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *AgentSkillUpdateOne) SetDescription(v string) *AgentSkillUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableDescription(v *string) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetInstructions sets the "instructions" field.
func (_u *AgentSkillUpdateOne) SetInstructions(v string) *AgentSkillUpdateOne {
	_u.mutation.SetInstructions(v)
	return _u
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableInstructions(v *string) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetInstructions(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentSkillUpdateOne) SetStatus(v string) *AgentSkillUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableStatus(v *string) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *AgentSkillUpdateOne) SetCategory(v string) *AgentSkillUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableCategory(v *string) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AgentSkillUpdateOne) SetVersion(v string) *AgentSkillUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableVersion(v *string) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// ClearVersion clears the value of the "version" field.
func (_u *AgentSkillUpdateOne) ClearVersion() *AgentSkillUpdateOne {
	_u.mutation.ClearVersion()
	return _u
}

// SetTaughtAt sets the "taught_at" field.
func (_u *AgentSkillUpdateOne) SetTaughtAt(v time.Time) *AgentSkillUpdateOne {
	_u.mutation.SetTaughtAt(v)
	return _u
}

// SetNillableTaughtAt sets the "taught_at" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableTaughtAt(v *time.Time) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetTaughtAt(*v)
	}
	return _u
}

// ClearTaughtAt clears the value of the "taught_at" field.
func (_u *AgentSkillUpdateOne) ClearTaughtAt() *AgentSkillUpdateOne {
	_u.mutation.ClearTaughtAt()
	return _u
}

// SetAliveAgentGatewayID sets the "alive_agent_gateway_id" field.
func (_u *AgentSkillUpdateOne) SetAliveAgentGatewayID(v string) *AgentSkillUpdateOne {
	_u.mutation.SetAliveAgentGatewayID(v)
	return _u
}

// SetNillableAliveAgentGatewayID sets the "alive_agent_gateway_id" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableAliveAgentGatewayID(v *string) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetAliveAgentGatewayID(*v)
	}
	return _u
}

// ClearAliveAgentGatewayID clears the value of the "alive_agent_gateway_id" field.
func (_u *AgentSkillUpdateOne) ClearAliveAgentGatewayID() *AgentSkillUpdateOne {
	_u.mutation.ClearAliveAgentGatewayID()
	return _u
}

// SetAliveAgentSkillID sets the "alive_agent_skill_id" field.
func (_u *AgentSkillUpdateOne) SetAliveAgentSkillID(v string) *AgentSkillUpdateOne {
	_u.mutation.SetAliveAgentSkillID(v)
	return _u
}

// SetNillableAliveAgentSkillID sets the "alive_agent_skill_id" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableAliveAgentSkillID(v *string) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetAliveAgentSkillID(*v)
	}
	return _u
}

// ClearAliveAgentSkillID clears the value of the "alive_agent_skill_id" field.
func (_u *AgentSkillUpdateOne) ClearAliveAgentSkillID() *AgentSkillUpdateOne {
	_u.mutation.ClearAliveAgentSkillID()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AgentSkillUpdateOne) SetDeletedAt(v time.Time) *AgentSkillUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AgentSkillUpdateOne) SetNillableDeletedAt(v *time.Time) *AgentSkillUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AgentSkillUpdateOne) ClearDeletedAt() *AgentSkillUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (_u *AgentSkillUpdateOne) SetOwnerID(id uuid.UUID) *AgentSkillUpdateOne {
	_u.mutation.SetOwnerID(id)
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *AgentSkillUpdateOne) SetOwner(v *User) *AgentSkillUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_u *AgentSkillUpdateOne) SetAgent(v *Agent) *AgentSkillUpdateOne {
	return _u.SetAgentID(v.ID)
}

// Mutation returns the AgentSkillMutation object of the builder.
func (_u *AgentSkillUpdateOne) Mutation() *AgentSkillMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *AgentSkillUpdateOne) ClearOwner() *AgentSkillUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (_u *AgentSkillUpdateOne) ClearAgent() *AgentSkillUpdateOne {
	_u.mutation.ClearAgent()
	return _u
}

// Where appends a list predicates to the AgentSkillUpdate builder.
func (_u *AgentSkillUpdateOne) Where(ps ...predicate.AgentSkill) *AgentSkillUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentSkillUpdateOne) Select(field string, fields ...string) *AgentSkillUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AgentSkill entity.
func (_u *AgentSkillUpdateOne) Save(ctx context.Context) (*AgentSkill, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentSkillUpdateOne) SaveX(ctx context.Context) *AgentSkill {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentSkillUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentSkillUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentSkillUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agentskill.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentSkillUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := agentskill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := agentskill.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Instructions(); ok {
		if err := agentskill.InstructionsValidator(v); err != nil {
			return &ValidationError{Name: "instructions", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.instructions": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentSkill.owner"`)
	}
	return nil
}

func (_u *AgentSkillUpdateOne) sqlSave(ctx context.Context) (_node *AgentSkill, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentskill.Table, agentskill.Columns, sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentSkill.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentskill.FieldID)
		for _, f := range fields {
			if !agentskill.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentskill.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agentskill.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SourceSkillID(); ok {
		_spec.SetField(agentskill.FieldSourceSkillID, field.TypeUUID, value)
	}
	if _u.mutation.SourceSkillIDCleared() {
		_spec.ClearField(agentskill.FieldSourceSkillID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(agentskill.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(agentskill.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Instructions(); ok {
		_spec.SetField(agentskill.FieldInstructions, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agentskill.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(agentskill.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(agentskill.FieldVersion, field.TypeString, value)
	}
	if _u.mutation.VersionCleared() {
		_spec.ClearField(agentskill.FieldVersion, field.TypeString)
	}
	if value, ok := _u.mutation.TaughtAt(); ok {
		_spec.SetField(agentskill.FieldTaughtAt, field.TypeTime, value)
	}
	if _u.mutation.TaughtAtCleared() {
		_spec.ClearField(agentskill.FieldTaughtAt, field.TypeTime)
	}
	if value, ok := _u.mutation.AliveAgentGatewayID(); ok {
		_spec.SetField(agentskill.FieldAliveAgentGatewayID, field.TypeString, value)
	}
	if _u.mutation.AliveAgentGatewayIDCleared() {
		_spec.ClearField(agentskill.FieldAliveAgentGatewayID, field.TypeString)
	}
	if value, ok := _u.mutation.AliveAgentSkillID(); ok {
		_spec.SetField(agentskill.FieldAliveAgentSkillID, field.TypeString, value)
	}
	if _u.mutation.AliveAgentSkillIDCleared() {
		_spec.ClearField(agentskill.FieldAliveAgentSkillID, field.TypeString)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(agentskill.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(agentskill.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.OwnerTable,
			Columns: []string{agentskill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.OwnerTable,
			Columns: []string{agentskill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.AgentTable,
			Columns: []string{agentskill.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.AgentTable,
			Columns: []string{agentskill.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentSkill{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentskill.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
