// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/agenttask"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AgentTaskUpdate is the builder for updating AgentTask entities.
type AgentTaskUpdate struct {
	config
	hooks    []Hook
	mutation *AgentTaskMutation
}

// Where appends a list predicates to the AgentTaskUpdate builder.
func (atu *AgentTaskUpdate) Where(ps ...predicate.AgentTask) *AgentTaskUpdate {
	atu.mutation.Where(ps...)
	return atu
}

// SetUpdatedAt sets the "updated_at" field.
func (atu *AgentTaskUpdate) SetUpdatedAt(t time.Time) *AgentTaskUpdate {
	atu.mutation.SetUpdatedAt(t)
	return atu
}

// SetAgentID sets the "agent_id" field.
func (atu *AgentTaskUpdate) SetAgentID(u uuid.UUID) *AgentTaskUpdate {
	atu.mutation.SetAgentID(u)
	return atu
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (atu *AgentTaskUpdate) SetNillableAgentID(u *uuid.UUID) *AgentTaskUpdate {
	if u != nil {
		atu.SetAgentID(*u)
	}
	return atu
}

// SetTitle sets the "title" field.
func (atu *AgentTaskUpdate) SetTitle(s string) *AgentTaskUpdate {
	atu.mutation.SetTitle(s)
	return atu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (atu *AgentTaskUpdate) SetNillableTitle(s *string) *AgentTaskUpdate {
	if s != nil {
		atu.SetTitle(*s)
	}
	return atu
}

// SetDescription sets the "description" field.
func (atu *AgentTaskUpdate) SetDescription(s string) *AgentTaskUpdate {
	atu.mutation.SetDescription(s)
	return atu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (atu *AgentTaskUpdate) SetNillableDescription(s *string) *AgentTaskUpdate {
	if s != nil {
		atu.SetDescription(*s)
	}
	return atu
}

// ClearDescription clears the value of the "description" field.
func (atu *AgentTaskUpdate) ClearDescription() *AgentTaskUpdate {
	atu.mutation.ClearDescription()
	return atu
}

// SetStatus sets the "status" field.
func (atu *AgentTaskUpdate) SetStatus(s string) *AgentTaskUpdate {
	atu.mutation.SetStatus(s)
	return atu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (atu *AgentTaskUpdate) SetNillableStatus(s *string) *AgentTaskUpdate {
	if s != nil {
		atu.SetStatus(*s)
	}
	return atu
}

// SetPriority sets the "priority" field.
func (atu *AgentTaskUpdate) SetPriority(s string) *AgentTaskUpdate {
	atu.mutation.SetPriority(s)
	return atu
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (atu *AgentTaskUpdate) SetNillablePriority(s *string) *AgentTaskUpdate {
	if s != nil {
		atu.SetPriority(*s)
	}
	return atu
}

// ClearPriority clears the value of the "priority" field.
func (atu *AgentTaskUpdate) ClearPriority() *AgentTaskUpdate {
	atu.mutation.ClearPriority()
	return atu
}

// SetProgress sets the "progress" field.
func (atu *AgentTaskUpdate) SetProgress(i int) *AgentTaskUpdate {
	atu.mutation.ResetProgress()
	atu.mutation.SetProgress(i)
	return atu
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (atu *AgentTaskUpdate) SetNillableProgress(i *int) *AgentTaskUpdate {
	if i != nil {
		atu.SetProgress(*i)
	}
	return atu
}

// AddProgress adds i to the "progress" field.
func (atu *AgentTaskUpdate) AddProgress(i int) *AgentTaskUpdate {
	atu.mutation.AddProgress(i)
	return atu
}

// SetDeletedAt sets the "deleted_at" field.
func (atu *AgentTaskUpdate) SetDeletedAt(t time.Time) *AgentTaskUpdate {
	atu.mutation.SetDeletedAt(t)
	return atu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (atu *AgentTaskUpdate) SetNillableDeletedAt(t *time.Time) *AgentTaskUpdate {
	if t != nil {
		atu.SetDeletedAt(*t)
	}
	return atu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (atu *AgentTaskUpdate) ClearDeletedAt() *AgentTaskUpdate {
	atu.mutation.ClearDeletedAt()
	return atu
}

// SetAgent sets the "agent" edge to the Agent entity.
func (atu *AgentTaskUpdate) SetAgent(a *Agent) *AgentTaskUpdate {
	return atu.SetAgentID(a.ID)
}

// Mutation returns the AgentTaskMutation object of the builder.
func (atu *AgentTaskUpdate) Mutation() *AgentTaskMutation {
	return atu.mutation
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (atu *AgentTaskUpdate) ClearAgent() *AgentTaskUpdate {
	atu.mutation.ClearAgent()
	return atu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (atu *AgentTaskUpdate) Save(ctx context.Context) (int, error) {
	atu.defaults()
	return withHooks(ctx, atu.sqlSave, atu.mutation, atu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atu *AgentTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := atu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (atu *AgentTaskUpdate) Exec(ctx context.Context) error {
	_, err := atu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atu *AgentTaskUpdate) ExecX(ctx context.Context) {
	if err := atu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (atu *AgentTaskUpdate) defaults() {
	if _, ok := atu.mutation.UpdatedAt(); !ok {
		v := agenttask.UpdateDefaultUpdatedAt()
		atu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atu *AgentTaskUpdate) check() error {
	if v, ok := atu.mutation.Title(); ok {
		if err := agenttask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "AgentTask.title": %w`, err)}
		}
	}
	if v, ok := atu.mutation.Description(); ok {
		if err := agenttask.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentTask.description": %w`, err)}
		}
	}
	if v, ok := atu.mutation.Progress(); ok {
		if err := agenttask.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "AgentTask.progress": %w`, err)}
		}
	}
	if atu.mutation.AgentCleared() && len(atu.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentTask.agent"`)
	}
	return nil
}

func (atu *AgentTaskUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := atu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttask.Table, agenttask.Columns, sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID))
	if ps := atu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := atu.mutation.UpdatedAt(); ok {
		_spec.SetField(agenttask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := atu.mutation.Title(); ok {
		_spec.SetField(agenttask.FieldTitle, field.TypeString, value)
	}
	if value, ok := atu.mutation.Description(); ok {
		_spec.SetField(agenttask.FieldDescription, field.TypeString, value)
	}
	if atu.mutation.DescriptionCleared() {
		_spec.ClearField(agenttask.FieldDescription, field.TypeString)
	}
	if value, ok := atu.mutation.Status(); ok {
		_spec.SetField(agenttask.FieldStatus, field.TypeString, value)
	}
	if value, ok := atu.mutation.Priority(); ok {
		_spec.SetField(agenttask.FieldPriority, field.TypeString, value)
	}
	if atu.mutation.PriorityCleared() {
		_spec.ClearField(agenttask.FieldPriority, field.TypeString)
	}
	if value, ok := atu.mutation.Progress(); ok {
		_spec.SetField(agenttask.FieldProgress, field.TypeInt, value)
	}
	if value, ok := atu.mutation.AddedProgress(); ok {
		_spec.AddField(agenttask.FieldProgress, field.TypeInt, value)
	}
	if value, ok := atu.mutation.DeletedAt(); ok {
		_spec.SetField(agenttask.FieldDeletedAt, field.TypeTime, value)
	}
	if atu.mutation.DeletedAtCleared() {
		_spec.ClearField(agenttask.FieldDeletedAt, field.TypeTime)
	}
	if atu.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttask.AgentTable,
			Columns: []string{agenttask.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atu.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttask.AgentTable,
			Columns: []string{agenttask.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, atu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	atu.mutation.done = true
	return n, nil
}

// AgentTaskUpdateOne is the builder for updating a single AgentTask entity.
type AgentTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentTaskMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (atuo *AgentTaskUpdateOne) SetUpdatedAt(t time.Time) *AgentTaskUpdateOne {
	atuo.mutation.SetUpdatedAt(t)
	return atuo
}

// SetAgentID sets the "agent_id" field.
func (atuo *AgentTaskUpdateOne) SetAgentID(u uuid.UUID) *AgentTaskUpdateOne {
	atuo.mutation.SetAgentID(u)
	return atuo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (atuo *AgentTaskUpdateOne) SetNillableAgentID(u *uuid.UUID) *AgentTaskUpdateOne {
	if u != nil {
		atuo.SetAgentID(*u)
	}
	return atuo
}

// SetTitle sets the "title" field.
func (atuo *AgentTaskUpdateOne) SetTitle(s string) *AgentTaskUpdateOne {
	atuo.mutation.SetTitle(s)
	return atuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (atuo *AgentTaskUpdateOne) SetNillableTitle(s *string) *AgentTaskUpdateOne {
	if s != nil {
		atuo.SetTitle(*s)
	}
	return atuo
}

// SetDescription sets the "description" field.
func (atuo *AgentTaskUpdateOne) SetDescription(s string) *AgentTaskUpdateOne {
	atuo.mutation.SetDescription(s)
	return atuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (atuo *AgentTaskUpdateOne) SetNillableDescription(s *string) *AgentTaskUpdateOne {
	if s != nil {
		atuo.SetDescription(*s)
	}
	return atuo
}

// ClearDescription clears the value of the "description" field.
func (atuo *AgentTaskUpdateOne) ClearDescription() *AgentTaskUpdateOne {
	atuo.mutation.ClearDescription()
	return atuo
}

// SetStatus sets the "status" field.
func (atuo *AgentTaskUpdateOne) SetStatus(s string) *AgentTaskUpdateOne {
	atuo.mutation.SetStatus(s)
	return atuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (atuo *AgentTaskUpdateOne) SetNillableStatus(s *string) *AgentTaskUpdateOne {
	if s != nil {
		atuo.SetStatus(*s)
	}
	return atuo
}

// SetPriority sets the "priority" field.
func (atuo *AgentTaskUpdateOne) SetPriority(s string) *AgentTaskUpdateOne {
	atuo.mutation.SetPriority(s)
	return atuo
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (atuo *AgentTaskUpdateOne) SetNillablePriority(s *string) *AgentTaskUpdateOne {
	if s != nil {
		atuo.SetPriority(*s)
	}
	return atuo
}

// ClearPriority clears the value of the "priority" field.
func (atuo *AgentTaskUpdateOne) ClearPriority() *AgentTaskUpdateOne {
	atuo.mutation.ClearPriority()
	return atuo
}

// SetProgress sets the "progress" field.
func (atuo *AgentTaskUpdateOne) SetProgress(i int) *AgentTaskUpdateOne {
	atuo.mutation.ResetProgress()
	atuo.mutation.SetProgress(i)
	return atuo
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (atuo *AgentTaskUpdateOne) SetNillableProgress(i *int) *AgentTaskUpdateOne {
	if i != nil {
		atuo.SetProgress(*i)
	}
	return atuo
}

// AddProgress adds i to the "progress" field.
func (atuo *AgentTaskUpdateOne) AddProgress(i int) *AgentTaskUpdateOne {
	atuo.mutation.AddProgress(i)
	return atuo
}

// SetDeletedAt sets the "deleted_at" field.
func (atuo *AgentTaskUpdateOne) SetDeletedAt(t time.Time) *AgentTaskUpdateOne {
	atuo.mutation.SetDeletedAt(t)
	return atuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (atuo *AgentTaskUpdateOne) SetNillableDeletedAt(t *time.Time) *AgentTaskUpdateOne {
	if t != nil {
		atuo.SetDeletedAt(*t)
	}
	return atuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (atuo *AgentTaskUpdateOne) ClearDeletedAt() *AgentTaskUpdateOne {
	atuo.mutation.ClearDeletedAt()
	return atuo
}

// SetAgent sets the "agent" edge to the Agent entity.
func (atuo *AgentTaskUpdateOne) SetAgent(a *Agent) *AgentTaskUpdateOne {
	return atuo.SetAgentID(a.ID)
}

// Mutation returns the AgentTaskMutation object of the builder.
func (atuo *AgentTaskUpdateOne) Mutation() *AgentTaskMutation {
	return atuo.mutation
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (atuo *AgentTaskUpdateOne) ClearAgent() *AgentTaskUpdateOne {
	atuo.mutation.ClearAgent()
	return atuo
}

// Where appends a list predicates to the AgentTaskUpdate builder.
func (atuo *AgentTaskUpdateOne) Where(ps ...predicate.AgentTask) *AgentTaskUpdateOne {
	atuo.mutation.Where(ps...)
	return atuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (atuo *AgentTaskUpdateOne) Select(field string, fields ...string) *AgentTaskUpdateOne {
	atuo.fields = append([]string{field}, fields...)
	return atuo
}

// Save executes the query and returns the updated AgentTask entity.
func (atuo *AgentTaskUpdateOne) Save(ctx context.Context) (*AgentTask, error) {
	atuo.defaults()
	return withHooks(ctx, atuo.sqlSave, atuo.mutation, atuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (atuo *AgentTaskUpdateOne) SaveX(ctx context.Context) *AgentTask {
	node, err := atuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (atuo *AgentTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := atuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (atuo *AgentTaskUpdateOne) ExecX(ctx context.Context) {
	if err := atuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (atuo *AgentTaskUpdateOne) defaults() {
	if _, ok := atuo.mutation.UpdatedAt(); !ok {
		v := agenttask.UpdateDefaultUpdatedAt()
		atuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (atuo *AgentTaskUpdateOne) check() error {
	if v, ok := atuo.mutation.Title(); ok {
		if err := agenttask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "AgentTask.title": %w`, err)}
		}
	}
	if v, ok := atuo.mutation.Description(); ok {
		if err := agenttask.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentTask.description": %w`, err)}
		}
	}
	if v, ok := atuo.mutation.Progress(); ok {
		if err := agenttask.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "AgentTask.progress": %w`, err)}
		}
	}
	if atuo.mutation.AgentCleared() && len(atuo.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentTask.agent"`)
	}
	return nil
}

func (atuo *AgentTaskUpdateOne) sqlSave(ctx context.Context) (_node *AgentTask, err error) {
	if err := atuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agenttask.Table, agenttask.Columns, sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID))
	id, ok := atuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := atuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agenttask.FieldID)
		for _, f := range fields {
			if !agenttask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agenttask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := atuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := atuo.mutation.UpdatedAt(); ok {
		_spec.SetField(agenttask.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := atuo.mutation.Title(); ok {
		_spec.SetField(agenttask.FieldTitle, field.TypeString, value)
	}
	if value, ok := atuo.mutation.Description(); ok {
		_spec.SetField(agenttask.FieldDescription, field.TypeString, value)
	}
	if atuo.mutation.DescriptionCleared() {
		_spec.ClearField(agenttask.FieldDescription, field.TypeString)
	}
	if value, ok := atuo.mutation.Status(); ok {
		_spec.SetField(agenttask.FieldStatus, field.TypeString, value)
	}
	if value, ok := atuo.mutation.Priority(); ok {
		_spec.SetField(agenttask.FieldPriority, field.TypeString, value)
	}
	if atuo.mutation.PriorityCleared() {
		_spec.ClearField(agenttask.FieldPriority, field.TypeString)
	}
	if value, ok := atuo.mutation.Progress(); ok {
		_spec.SetField(agenttask.FieldProgress, field.TypeInt, value)
	}
	if value, ok := atuo.mutation.AddedProgress(); ok {
		_spec.AddField(agenttask.FieldProgress, field.TypeInt, value)
	}
	if value, ok := atuo.mutation.DeletedAt(); ok {
		_spec.SetField(agenttask.FieldDeletedAt, field.TypeTime, value)
	}
	if atuo.mutation.DeletedAtCleared() {
		_spec.ClearField(agenttask.FieldDeletedAt, field.TypeTime)
	}
	if atuo.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttask.AgentTable,
			Columns: []string{agenttask.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := atuo.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttask.AgentTable,
			Columns: []string{agenttask.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentTask{config: atuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, atuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agenttask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	atuo.mutation.done = true
	return _node, nil
}
