// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/agentskill"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AgentSkillCreate is the builder for creating a AgentSkill entity.
type AgentSkillCreate struct {
	config
	mutation *AgentSkillMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (asc *AgentSkillCreate) SetCreatedAt(t time.Time) *AgentSkillCreate {
	asc.mutation.SetCreatedAt(t)
	return asc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableCreatedAt(t *time.Time) *AgentSkillCreate {
	if t != nil {
		asc.SetCreatedAt(*t)
	}
	return asc
}

// SetUpdatedAt sets the "updated_at" field.
func (asc *AgentSkillCreate) SetUpdatedAt(t time.Time) *AgentSkillCreate {
	asc.mutation.SetUpdatedAt(t)
	return asc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableUpdatedAt(t *time.Time) *AgentSkillCreate {
	if t != nil {
		asc.SetUpdatedAt(*t)
	}
	return asc
}

// SetOwnerUserID sets the "owner_user_id" field.
func (asc *AgentSkillCreate) SetOwnerUserID(u uuid.UUID) *AgentSkillCreate {
	asc.mutation.SetOwnerUserID(u)
	return asc
}

// SetAgentID sets the "agent_id" field.
func (asc *AgentSkillCreate) SetAgentID(u uuid.UUID) *AgentSkillCreate {
	asc.mutation.SetAgentID(u)
	return asc
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableAgentID(u *uuid.UUID) *AgentSkillCreate {
	if u != nil {
		asc.SetAgentID(*u)
	}
	return asc
}

// SetSourceSkillID sets the "source_skill_id" field.
func (asc *AgentSkillCreate) SetSourceSkillID(u uuid.UUID) *AgentSkillCreate {
	asc.mutation.SetSourceSkillID(u)
	return asc
}

// SetNillableSourceSkillID sets the "source_skill_id" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableSourceSkillID(u *uuid.UUID) *AgentSkillCreate {
	if u != nil {
		asc.SetSourceSkillID(*u)
	}
	return asc
}

// SetName sets the "name" field.
func (asc *AgentSkillCreate) SetName(s string) *AgentSkillCreate {
	asc.mutation.SetName(s)
	return asc
}

// SetDescription sets the "description" field.
func (asc *AgentSkillCreate) SetDescription(s string) *AgentSkillCreate {
	asc.mutation.SetDescription(s)
	return asc
}

// SetInstructions sets the "instructions" field.
func (asc *AgentSkillCreate) SetInstructions(s string) *AgentSkillCreate {
	asc.mutation.SetInstructions(s)
	return asc
}

// SetStatus sets the "status" field.
func (asc *AgentSkillCreate) SetStatus(s string) *AgentSkillCreate {
	asc.mutation.SetStatus(s)
	return asc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableStatus(s *string) *AgentSkillCreate {
	if s != nil {
		asc.SetStatus(*s)
	}
	return asc
}

// SetCategory sets the "category" field.
func (asc *AgentSkillCreate) SetCategory(s string) *AgentSkillCreate {
	asc.mutation.SetCategory(s)
	return asc
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableCategory(s *string) *AgentSkillCreate {
	if s != nil {
		asc.SetCategory(*s)
	}
	return asc
}

// SetVersion sets the "version" field.
func (asc *AgentSkillCreate) SetVersion(s string) *AgentSkillCreate {
	asc.mutation.SetVersion(s)
	return asc
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableVersion(s *string) *AgentSkillCreate {
	if s != nil {
		asc.SetVersion(*s)
	}
	return asc
}

// SetTaughtAt sets the "taught_at" field.
func (asc *AgentSkillCreate) SetTaughtAt(t time.Time) *AgentSkillCreate {
	asc.mutation.SetTaughtAt(t)
	return asc
}

// SetNillableTaughtAt sets the "taught_at" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableTaughtAt(t *time.Time) *AgentSkillCreate {
	if t != nil {
		asc.SetTaughtAt(*t)
	}
	return asc
}

// SetOpenclawGatewayID sets the "openclaw_gateway_id" field.
func (asc *AgentSkillCreate) SetOpenclawGatewayID(s string) *AgentSkillCreate {
	asc.mutation.SetOpenclawGatewayID(s)
	return asc
}

// SetNillableOpenclawGatewayID sets the "openclaw_gateway_id" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableOpenclawGatewayID(s *string) *AgentSkillCreate {
	if s != nil {
		asc.SetOpenclawGatewayID(*s)
	}
	return asc
}

// SetOpenclawSkillID sets the "openclaw_skill_id" field.
func (asc *AgentSkillCreate) SetOpenclawSkillID(s string) *AgentSkillCreate {
	asc.mutation.SetOpenclawSkillID(s)
	return asc
}

// SetNillableOpenclawSkillID sets the "openclaw_skill_id" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableOpenclawSkillID(s *string) *AgentSkillCreate {
	if s != nil {
		asc.SetOpenclawSkillID(*s)
	}
	return asc
}

// SetDeletedAt sets the "deleted_at" field.
func (asc *AgentSkillCreate) SetDeletedAt(t time.Time) *AgentSkillCreate {
	asc.mutation.SetDeletedAt(t)
	return asc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableDeletedAt(t *time.Time) *AgentSkillCreate {
	if t != nil {
		asc.SetDeletedAt(*t)
	}
	return asc
}

// SetID sets the "id" field.
func (asc *AgentSkillCreate) SetID(u uuid.UUID) *AgentSkillCreate {
	asc.mutation.SetID(u)
	return asc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (asc *AgentSkillCreate) SetNillableID(u *uuid.UUID) *AgentSkillCreate {
	if u != nil {
		asc.SetID(*u)
	}
	return asc
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (asc *AgentSkillCreate) SetOwnerID(id uuid.UUID) *AgentSkillCreate {
	asc.mutation.SetOwnerID(id)
	return asc
}

// SetOwner sets the "owner" edge to the User entity.
func (asc *AgentSkillCreate) SetOwner(u *User) *AgentSkillCreate {
	return asc.SetOwnerID(u.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (asc *AgentSkillCreate) SetAgent(a *Agent) *AgentSkillCreate {
	return asc.SetAgentID(a.ID)
}

// Mutation returns the AgentSkillMutation object of the builder.
func (asc *AgentSkillCreate) Mutation() *AgentSkillMutation {
	return asc.mutation
}

// Save creates the AgentSkill in the database.
func (asc *AgentSkillCreate) Save(ctx context.Context) (*AgentSkill, error) {
	asc.defaults()
	return withHooks(ctx, asc.sqlSave, asc.mutation, asc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (asc *AgentSkillCreate) SaveX(ctx context.Context) *AgentSkill {
	v, err := asc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (asc *AgentSkillCreate) Exec(ctx context.Context) error {
	_, err := asc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (asc *AgentSkillCreate) ExecX(ctx context.Context) {
	if err := asc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (asc *AgentSkillCreate) defaults() {
	if _, ok := asc.mutation.CreatedAt(); !ok {
		v := agentskill.DefaultCreatedAt()
		asc.mutation.SetCreatedAt(v)
	}
	if _, ok := asc.mutation.UpdatedAt(); !ok {
		v := agentskill.DefaultUpdatedAt()
		asc.mutation.SetUpdatedAt(v)
	}
	if _, ok := asc.mutation.Status(); !ok {
		v := agentskill.DefaultStatus
		asc.mutation.SetStatus(v)
	}
	if _, ok := asc.mutation.Category(); !ok {
		v := agentskill.DefaultCategory
		asc.mutation.SetCategory(v)
	}
	if _, ok := asc.mutation.ID(); !ok {
		v := agentskill.DefaultID()
		asc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (asc *AgentSkillCreate) check() error {
	if _, ok := asc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentSkill.created_at"`)}
	}
	if _, ok := asc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentSkill.updated_at"`)}
	}
	if _, ok := asc.mutation.OwnerUserID(); !ok {
		return &ValidationError{Name: "owner_user_id", err: errors.New(`ent: missing required field "AgentSkill.owner_user_id"`)}
	}
	if _, ok := asc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "AgentSkill.name"`)}
	}
	if v, ok := asc.mutation.Name(); ok {
		if err := agentskill.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.name": %w`, err)}
		}
	}
	if _, ok := asc.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "AgentSkill.description"`)}
	}
	if v, ok := asc.mutation.Description(); ok {
		if err := agentskill.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.description": %w`, err)}
		}
	}
	if _, ok := asc.mutation.Instructions(); !ok {
		return &ValidationError{Name: "instructions", err: errors.New(`ent: missing required field "AgentSkill.instructions"`)}
	}
	if v, ok := asc.mutation.Instructions(); ok {
		if err := agentskill.InstructionsValidator(v); err != nil {
			return &ValidationError{Name: "instructions", err: fmt.Errorf(`ent: validator failed for field "AgentSkill.instructions": %w`, err)}
		}
	}
	if _, ok := asc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AgentSkill.status"`)}
	}
	if _, ok := asc.mutation.Category(); !ok {
		return &ValidationError{Name: "category", err: errors.New(`ent: missing required field "AgentSkill.category"`)}
	}
	if len(asc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "AgentSkill.owner"`)}
	}
	return nil
}

func (asc *AgentSkillCreate) sqlSave(ctx context.Context) (*AgentSkill, error) {
	if err := asc.check(); err != nil {
		return nil, err
	}
	_node, _spec := asc.createSpec()
	if err := sqlgraph.CreateNode(ctx, asc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	asc.mutation.id = &_node.ID
	asc.mutation.done = true
	return _node, nil
}

func (asc *AgentSkillCreate) createSpec() (*AgentSkill, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentSkill{config: asc.config}
		_spec = sqlgraph.NewCreateSpec(agentskill.Table, sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID))
	)
	if id, ok := asc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := asc.mutation.CreatedAt(); ok {
		_spec.SetField(agentskill.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := asc.mutation.UpdatedAt(); ok {
		_spec.SetField(agentskill.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := asc.mutation.SourceSkillID(); ok {
		_spec.SetField(agentskill.FieldSourceSkillID, field.TypeUUID, value)
		_node.SourceSkillID = &value
	}
	if value, ok := asc.mutation.Name(); ok {
		_spec.SetField(agentskill.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := asc.mutation.Description(); ok {
		_spec.SetField(agentskill.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := asc.mutation.Instructions(); ok {
		_spec.SetField(agentskill.FieldInstructions, field.TypeString, value)
		_node.Instructions = value
	}
	if value, ok := asc.mutation.Status(); ok {
		_spec.SetField(agentskill.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := asc.mutation.Category(); ok {
		_spec.SetField(agentskill.FieldCategory, field.TypeString, value)
		_node.Category = value
	}
	if value, ok := asc.mutation.Version(); ok {
		_spec.SetField(agentskill.FieldVersion, field.TypeString, value)
		_node.Version = &value
	}
	if value, ok := asc.mutation.TaughtAt(); ok {
		_spec.SetField(agentskill.FieldTaughtAt, field.TypeTime, value)
		_node.TaughtAt = &value
	}
	if value, ok := asc.mutation.OpenclawGatewayID(); ok {
		_spec.SetField(agentskill.FieldOpenclawGatewayID, field.TypeString, value)
		_node.OpenclawGatewayID = &value
	}
	if value, ok := asc.mutation.OpenclawSkillID(); ok {
		_spec.SetField(agentskill.FieldOpenclawSkillID, field.TypeString, value)
		_node.OpenclawSkillID = &value
	}
	if value, ok := asc.mutation.DeletedAt(); ok {
		_spec.SetField(agentskill.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := asc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.OwnerTable,
			Columns: []string{agentskill.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerUserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := asc.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentskill.AgentTable,
			Columns: []string{agentskill.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AgentID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentSkillCreateBulk is the builder for creating many AgentSkill entities in bulk.
type AgentSkillCreateBulk struct {
	config
	err      error
	builders []*AgentSkillCreate
}

// Save creates the AgentSkill entities in the database.
func (ascb *AgentSkillCreateBulk) Save(ctx context.Context) ([]*AgentSkill, error) {
	if ascb.err != nil {
		return nil, ascb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ascb.builders))
	nodes := make([]*AgentSkill, len(ascb.builders))
	mutators := make([]Mutator, len(ascb.builders))
	for i := range ascb.builders {
		func(i int, root context.Context) {
			builder := ascb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentSkillMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ascb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ascb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ascb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ascb *AgentSkillCreateBulk) SaveX(ctx context.Context) []*AgentSkill {
	v, err := ascb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ascb *AgentSkillCreateBulk) Exec(ctx context.Context) error {
	_, err := ascb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ascb *AgentSkillCreateBulk) ExecX(ctx context.Context) {
	if err := ascb.Exec(ctx); err != nil {
		panic(err)
	}
}
