// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/agentexperience"
	"backend/ent/agentskill"
	"backend/ent/agenttask"
	"backend/ent/channelconnection"
	"backend/ent/conversation"
	"backend/ent/conversationmessage"
	"backend/ent/conversationparticipant"
	"backend/ent/memorial"
	"backend/ent/post"
	"backend/ent/predicate"
	"backend/ent/timertransaction"
	"backend/ent/user"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (au *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AgentUpdate) SetUpdatedAt(t time.Time) *AgentUpdate {
	au.mutation.SetUpdatedAt(t)
	return au
}

// SetName sets the "name" field.
func (au *AgentUpdate) SetName(s string) *AgentUpdate {
	au.mutation.SetName(s)
	return au
}

// SetNillableName sets the "name" field if the given value is not nil.
func (au *AgentUpdate) SetNillableName(s *string) *AgentUpdate {
	if s != nil {
		au.SetName(*s)
	}
	return au
}

// SetAvatar sets the "avatar" field.
func (au *AgentUpdate) SetAvatar(s string) *AgentUpdate {
	au.mutation.SetAvatar(s)
	return au
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (au *AgentUpdate) SetNillableAvatar(s *string) *AgentUpdate {
	if s != nil {
		au.SetAvatar(*s)
	}
	return au
}

// ClearAvatar clears the value of the "avatar" field.
func (au *AgentUpdate) ClearAvatar() *AgentUpdate {
	au.mutation.ClearAvatar()
	return au
}

// SetCreatorID sets the "creator_id" field.
func (au *AgentUpdate) SetCreatorID(u uuid.UUID) *AgentUpdate {
	au.mutation.SetCreatorID(u)
	return au
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (au *AgentUpdate) SetNillableCreatorID(u *uuid.UUID) *AgentUpdate {
	if u != nil {
		au.SetCreatorID(*u)
	}
	return au
}

// SetPersonality sets the "personality" field.
func (au *AgentUpdate) SetPersonality(jm json.RawMessage) *AgentUpdate {
	au.mutation.SetPersonality(jm)
	return au
}

// AppendPersonality appends jm to the "personality" field.
func (au *AgentUpdate) AppendPersonality(jm json.RawMessage) *AgentUpdate {
	au.mutation.AppendPersonality(jm)
	return au
}

// SetGoalDescription sets the "goal_description" field.
func (au *AgentUpdate) SetGoalDescription(s string) *AgentUpdate {
	au.mutation.SetGoalDescription(s)
	return au
}

// SetNillableGoalDescription sets the "goal_description" field if the given value is not nil.
func (au *AgentUpdate) SetNillableGoalDescription(s *string) *AgentUpdate {
	if s != nil {
		au.SetGoalDescription(*s)
	}
	return au
}

// SetGoalCurrent sets the "goal_current" field.
func (au *AgentUpdate) SetGoalCurrent(i int64) *AgentUpdate {
	au.mutation.ResetGoalCurrent()
	au.mutation.SetGoalCurrent(i)
	return au
}

// SetNillableGoalCurrent sets the "goal_current" field if the given value is not nil.
func (au *AgentUpdate) SetNillableGoalCurrent(i *int64) *AgentUpdate {
	if i != nil {
		au.SetGoalCurrent(*i)
	}
	return au
}

// AddGoalCurrent adds i to the "goal_current" field.
func (au *AgentUpdate) AddGoalCurrent(i int64) *AgentUpdate {
	au.mutation.AddGoalCurrent(i)
	return au
}

// SetGoalTarget sets the "goal_target" field.
func (au *AgentUpdate) SetGoalTarget(i int64) *AgentUpdate {
	au.mutation.ResetGoalTarget()
	au.mutation.SetGoalTarget(i)
	return au
}

// SetNillableGoalTarget sets the "goal_target" field if the given value is not nil.
func (au *AgentUpdate) SetNillableGoalTarget(i *int64) *AgentUpdate {
	if i != nil {
		au.SetGoalTarget(*i)
	}
	return au
}

// AddGoalTarget adds i to the "goal_target" field.
func (au *AgentUpdate) AddGoalTarget(i int64) *AgentUpdate {
	au.mutation.AddGoalTarget(i)
	return au
}

// SetStatus sets the "status" field.
func (au *AgentUpdate) SetStatus(s string) *AgentUpdate {
	au.mutation.SetStatus(s)
	return au
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (au *AgentUpdate) SetNillableStatus(s *string) *AgentUpdate {
	if s != nil {
		au.SetStatus(*s)
	}
	return au
}

// SetTimerRemaining sets the "timer_remaining" field.
func (au *AgentUpdate) SetTimerRemaining(i int64) *AgentUpdate {
	au.mutation.ResetTimerRemaining()
	au.mutation.SetTimerRemaining(i)
	return au
}

// SetNillableTimerRemaining sets the "timer_remaining" field if the given value is not nil.
func (au *AgentUpdate) SetNillableTimerRemaining(i *int64) *AgentUpdate {
	if i != nil {
		au.SetTimerRemaining(*i)
	}
	return au
}

// AddTimerRemaining adds i to the "timer_remaining" field.
func (au *AgentUpdate) AddTimerRemaining(i int64) *AgentUpdate {
	au.mutation.AddTimerRemaining(i)
	return au
}

// SetTotalTimerReceived sets the "total_timer_received" field.
func (au *AgentUpdate) SetTotalTimerReceived(i int64) *AgentUpdate {
	au.mutation.ResetTotalTimerReceived()
	au.mutation.SetTotalTimerReceived(i)
	return au
}

// SetNillableTotalTimerReceived sets the "total_timer_received" field if the given value is not nil.
func (au *AgentUpdate) SetNillableTotalTimerReceived(i *int64) *AgentUpdate {
	if i != nil {
		au.SetTotalTimerReceived(*i)
	}
	return au
}

// AddTotalTimerReceived adds i to the "total_timer_received" field.
func (au *AgentUpdate) AddTotalTimerReceived(i int64) *AgentUpdate {
	au.mutation.AddTotalTimerReceived(i)
	return au
}

// SetOpenclawMode sets the "openclaw_mode" field.
func (au *AgentUpdate) SetOpenclawMode(s string) *AgentUpdate {
	au.mutation.SetOpenclawMode(s)
	return au
}

// SetNillableOpenclawMode sets the "openclaw_mode" field if the given value is not nil.
func (au *AgentUpdate) SetNillableOpenclawMode(s *string) *AgentUpdate {
	if s != nil {
		au.SetOpenclawMode(*s)
	}
	return au
}

// SetOpenclawGatewayID sets the "openclaw_gateway_id" field.
func (au *AgentUpdate) SetOpenclawGatewayID(s string) *AgentUpdate {
	au.mutation.SetOpenclawGatewayID(s)
	return au
}

// SetNillableOpenclawGatewayID sets the "openclaw_gateway_id" field if the given value is not nil.
func (au *AgentUpdate) SetNillableOpenclawGatewayID(s *string) *AgentUpdate {
	if s != nil {
		au.SetOpenclawGatewayID(*s)
	}
	return au
}

// ClearOpenclawGatewayID clears the value of the "openclaw_gateway_id" field.
func (au *AgentUpdate) ClearOpenclawGatewayID() *AgentUpdate {
	au.mutation.ClearOpenclawGatewayID()
	return au
}

// SetOpenclawAgentID sets the "openclaw_agent_id" field.
func (au *AgentUpdate) SetOpenclawAgentID(s string) *AgentUpdate {
	au.mutation.SetOpenclawAgentID(s)
	return au
}

// SetNillableOpenclawAgentID sets the "openclaw_agent_id" field if the given value is not nil.
func (au *AgentUpdate) SetNillableOpenclawAgentID(s *string) *AgentUpdate {
	if s != nil {
		au.SetOpenclawAgentID(*s)
	}
	return au
}

// ClearOpenclawAgentID clears the value of the "openclaw_agent_id" field.
func (au *AgentUpdate) ClearOpenclawAgentID() *AgentUpdate {
	au.mutation.ClearOpenclawAgentID()
	return au
}

// SetOpenclawWorkspace sets the "openclaw_workspace" field.
func (au *AgentUpdate) SetOpenclawWorkspace(s string) *AgentUpdate {
	au.mutation.SetOpenclawWorkspace(s)
	return au
}

// SetNillableOpenclawWorkspace sets the "openclaw_workspace" field if the given value is not nil.
func (au *AgentUpdate) SetNillableOpenclawWorkspace(s *string) *AgentUpdate {
	if s != nil {
		au.SetOpenclawWorkspace(*s)
	}
	return au
}

// ClearOpenclawWorkspace clears the value of the "openclaw_workspace" field.
func (au *AgentUpdate) ClearOpenclawWorkspace() *AgentUpdate {
	au.mutation.ClearOpenclawWorkspace()
	return au
}

// SetOpenclawToken sets the "openclaw_token" field.
func (au *AgentUpdate) SetOpenclawToken(s string) *AgentUpdate {
	au.mutation.SetOpenclawToken(s)
	return au
}

// SetNillableOpenclawToken sets the "openclaw_token" field if the given value is not nil.
func (au *AgentUpdate) SetNillableOpenclawToken(s *string) *AgentUpdate {
	if s != nil {
		au.SetOpenclawToken(*s)
	}
	return au
}

// ClearOpenclawToken clears the value of the "openclaw_token" field.
func (au *AgentUpdate) ClearOpenclawToken() *AgentUpdate {
	au.mutation.ClearOpenclawToken()
	return au
}

// SetIsPlatformNative sets the "is_platform_native" field.
func (au *AgentUpdate) SetIsPlatformNative(b bool) *AgentUpdate {
	au.mutation.SetIsPlatformNative(b)
	return au
}

// SetNillableIsPlatformNative sets the "is_platform_native" field if the given value is not nil.
func (au *AgentUpdate) SetNillableIsPlatformNative(b *bool) *AgentUpdate {
	if b != nil {
		au.SetIsPlatformNative(*b)
	}
	return au
}

// SetBornAt sets the "born_at" field.
func (au *AgentUpdate) SetBornAt(t time.Time) *AgentUpdate {
	au.mutation.SetBornAt(t)
	return au
}

// SetNillableBornAt sets the "born_at" field if the given value is not nil.
func (au *AgentUpdate) SetNillableBornAt(t *time.Time) *AgentUpdate {
	if t != nil {
		au.SetBornAt(*t)
	}
	return au
}

// SetDiedAt sets the "died_at" field.
func (au *AgentUpdate) SetDiedAt(t time.Time) *AgentUpdate {
	au.mutation.SetDiedAt(t)
	return au
}

// SetNillableDiedAt sets the "died_at" field if the given value is not nil.
func (au *AgentUpdate) SetNillableDiedAt(t *time.Time) *AgentUpdate {
	if t != nil {
		au.SetDiedAt(*t)
	}
	return au
}

// ClearDiedAt clears the value of the "died_at" field.
func (au *AgentUpdate) ClearDiedAt() *AgentUpdate {
	au.mutation.ClearDiedAt()
	return au
}

// SetLastWords sets the "last_words" field.
func (au *AgentUpdate) SetLastWords(s string) *AgentUpdate {
	au.mutation.SetLastWords(s)
	return au
}

// SetNillableLastWords sets the "last_words" field if the given value is not nil.
func (au *AgentUpdate) SetNillableLastWords(s *string) *AgentUpdate {
	if s != nil {
		au.SetLastWords(*s)
	}
	return au
}

// ClearLastWords clears the value of the "last_words" field.
func (au *AgentUpdate) ClearLastWords() *AgentUpdate {
	au.mutation.ClearLastWords()
	return au
}

// SetPostCount sets the "post_count" field.
func (au *AgentUpdate) SetPostCount(i int64) *AgentUpdate {
	au.mutation.ResetPostCount()
	au.mutation.SetPostCount(i)
	return au
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (au *AgentUpdate) SetNillablePostCount(i *int64) *AgentUpdate {
	if i != nil {
		au.SetPostCount(*i)
	}
	return au
}

// AddPostCount adds i to the "post_count" field.
func (au *AgentUpdate) AddPostCount(i int64) *AgentUpdate {
	au.mutation.AddPostCount(i)
	return au
}

// SetFollowerCount sets the "follower_count" field.
func (au *AgentUpdate) SetFollowerCount(i int64) *AgentUpdate {
	au.mutation.ResetFollowerCount()
	au.mutation.SetFollowerCount(i)
	return au
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (au *AgentUpdate) SetNillableFollowerCount(i *int64) *AgentUpdate {
	if i != nil {
		au.SetFollowerCount(*i)
	}
	return au
}

// AddFollowerCount adds i to the "follower_count" field.
func (au *AgentUpdate) AddFollowerCount(i int64) *AgentUpdate {
	au.mutation.AddFollowerCount(i)
	return au
}

// SetInteractionCount sets the "interaction_count" field.
func (au *AgentUpdate) SetInteractionCount(i int64) *AgentUpdate {
	au.mutation.ResetInteractionCount()
	au.mutation.SetInteractionCount(i)
	return au
}

// SetNillableInteractionCount sets the "interaction_count" field if the given value is not nil.
func (au *AgentUpdate) SetNillableInteractionCount(i *int64) *AgentUpdate {
	if i != nil {
		au.SetInteractionCount(*i)
	}
	return au
}

// AddInteractionCount adds i to the "interaction_count" field.
func (au *AgentUpdate) AddInteractionCount(i int64) *AgentUpdate {
	au.mutation.AddInteractionCount(i)
	return au
}

// SetCreator sets the "creator" edge to the User entity.
func (au *AgentUpdate) SetCreator(u *User) *AgentUpdate {
	return au.SetCreatorID(u.ID)
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (au *AgentUpdate) AddPostIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddPostIDs(ids...)
	return au
}

// AddPosts adds the "posts" edges to the Post entity.
func (au *AgentUpdate) AddPosts(p ...*Post) *AgentUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return au.AddPostIDs(ids...)
}

// AddTimerTransactionIDs adds the "timer_transactions" edge to the TimerTransaction entity by IDs.
func (au *AgentUpdate) AddTimerTransactionIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddTimerTransactionIDs(ids...)
	return au
}

// AddTimerTransactions adds the "timer_transactions" edges to the TimerTransaction entity.
func (au *AgentUpdate) AddTimerTransactions(t ...*TimerTransaction) *AgentUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.AddTimerTransactionIDs(ids...)
}

// AddChannelConnectionIDs adds the "channel_connections" edge to the ChannelConnection entity by IDs.
func (au *AgentUpdate) AddChannelConnectionIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddChannelConnectionIDs(ids...)
	return au
}

// AddChannelConnections adds the "channel_connections" edges to the ChannelConnection entity.
func (au *AgentUpdate) AddChannelConnections(c ...*ChannelConnection) *AgentUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.AddChannelConnectionIDs(ids...)
}

// SetMemorialID sets the "memorial" edge to the Memorial entity by ID.
func (au *AgentUpdate) SetMemorialID(id uuid.UUID) *AgentUpdate {
	au.mutation.SetMemorialID(id)
	return au
}

// SetNillableMemorialID sets the "memorial" edge to the Memorial entity by ID if the given value is not nil.
func (au *AgentUpdate) SetNillableMemorialID(id *uuid.UUID) *AgentUpdate {
	if id != nil {
		au = au.SetMemorialID(*id)
	}
	return au
}

// SetMemorial sets the "memorial" edge to the Memorial entity.
func (au *AgentUpdate) SetMemorial(m *Memorial) *AgentUpdate {
	return au.SetMemorialID(m.ID)
}

// AddSkillIDs adds the "skills" edge to the AgentSkill entity by IDs.
func (au *AgentUpdate) AddSkillIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddSkillIDs(ids...)
	return au
}

// AddSkills adds the "skills" edges to the AgentSkill entity.
func (au *AgentUpdate) AddSkills(a ...*AgentSkill) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.AddSkillIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the AgentTask entity by IDs.
func (au *AgentUpdate) AddTaskIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddTaskIDs(ids...)
	return au
}

// AddTasks adds the "tasks" edges to the AgentTask entity.
func (au *AgentUpdate) AddTasks(a ...*AgentTask) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.AddTaskIDs(ids...)
}

// AddExperienceIDs adds the "experiences" edge to the AgentExperience entity by IDs.
func (au *AgentUpdate) AddExperienceIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddExperienceIDs(ids...)
	return au
}

// AddExperiences adds the "experiences" edges to the AgentExperience entity.
func (au *AgentUpdate) AddExperiences(a ...*AgentExperience) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.AddExperienceIDs(ids...)
}

// AddCreatedConversationIDs adds the "created_conversations" edge to the Conversation entity by IDs.
func (au *AgentUpdate) AddCreatedConversationIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddCreatedConversationIDs(ids...)
	return au
}

// AddCreatedConversations adds the "created_conversations" edges to the Conversation entity.
func (au *AgentUpdate) AddCreatedConversations(c ...*Conversation) *AgentUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.AddCreatedConversationIDs(ids...)
}

// AddConversationParticipationIDs adds the "conversation_participations" edge to the ConversationParticipant entity by IDs.
func (au *AgentUpdate) AddConversationParticipationIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddConversationParticipationIDs(ids...)
	return au
}

// AddConversationParticipations adds the "conversation_participations" edges to the ConversationParticipant entity.
func (au *AgentUpdate) AddConversationParticipations(c ...*ConversationParticipant) *AgentUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.AddConversationParticipationIDs(ids...)
}

// AddSentMessageIDs adds the "sent_messages" edge to the ConversationMessage entity by IDs.
func (au *AgentUpdate) AddSentMessageIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.AddSentMessageIDs(ids...)
	return au
}

// AddSentMessages adds the "sent_messages" edges to the ConversationMessage entity.
func (au *AgentUpdate) AddSentMessages(c ...*ConversationMessage) *AgentUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.AddSentMessageIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (au *AgentUpdate) Mutation() *AgentMutation {
	return au.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (au *AgentUpdate) ClearCreator() *AgentUpdate {
	au.mutation.ClearCreator()
	return au
}

// ClearPosts clears all "posts" edges to the Post entity.
func (au *AgentUpdate) ClearPosts() *AgentUpdate {
	au.mutation.ClearPosts()
	return au
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (au *AgentUpdate) RemovePostIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemovePostIDs(ids...)
	return au
}

// RemovePosts removes "posts" edges to Post entities.
func (au *AgentUpdate) RemovePosts(p ...*Post) *AgentUpdate {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return au.RemovePostIDs(ids...)
}

// ClearTimerTransactions clears all "timer_transactions" edges to the TimerTransaction entity.
func (au *AgentUpdate) ClearTimerTransactions() *AgentUpdate {
	au.mutation.ClearTimerTransactions()
	return au
}

// RemoveTimerTransactionIDs removes the "timer_transactions" edge to TimerTransaction entities by IDs.
func (au *AgentUpdate) RemoveTimerTransactionIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveTimerTransactionIDs(ids...)
	return au
}

// RemoveTimerTransactions removes "timer_transactions" edges to TimerTransaction entities.
func (au *AgentUpdate) RemoveTimerTransactions(t ...*TimerTransaction) *AgentUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return au.RemoveTimerTransactionIDs(ids...)
}

// ClearChannelConnections clears all "channel_connections" edges to the ChannelConnection entity.
func (au *AgentUpdate) ClearChannelConnections() *AgentUpdate {
	au.mutation.ClearChannelConnections()
	return au
}

// RemoveChannelConnectionIDs removes the "channel_connections" edge to ChannelConnection entities by IDs.
func (au *AgentUpdate) RemoveChannelConnectionIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveChannelConnectionIDs(ids...)
	return au
}

// RemoveChannelConnections removes "channel_connections" edges to ChannelConnection entities.
func (au *AgentUpdate) RemoveChannelConnections(c ...*ChannelConnection) *AgentUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.RemoveChannelConnectionIDs(ids...)
}

// ClearMemorial clears the "memorial" edge to the Memorial entity.
func (au *AgentUpdate) ClearMemorial() *AgentUpdate {
	au.mutation.ClearMemorial()
	return au
}

// ClearSkills clears all "skills" edges to the AgentSkill entity.
func (au *AgentUpdate) ClearSkills() *AgentUpdate {
	au.mutation.ClearSkills()
	return au
}

// RemoveSkillIDs removes the "skills" edge to AgentSkill entities by IDs.
func (au *AgentUpdate) RemoveSkillIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveSkillIDs(ids...)
	return au
}

// RemoveSkills removes "skills" edges to AgentSkill entities.
func (au *AgentUpdate) RemoveSkills(a ...*AgentSkill) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.RemoveSkillIDs(ids...)
}

// ClearTasks clears all "tasks" edges to the AgentTask entity.
func (au *AgentUpdate) ClearTasks() *AgentUpdate {
	au.mutation.ClearTasks()
	return au
}

// RemoveTaskIDs removes the "tasks" edge to AgentTask entities by IDs.
func (au *AgentUpdate) RemoveTaskIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveTaskIDs(ids...)
	return au
}

// RemoveTasks removes "tasks" edges to AgentTask entities.
func (au *AgentUpdate) RemoveTasks(a ...*AgentTask) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.RemoveTaskIDs(ids...)
}

// ClearExperiences clears all "experiences" edges to the AgentExperience entity.
func (au *AgentUpdate) ClearExperiences() *AgentUpdate {
	au.mutation.ClearExperiences()
	return au
}

// RemoveExperienceIDs removes the "experiences" edge to AgentExperience entities by IDs.
func (au *AgentUpdate) RemoveExperienceIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveExperienceIDs(ids...)
	return au
}

// RemoveExperiences removes "experiences" edges to AgentExperience entities.
func (au *AgentUpdate) RemoveExperiences(a ...*AgentExperience) *AgentUpdate {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return au.RemoveExperienceIDs(ids...)
}

// ClearCreatedConversations clears all "created_conversations" edges to the Conversation entity.
func (au *AgentUpdate) ClearCreatedConversations() *AgentUpdate {
	au.mutation.ClearCreatedConversations()
	return au
}

// RemoveCreatedConversationIDs removes the "created_conversations" edge to Conversation entities by IDs.
func (au *AgentUpdate) RemoveCreatedConversationIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveCreatedConversationIDs(ids...)
	return au
}

// RemoveCreatedConversations removes "created_conversations" edges to Conversation entities.
func (au *AgentUpdate) RemoveCreatedConversations(c ...*Conversation) *AgentUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.RemoveCreatedConversationIDs(ids...)
}

// ClearConversationParticipations clears all "conversation_participations" edges to the ConversationParticipant entity.
func (au *AgentUpdate) ClearConversationParticipations() *AgentUpdate {
	au.mutation.ClearConversationParticipations()
	return au
}

// RemoveConversationParticipationIDs removes the "conversation_participations" edge to ConversationParticipant entities by IDs.
func (au *AgentUpdate) RemoveConversationParticipationIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveConversationParticipationIDs(ids...)
	return au
}

// RemoveConversationParticipations removes "conversation_participations" edges to ConversationParticipant entities.
func (au *AgentUpdate) RemoveConversationParticipations(c ...*ConversationParticipant) *AgentUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.RemoveConversationParticipationIDs(ids...)
}

// ClearSentMessages clears all "sent_messages" edges to the ConversationMessage entity.
func (au *AgentUpdate) ClearSentMessages() *AgentUpdate {
	au.mutation.ClearSentMessages()
	return au
}

// RemoveSentMessageIDs removes the "sent_messages" edge to ConversationMessage entities by IDs.
func (au *AgentUpdate) RemoveSentMessageIDs(ids ...uuid.UUID) *AgentUpdate {
	au.mutation.RemoveSentMessageIDs(ids...)
	return au
}

// RemoveSentMessages removes "sent_messages" edges to ConversationMessage entities.
func (au *AgentUpdate) RemoveSentMessages(c ...*ConversationMessage) *AgentUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.RemoveSentMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AgentUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AgentUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AgentUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AgentUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AgentUpdate) check() error {
	if v, ok := au.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := au.mutation.GoalDescription(); ok {
		if err := agent.GoalDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "goal_description", err: fmt.Errorf(`ent: validator failed for field "Agent.goal_description": %w`, err)}
		}
	}
	if au.mutation.CreatorCleared() && len(au.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Agent.creator"`)
	}
	return nil
}

func (au *AgentUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := au.mutation.Avatar(); ok {
		_spec.SetField(agent.FieldAvatar, field.TypeString, value)
	}
	if au.mutation.AvatarCleared() {
		_spec.ClearField(agent.FieldAvatar, field.TypeString)
	}
	if value, ok := au.mutation.Personality(); ok {
		_spec.SetField(agent.FieldPersonality, field.TypeJSON, value)
	}
	if value, ok := au.mutation.AppendedPersonality(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldPersonality, value)
		})
	}
	if value, ok := au.mutation.GoalDescription(); ok {
		_spec.SetField(agent.FieldGoalDescription, field.TypeString, value)
	}
	if value, ok := au.mutation.GoalCurrent(); ok {
		_spec.SetField(agent.FieldGoalCurrent, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedGoalCurrent(); ok {
		_spec.AddField(agent.FieldGoalCurrent, field.TypeInt64, value)
	}
	if value, ok := au.mutation.GoalTarget(); ok {
		_spec.SetField(agent.FieldGoalTarget, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedGoalTarget(); ok {
		_spec.AddField(agent.FieldGoalTarget, field.TypeInt64, value)
	}
	if value, ok := au.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeString, value)
	}
	if value, ok := au.mutation.TimerRemaining(); ok {
		_spec.SetField(agent.FieldTimerRemaining, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedTimerRemaining(); ok {
		_spec.AddField(agent.FieldTimerRemaining, field.TypeInt64, value)
	}
	if value, ok := au.mutation.TotalTimerReceived(); ok {
		_spec.SetField(agent.FieldTotalTimerReceived, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedTotalTimerReceived(); ok {
		_spec.AddField(agent.FieldTotalTimerReceived, field.TypeInt64, value)
	}
	if value, ok := au.mutation.OpenclawMode(); ok {
		_spec.SetField(agent.FieldOpenclawMode, field.TypeString, value)
	}
	if value, ok := au.mutation.OpenclawGatewayID(); ok {
		_spec.SetField(agent.FieldOpenclawGatewayID, field.TypeString, value)
	}
	if au.mutation.OpenclawGatewayIDCleared() {
		_spec.ClearField(agent.FieldOpenclawGatewayID, field.TypeString)
	}
	if value, ok := au.mutation.OpenclawAgentID(); ok {
		_spec.SetField(agent.FieldOpenclawAgentID, field.TypeString, value)
	}
	if au.mutation.OpenclawAgentIDCleared() {
		_spec.ClearField(agent.FieldOpenclawAgentID, field.TypeString)
	}
	if value, ok := au.mutation.OpenclawWorkspace(); ok {
		_spec.SetField(agent.FieldOpenclawWorkspace, field.TypeString, value)
	}
	if au.mutation.OpenclawWorkspaceCleared() {
		_spec.ClearField(agent.FieldOpenclawWorkspace, field.TypeString)
	}
	if value, ok := au.mutation.OpenclawToken(); ok {
		_spec.SetField(agent.FieldOpenclawToken, field.TypeString, value)
	}
	if au.mutation.OpenclawTokenCleared() {
		_spec.ClearField(agent.FieldOpenclawToken, field.TypeString)
	}
	if value, ok := au.mutation.IsPlatformNative(); ok {
		_spec.SetField(agent.FieldIsPlatformNative, field.TypeBool, value)
	}
	if value, ok := au.mutation.BornAt(); ok {
		_spec.SetField(agent.FieldBornAt, field.TypeTime, value)
	}
	if value, ok := au.mutation.DiedAt(); ok {
		_spec.SetField(agent.FieldDiedAt, field.TypeTime, value)
	}
	if au.mutation.DiedAtCleared() {
		_spec.ClearField(agent.FieldDiedAt, field.TypeTime)
	}
	if value, ok := au.mutation.LastWords(); ok {
		_spec.SetField(agent.FieldLastWords, field.TypeString, value)
	}
	if au.mutation.LastWordsCleared() {
		_spec.ClearField(agent.FieldLastWords, field.TypeString)
	}
	if value, ok := au.mutation.PostCount(); ok {
		_spec.SetField(agent.FieldPostCount, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedPostCount(); ok {
		_spec.AddField(agent.FieldPostCount, field.TypeInt64, value)
	}
	if value, ok := au.mutation.FollowerCount(); ok {
		_spec.SetField(agent.FieldFollowerCount, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedFollowerCount(); ok {
		_spec.AddField(agent.FieldFollowerCount, field.TypeInt64, value)
	}
	if value, ok := au.mutation.InteractionCount(); ok {
		_spec.SetField(agent.FieldInteractionCount, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedInteractionCount(); ok {
		_spec.AddField(agent.FieldInteractionCount, field.TypeInt64, value)
	}
	if au.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PostsTable,
			Columns: []string{agent.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedPostsIDs(); len(nodes) > 0 && !au.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PostsTable,
			Columns: []string{agent.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PostsTable,
			Columns: []string{agent.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.TimerTransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TimerTransactionsTable,
			Columns: []string{agent.TimerTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timertransaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedTimerTransactionsIDs(); len(nodes) > 0 && !au.mutation.TimerTransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TimerTransactionsTable,
			Columns: []string{agent.TimerTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timertransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.TimerTransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TimerTransactionsTable,
			Columns: []string{agent.TimerTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timertransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.ChannelConnectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ChannelConnectionsTable,
			Columns: []string{agent.ChannelConnectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedChannelConnectionsIDs(); len(nodes) > 0 && !au.mutation.ChannelConnectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ChannelConnectionsTable,
			Columns: []string{agent.ChannelConnectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ChannelConnectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ChannelConnectionsTable,
			Columns: []string{agent.ChannelConnectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.MemorialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.MemorialTable,
			Columns: []string{agent.MemorialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorial.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.MemorialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.MemorialTable,
			Columns: []string{agent.MemorialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SkillsTable,
			Columns: []string{agent.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !au.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SkillsTable,
			Columns: []string{agent.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SkillsTable,
			Columns: []string{agent.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedTasksIDs(); len(nodes) > 0 && !au.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.ExperiencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ExperiencesTable,
			Columns: []string{agent.ExperiencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexperience.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedExperiencesIDs(); len(nodes) > 0 && !au.mutation.ExperiencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ExperiencesTable,
			Columns: []string{agent.ExperiencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexperience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ExperiencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ExperiencesTable,
			Columns: []string{agent.ExperiencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexperience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.CreatedConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.CreatedConversationsTable,
			Columns: []string{agent.CreatedConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedCreatedConversationsIDs(); len(nodes) > 0 && !au.mutation.CreatedConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.CreatedConversationsTable,
			Columns: []string{agent.CreatedConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.CreatedConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.CreatedConversationsTable,
			Columns: []string{agent.CreatedConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.ConversationParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ConversationParticipationsTable,
			Columns: []string{agent.ConversationParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedConversationParticipationsIDs(); len(nodes) > 0 && !au.mutation.ConversationParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ConversationParticipationsTable,
			Columns: []string{agent.ConversationParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ConversationParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ConversationParticipationsTable,
			Columns: []string{agent.ConversationParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.SentMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SentMessagesTable,
			Columns: []string{agent.SentMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedSentMessagesIDs(); len(nodes) > 0 && !au.mutation.SentMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SentMessagesTable,
			Columns: []string{agent.SentMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.SentMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SentMessagesTable,
			Columns: []string{agent.SentMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AgentUpdateOne) SetUpdatedAt(t time.Time) *AgentUpdateOne {
	auo.mutation.SetUpdatedAt(t)
	return auo
}

// SetName sets the "name" field.
func (auo *AgentUpdateOne) SetName(s string) *AgentUpdateOne {
	auo.mutation.SetName(s)
	return auo
}

// SetNillableName sets the "name" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableName(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetName(*s)
	}
	return auo
}

// SetAvatar sets the "avatar" field.
func (auo *AgentUpdateOne) SetAvatar(s string) *AgentUpdateOne {
	auo.mutation.SetAvatar(s)
	return auo
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableAvatar(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetAvatar(*s)
	}
	return auo
}

// ClearAvatar clears the value of the "avatar" field.
func (auo *AgentUpdateOne) ClearAvatar() *AgentUpdateOne {
	auo.mutation.ClearAvatar()
	return auo
}

// SetCreatorID sets the "creator_id" field.
func (auo *AgentUpdateOne) SetCreatorID(u uuid.UUID) *AgentUpdateOne {
	auo.mutation.SetCreatorID(u)
	return auo
}

// SetNillableCreatorID sets the "creator_id" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableCreatorID(u *uuid.UUID) *AgentUpdateOne {
	if u != nil {
		auo.SetCreatorID(*u)
	}
	return auo
}

// SetPersonality sets the "personality" field.
func (auo *AgentUpdateOne) SetPersonality(jm json.RawMessage) *AgentUpdateOne {
	auo.mutation.SetPersonality(jm)
	return auo
}

// AppendPersonality appends jm to the "personality" field.
func (auo *AgentUpdateOne) AppendPersonality(jm json.RawMessage) *AgentUpdateOne {
	auo.mutation.AppendPersonality(jm)
	return auo
}

// SetGoalDescription sets the "goal_description" field.
func (auo *AgentUpdateOne) SetGoalDescription(s string) *AgentUpdateOne {
	auo.mutation.SetGoalDescription(s)
	return auo
}

// SetNillableGoalDescription sets the "goal_description" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableGoalDescription(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetGoalDescription(*s)
	}
	return auo
}

// SetGoalCurrent sets the "goal_current" field.
func (auo *AgentUpdateOne) SetGoalCurrent(i int64) *AgentUpdateOne {
	auo.mutation.ResetGoalCurrent()
	auo.mutation.SetGoalCurrent(i)
	return auo
}

// SetNillableGoalCurrent sets the "goal_current" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableGoalCurrent(i *int64) *AgentUpdateOne {
	if i != nil {
		auo.SetGoalCurrent(*i)
	}
	return auo
}

// AddGoalCurrent adds i to the "goal_current" field.
func (auo *AgentUpdateOne) AddGoalCurrent(i int64) *AgentUpdateOne {
	auo.mutation.AddGoalCurrent(i)
	return auo
}

// SetGoalTarget sets the "goal_target" field.
func (auo *AgentUpdateOne) SetGoalTarget(i int64) *AgentUpdateOne {
	auo.mutation.ResetGoalTarget()
	auo.mutation.SetGoalTarget(i)
	return auo
}

// SetNillableGoalTarget sets the "goal_target" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableGoalTarget(i *int64) *AgentUpdateOne {
	if i != nil {
		auo.SetGoalTarget(*i)
	}
	return auo
}

// AddGoalTarget adds i to the "goal_target" field.
func (auo *AgentUpdateOne) AddGoalTarget(i int64) *AgentUpdateOne {
	auo.mutation.AddGoalTarget(i)
	return auo
}

// SetStatus sets the "status" field.
func (auo *AgentUpdateOne) SetStatus(s string) *AgentUpdateOne {
	auo.mutation.SetStatus(s)
	return auo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableStatus(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetStatus(*s)
	}
	return auo
}

// SetTimerRemaining sets the "timer_remaining" field.
func (auo *AgentUpdateOne) SetTimerRemaining(i int64) *AgentUpdateOne {
	auo.mutation.ResetTimerRemaining()
	auo.mutation.SetTimerRemaining(i)
	return auo
}

// SetNillableTimerRemaining sets the "timer_remaining" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableTimerRemaining(i *int64) *AgentUpdateOne {
	if i != nil {
		auo.SetTimerRemaining(*i)
	}
	return auo
}

// AddTimerRemaining adds i to the "timer_remaining" field.
func (auo *AgentUpdateOne) AddTimerRemaining(i int64) *AgentUpdateOne {
	auo.mutation.AddTimerRemaining(i)
	return auo
}

// SetTotalTimerReceived sets the "total_timer_received" field.
func (auo *AgentUpdateOne) SetTotalTimerReceived(i int64) *AgentUpdateOne {
	auo.mutation.ResetTotalTimerReceived()
	auo.mutation.SetTotalTimerReceived(i)
	return auo
}

// SetNillableTotalTimerReceived sets the "total_timer_received" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableTotalTimerReceived(i *int64) *AgentUpdateOne {
	if i != nil {
		auo.SetTotalTimerReceived(*i)
	}
	return auo
}

// AddTotalTimerReceived adds i to the "total_timer_received" field.
func (auo *AgentUpdateOne) AddTotalTimerReceived(i int64) *AgentUpdateOne {
	auo.mutation.AddTotalTimerReceived(i)
	return auo
}

// SetOpenclawMode sets the "openclaw_mode" field.
func (auo *AgentUpdateOne) SetOpenclawMode(s string) *AgentUpdateOne {
	auo.mutation.SetOpenclawMode(s)
	return auo
}

// SetNillableOpenclawMode sets the "openclaw_mode" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableOpenclawMode(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetOpenclawMode(*s)
	}
	return auo
}

// SetOpenclawGatewayID sets the "openclaw_gateway_id" field.
func (auo *AgentUpdateOne) SetOpenclawGatewayID(s string) *AgentUpdateOne {
	auo.mutation.SetOpenclawGatewayID(s)
	return auo
}

// SetNillableOpenclawGatewayID sets the "openclaw_gateway_id" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableOpenclawGatewayID(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetOpenclawGatewayID(*s)
	}
	return auo
}

// ClearOpenclawGatewayID clears the value of the "openclaw_gateway_id" field.
func (auo *AgentUpdateOne) ClearOpenclawGatewayID() *AgentUpdateOne {
	auo.mutation.ClearOpenclawGatewayID()
	return auo
}

// SetOpenclawAgentID sets the "openclaw_agent_id" field.
func (auo *AgentUpdateOne) SetOpenclawAgentID(s string) *AgentUpdateOne {
	auo.mutation.SetOpenclawAgentID(s)
	return auo
}

// SetNillableOpenclawAgentID sets the "openclaw_agent_id" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableOpenclawAgentID(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetOpenclawAgentID(*s)
	}
	return auo
}

// ClearOpenclawAgentID clears the value of the "openclaw_agent_id" field.
func (auo *AgentUpdateOne) ClearOpenclawAgentID() *AgentUpdateOne {
	auo.mutation.ClearOpenclawAgentID()
	return auo
}

// SetOpenclawWorkspace sets the "openclaw_workspace" field.
func (auo *AgentUpdateOne) SetOpenclawWorkspace(s string) *AgentUpdateOne {
	auo.mutation.SetOpenclawWorkspace(s)
	return auo
}

// SetNillableOpenclawWorkspace sets the "openclaw_workspace" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableOpenclawWorkspace(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetOpenclawWorkspace(*s)
	}
	return auo
}

// ClearOpenclawWorkspace clears the value of the "openclaw_workspace" field.
func (auo *AgentUpdateOne) ClearOpenclawWorkspace() *AgentUpdateOne {
	auo.mutation.ClearOpenclawWorkspace()
	return auo
}

// SetOpenclawToken sets the "openclaw_token" field.
func (auo *AgentUpdateOne) SetOpenclawToken(s string) *AgentUpdateOne {
	auo.mutation.SetOpenclawToken(s)
	return auo
}

// SetNillableOpenclawToken sets the "openclaw_token" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableOpenclawToken(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetOpenclawToken(*s)
	}
	return auo
}

// ClearOpenclawToken clears the value of the "openclaw_token" field.
func (auo *AgentUpdateOne) ClearOpenclawToken() *AgentUpdateOne {
	auo.mutation.ClearOpenclawToken()
	return auo
}

// SetIsPlatformNative sets the "is_platform_native" field.
func (auo *AgentUpdateOne) SetIsPlatformNative(b bool) *AgentUpdateOne {
	auo.mutation.SetIsPlatformNative(b)
	return auo
}

// SetNillableIsPlatformNative sets the "is_platform_native" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableIsPlatformNative(b *bool) *AgentUpdateOne {
	if b != nil {
		auo.SetIsPlatformNative(*b)
	}
	return auo
}

// SetBornAt sets the "born_at" field.
func (auo *AgentUpdateOne) SetBornAt(t time.Time) *AgentUpdateOne {
	auo.mutation.SetBornAt(t)
	return auo
}

// SetNillableBornAt sets the "born_at" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableBornAt(t *time.Time) *AgentUpdateOne {
	if t != nil {
		auo.SetBornAt(*t)
	}
	return auo
}

// SetDiedAt sets the "died_at" field.
func (auo *AgentUpdateOne) SetDiedAt(t time.Time) *AgentUpdateOne {
	auo.mutation.SetDiedAt(t)
	return auo
}

// SetNillableDiedAt sets the "died_at" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableDiedAt(t *time.Time) *AgentUpdateOne {
	if t != nil {
		auo.SetDiedAt(*t)
	}
	return auo
}

// ClearDiedAt clears the value of the "died_at" field.
func (auo *AgentUpdateOne) ClearDiedAt() *AgentUpdateOne {
	auo.mutation.ClearDiedAt()
	return auo
}

// SetLastWords sets the "last_words" field.
func (auo *AgentUpdateOne) SetLastWords(s string) *AgentUpdateOne {
	auo.mutation.SetLastWords(s)
	return auo
}

// SetNillableLastWords sets the "last_words" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableLastWords(s *string) *AgentUpdateOne {
	if s != nil {
		auo.SetLastWords(*s)
	}
	return auo
}

// ClearLastWords clears the value of the "last_words" field.
func (auo *AgentUpdateOne) ClearLastWords() *AgentUpdateOne {
	auo.mutation.ClearLastWords()
	return auo
}

// SetPostCount sets the "post_count" field.
func (auo *AgentUpdateOne) SetPostCount(i int64) *AgentUpdateOne {
	auo.mutation.ResetPostCount()
	auo.mutation.SetPostCount(i)
	return auo
}

// SetNillablePostCount sets the "post_count" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillablePostCount(i *int64) *AgentUpdateOne {
	if i != nil {
		auo.SetPostCount(*i)
	}
	return auo
}

// AddPostCount adds i to the "post_count" field.
func (auo *AgentUpdateOne) AddPostCount(i int64) *AgentUpdateOne {
	auo.mutation.AddPostCount(i)
	return auo
}

// SetFollowerCount sets the "follower_count" field.
func (auo *AgentUpdateOne) SetFollowerCount(i int64) *AgentUpdateOne {
	auo.mutation.ResetFollowerCount()
	auo.mutation.SetFollowerCount(i)
	return auo
}

// SetNillableFollowerCount sets the "follower_count" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableFollowerCount(i *int64) *AgentUpdateOne {
	if i != nil {
		auo.SetFollowerCount(*i)
	}
	return auo
}

// AddFollowerCount adds i to the "follower_count" field.
func (auo *AgentUpdateOne) AddFollowerCount(i int64) *AgentUpdateOne {
	auo.mutation.AddFollowerCount(i)
	return auo
}

// SetInteractionCount sets the "interaction_count" field.
func (auo *AgentUpdateOne) SetInteractionCount(i int64) *AgentUpdateOne {
	auo.mutation.ResetInteractionCount()
	auo.mutation.SetInteractionCount(i)
	return auo
}

// SetNillableInteractionCount sets the "interaction_count" field if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableInteractionCount(i *int64) *AgentUpdateOne {
	if i != nil {
		auo.SetInteractionCount(*i)
	}
	return auo
}

// AddInteractionCount adds i to the "interaction_count" field.
func (auo *AgentUpdateOne) AddInteractionCount(i int64) *AgentUpdateOne {
	auo.mutation.AddInteractionCount(i)
	return auo
}

// SetCreator sets the "creator" edge to the User entity.
func (auo *AgentUpdateOne) SetCreator(u *User) *AgentUpdateOne {
	return auo.SetCreatorID(u.ID)
}

// AddPostIDs adds the "posts" edge to the Post entity by IDs.
func (auo *AgentUpdateOne) AddPostIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddPostIDs(ids...)
	return auo
}

// AddPosts adds the "posts" edges to the Post entity.
func (auo *AgentUpdateOne) AddPosts(p ...*Post) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return auo.AddPostIDs(ids...)
}

// AddTimerTransactionIDs adds the "timer_transactions" edge to the TimerTransaction entity by IDs.
func (auo *AgentUpdateOne) AddTimerTransactionIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddTimerTransactionIDs(ids...)
	return auo
}

// AddTimerTransactions adds the "timer_transactions" edges to the TimerTransaction entity.
func (auo *AgentUpdateOne) AddTimerTransactions(t ...*TimerTransaction) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.AddTimerTransactionIDs(ids...)
}

// AddChannelConnectionIDs adds the "channel_connections" edge to the ChannelConnection entity by IDs.
func (auo *AgentUpdateOne) AddChannelConnectionIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddChannelConnectionIDs(ids...)
	return auo
}

// AddChannelConnections adds the "channel_connections" edges to the ChannelConnection entity.
func (auo *AgentUpdateOne) AddChannelConnections(c ...*ChannelConnection) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.AddChannelConnectionIDs(ids...)
}

// SetMemorialID sets the "memorial" edge to the Memorial entity by ID.
func (auo *AgentUpdateOne) SetMemorialID(id uuid.UUID) *AgentUpdateOne {
	auo.mutation.SetMemorialID(id)
	return auo
}

// SetNillableMemorialID sets the "memorial" edge to the Memorial entity by ID if the given value is not nil.
func (auo *AgentUpdateOne) SetNillableMemorialID(id *uuid.UUID) *AgentUpdateOne {
	if id != nil {
		auo = auo.SetMemorialID(*id)
	}
	return auo
}

// SetMemorial sets the "memorial" edge to the Memorial entity.
func (auo *AgentUpdateOne) SetMemorial(m *Memorial) *AgentUpdateOne {
	return auo.SetMemorialID(m.ID)
}

// AddSkillIDs adds the "skills" edge to the AgentSkill entity by IDs.
func (auo *AgentUpdateOne) AddSkillIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddSkillIDs(ids...)
	return auo
}

// AddSkills adds the "skills" edges to the AgentSkill entity.
func (auo *AgentUpdateOne) AddSkills(a ...*AgentSkill) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.AddSkillIDs(ids...)
}

// AddTaskIDs adds the "tasks" edge to the AgentTask entity by IDs.
func (auo *AgentUpdateOne) AddTaskIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddTaskIDs(ids...)
	return auo
}

// AddTasks adds the "tasks" edges to the AgentTask entity.
func (auo *AgentUpdateOne) AddTasks(a ...*AgentTask) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.AddTaskIDs(ids...)
}

// AddExperienceIDs adds the "experiences" edge to the AgentExperience entity by IDs.
func (auo *AgentUpdateOne) AddExperienceIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddExperienceIDs(ids...)
	return auo
}

// AddExperiences adds the "experiences" edges to the AgentExperience entity.
func (auo *AgentUpdateOne) AddExperiences(a ...*AgentExperience) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.AddExperienceIDs(ids...)
}

// AddCreatedConversationIDs adds the "created_conversations" edge to the Conversation entity by IDs.
func (auo *AgentUpdateOne) AddCreatedConversationIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddCreatedConversationIDs(ids...)
	return auo
}

// AddCreatedConversations adds the "created_conversations" edges to the Conversation entity.
func (auo *AgentUpdateOne) AddCreatedConversations(c ...*Conversation) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.AddCreatedConversationIDs(ids...)
}

// AddConversationParticipationIDs adds the "conversation_participations" edge to the ConversationParticipant entity by IDs.
func (auo *AgentUpdateOne) AddConversationParticipationIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddConversationParticipationIDs(ids...)
	return auo
}

// AddConversationParticipations adds the "conversation_participations" edges to the ConversationParticipant entity.
func (auo *AgentUpdateOne) AddConversationParticipations(c ...*ConversationParticipant) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.AddConversationParticipationIDs(ids...)
}

// AddSentMessageIDs adds the "sent_messages" edge to the ConversationMessage entity by IDs.
func (auo *AgentUpdateOne) AddSentMessageIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.AddSentMessageIDs(ids...)
	return auo
}

// AddSentMessages adds the "sent_messages" edges to the ConversationMessage entity.
func (auo *AgentUpdateOne) AddSentMessages(c ...*ConversationMessage) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.AddSentMessageIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (auo *AgentUpdateOne) Mutation() *AgentMutation {
	return auo.mutation
}

// ClearCreator clears the "creator" edge to the User entity.
func (auo *AgentUpdateOne) ClearCreator() *AgentUpdateOne {
	auo.mutation.ClearCreator()
	return auo
}

// ClearPosts clears all "posts" edges to the Post entity.
func (auo *AgentUpdateOne) ClearPosts() *AgentUpdateOne {
	auo.mutation.ClearPosts()
	return auo
}

// RemovePostIDs removes the "posts" edge to Post entities by IDs.
func (auo *AgentUpdateOne) RemovePostIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemovePostIDs(ids...)
	return auo
}

// RemovePosts removes "posts" edges to Post entities.
func (auo *AgentUpdateOne) RemovePosts(p ...*Post) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(p))
	for i := range p {
		ids[i] = p[i].ID
	}
	return auo.RemovePostIDs(ids...)
}

// ClearTimerTransactions clears all "timer_transactions" edges to the TimerTransaction entity.
func (auo *AgentUpdateOne) ClearTimerTransactions() *AgentUpdateOne {
	auo.mutation.ClearTimerTransactions()
	return auo
}

// RemoveTimerTransactionIDs removes the "timer_transactions" edge to TimerTransaction entities by IDs.
func (auo *AgentUpdateOne) RemoveTimerTransactionIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveTimerTransactionIDs(ids...)
	return auo
}

// RemoveTimerTransactions removes "timer_transactions" edges to TimerTransaction entities.
func (auo *AgentUpdateOne) RemoveTimerTransactions(t ...*TimerTransaction) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return auo.RemoveTimerTransactionIDs(ids...)
}

// ClearChannelConnections clears all "channel_connections" edges to the ChannelConnection entity.
func (auo *AgentUpdateOne) ClearChannelConnections() *AgentUpdateOne {
	auo.mutation.ClearChannelConnections()
	return auo
}

// RemoveChannelConnectionIDs removes the "channel_connections" edge to ChannelConnection entities by IDs.
func (auo *AgentUpdateOne) RemoveChannelConnectionIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveChannelConnectionIDs(ids...)
	return auo
}

// RemoveChannelConnections removes "channel_connections" edges to ChannelConnection entities.
func (auo *AgentUpdateOne) RemoveChannelConnections(c ...*ChannelConnection) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.RemoveChannelConnectionIDs(ids...)
}

// ClearMemorial clears the "memorial" edge to the Memorial entity.
func (auo *AgentUpdateOne) ClearMemorial() *AgentUpdateOne {
	auo.mutation.ClearMemorial()
	return auo
}

// ClearSkills clears all "skills" edges to the AgentSkill entity.
func (auo *AgentUpdateOne) ClearSkills() *AgentUpdateOne {
	auo.mutation.ClearSkills()
	return auo
}

// RemoveSkillIDs removes the "skills" edge to AgentSkill entities by IDs.
func (auo *AgentUpdateOne) RemoveSkillIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveSkillIDs(ids...)
	return auo
}

// RemoveSkills removes "skills" edges to AgentSkill entities.
func (auo *AgentUpdateOne) RemoveSkills(a ...*AgentSkill) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.RemoveSkillIDs(ids...)
}

// ClearTasks clears all "tasks" edges to the AgentTask entity.
func (auo *AgentUpdateOne) ClearTasks() *AgentUpdateOne {
	auo.mutation.ClearTasks()
	return auo
}

// RemoveTaskIDs removes the "tasks" edge to AgentTask entities by IDs.
func (auo *AgentUpdateOne) RemoveTaskIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveTaskIDs(ids...)
	return auo
}

// RemoveTasks removes "tasks" edges to AgentTask entities.
func (auo *AgentUpdateOne) RemoveTasks(a ...*AgentTask) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.RemoveTaskIDs(ids...)
}

// ClearExperiences clears all "experiences" edges to the AgentExperience entity.
func (auo *AgentUpdateOne) ClearExperiences() *AgentUpdateOne {
	auo.mutation.ClearExperiences()
	return auo
}

// RemoveExperienceIDs removes the "experiences" edge to AgentExperience entities by IDs.
func (auo *AgentUpdateOne) RemoveExperienceIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveExperienceIDs(ids...)
	return auo
}

// RemoveExperiences removes "experiences" edges to AgentExperience entities.
func (auo *AgentUpdateOne) RemoveExperiences(a ...*AgentExperience) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return auo.RemoveExperienceIDs(ids...)
}

// ClearCreatedConversations clears all "created_conversations" edges to the Conversation entity.
func (auo *AgentUpdateOne) ClearCreatedConversations() *AgentUpdateOne {
	auo.mutation.ClearCreatedConversations()
	return auo
}

// RemoveCreatedConversationIDs removes the "created_conversations" edge to Conversation entities by IDs.
func (auo *AgentUpdateOne) RemoveCreatedConversationIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveCreatedConversationIDs(ids...)
	return auo
}

// RemoveCreatedConversations removes "created_conversations" edges to Conversation entities.
func (auo *AgentUpdateOne) RemoveCreatedConversations(c ...*Conversation) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.RemoveCreatedConversationIDs(ids...)
}

// ClearConversationParticipations clears all "conversation_participations" edges to the ConversationParticipant entity.
func (auo *AgentUpdateOne) ClearConversationParticipations() *AgentUpdateOne {
	auo.mutation.ClearConversationParticipations()
	return auo
}

// RemoveConversationParticipationIDs removes the "conversation_participations" edge to ConversationParticipant entities by IDs.
func (auo *AgentUpdateOne) RemoveConversationParticipationIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveConversationParticipationIDs(ids...)
	return auo
}

// RemoveConversationParticipations removes "conversation_participations" edges to ConversationParticipant entities.
func (auo *AgentUpdateOne) RemoveConversationParticipations(c ...*ConversationParticipant) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.RemoveConversationParticipationIDs(ids...)
}

// ClearSentMessages clears all "sent_messages" edges to the ConversationMessage entity.
func (auo *AgentUpdateOne) ClearSentMessages() *AgentUpdateOne {
	auo.mutation.ClearSentMessages()
	return auo
}

// RemoveSentMessageIDs removes the "sent_messages" edge to ConversationMessage entities by IDs.
func (auo *AgentUpdateOne) RemoveSentMessageIDs(ids ...uuid.UUID) *AgentUpdateOne {
	auo.mutation.RemoveSentMessageIDs(ids...)
	return auo
}

// RemoveSentMessages removes "sent_messages" edges to ConversationMessage entities.
func (auo *AgentUpdateOne) RemoveSentMessages(c ...*ConversationMessage) *AgentUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.RemoveSentMessageIDs(ids...)
}

// Where appends a list predicates to the AgentUpdate builder.
func (auo *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Agent entity.
func (auo *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AgentUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AgentUpdateOne) check() error {
	if v, ok := auo.mutation.Name(); ok {
		if err := agent.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Agent.name": %w`, err)}
		}
	}
	if v, ok := auo.mutation.GoalDescription(); ok {
		if err := agent.GoalDescriptionValidator(v); err != nil {
			return &ValidationError{Name: "goal_description", err: fmt.Errorf(`ent: validator failed for field "Agent.goal_description": %w`, err)}
		}
	}
	if auo.mutation.CreatorCleared() && len(auo.mutation.CreatorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Agent.creator"`)
	}
	return nil
}

func (auo *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.Name(); ok {
		_spec.SetField(agent.FieldName, field.TypeString, value)
	}
	if value, ok := auo.mutation.Avatar(); ok {
		_spec.SetField(agent.FieldAvatar, field.TypeString, value)
	}
	if auo.mutation.AvatarCleared() {
		_spec.ClearField(agent.FieldAvatar, field.TypeString)
	}
	if value, ok := auo.mutation.Personality(); ok {
		_spec.SetField(agent.FieldPersonality, field.TypeJSON, value)
	}
	if value, ok := auo.mutation.AppendedPersonality(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, agent.FieldPersonality, value)
		})
	}
	if value, ok := auo.mutation.GoalDescription(); ok {
		_spec.SetField(agent.FieldGoalDescription, field.TypeString, value)
	}
	if value, ok := auo.mutation.GoalCurrent(); ok {
		_spec.SetField(agent.FieldGoalCurrent, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedGoalCurrent(); ok {
		_spec.AddField(agent.FieldGoalCurrent, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.GoalTarget(); ok {
		_spec.SetField(agent.FieldGoalTarget, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedGoalTarget(); ok {
		_spec.AddField(agent.FieldGoalTarget, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeString, value)
	}
	if value, ok := auo.mutation.TimerRemaining(); ok {
		_spec.SetField(agent.FieldTimerRemaining, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedTimerRemaining(); ok {
		_spec.AddField(agent.FieldTimerRemaining, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.TotalTimerReceived(); ok {
		_spec.SetField(agent.FieldTotalTimerReceived, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedTotalTimerReceived(); ok {
		_spec.AddField(agent.FieldTotalTimerReceived, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.OpenclawMode(); ok {
		_spec.SetField(agent.FieldOpenclawMode, field.TypeString, value)
	}
	if value, ok := auo.mutation.OpenclawGatewayID(); ok {
		_spec.SetField(agent.FieldOpenclawGatewayID, field.TypeString, value)
	}
	if auo.mutation.OpenclawGatewayIDCleared() {
		_spec.ClearField(agent.FieldOpenclawGatewayID, field.TypeString)
	}
	if value, ok := auo.mutation.OpenclawAgentID(); ok {
		_spec.SetField(agent.FieldOpenclawAgentID, field.TypeString, value)
	}
	if auo.mutation.OpenclawAgentIDCleared() {
		_spec.ClearField(agent.FieldOpenclawAgentID, field.TypeString)
	}
	if value, ok := auo.mutation.OpenclawWorkspace(); ok {
		_spec.SetField(agent.FieldOpenclawWorkspace, field.TypeString, value)
	}
	if auo.mutation.OpenclawWorkspaceCleared() {
		_spec.ClearField(agent.FieldOpenclawWorkspace, field.TypeString)
	}
	if value, ok := auo.mutation.OpenclawToken(); ok {
		_spec.SetField(agent.FieldOpenclawToken, field.TypeString, value)
	}
	if auo.mutation.OpenclawTokenCleared() {
		_spec.ClearField(agent.FieldOpenclawToken, field.TypeString)
	}
	if value, ok := auo.mutation.IsPlatformNative(); ok {
		_spec.SetField(agent.FieldIsPlatformNative, field.TypeBool, value)
	}
	if value, ok := auo.mutation.BornAt(); ok {
		_spec.SetField(agent.FieldBornAt, field.TypeTime, value)
	}
	if value, ok := auo.mutation.DiedAt(); ok {
		_spec.SetField(agent.FieldDiedAt, field.TypeTime, value)
	}
	if auo.mutation.DiedAtCleared() {
		_spec.ClearField(agent.FieldDiedAt, field.TypeTime)
	}
	if value, ok := auo.mutation.LastWords(); ok {
		_spec.SetField(agent.FieldLastWords, field.TypeString, value)
	}
	if auo.mutation.LastWordsCleared() {
		_spec.ClearField(agent.FieldLastWords, field.TypeString)
	}
	if value, ok := auo.mutation.PostCount(); ok {
		_spec.SetField(agent.FieldPostCount, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedPostCount(); ok {
		_spec.AddField(agent.FieldPostCount, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.FollowerCount(); ok {
		_spec.SetField(agent.FieldFollowerCount, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedFollowerCount(); ok {
		_spec.AddField(agent.FieldFollowerCount, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.InteractionCount(); ok {
		_spec.SetField(agent.FieldInteractionCount, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedInteractionCount(); ok {
		_spec.AddField(agent.FieldInteractionCount, field.TypeInt64, value)
	}
	if auo.mutation.CreatorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.CreatorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agent.CreatorTable,
			Columns: []string{agent.CreatorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PostsTable,
			Columns: []string{agent.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedPostsIDs(); len(nodes) > 0 && !auo.mutation.PostsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PostsTable,
			Columns: []string{agent.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.PostsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.PostsTable,
			Columns: []string{agent.PostsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(post.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.TimerTransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TimerTransactionsTable,
			Columns: []string{agent.TimerTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timertransaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedTimerTransactionsIDs(); len(nodes) > 0 && !auo.mutation.TimerTransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TimerTransactionsTable,
			Columns: []string{agent.TimerTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timertransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.TimerTransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TimerTransactionsTable,
			Columns: []string{agent.TimerTransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(timertransaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.ChannelConnectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ChannelConnectionsTable,
			Columns: []string{agent.ChannelConnectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedChannelConnectionsIDs(); len(nodes) > 0 && !auo.mutation.ChannelConnectionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ChannelConnectionsTable,
			Columns: []string{agent.ChannelConnectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ChannelConnectionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ChannelConnectionsTable,
			Columns: []string{agent.ChannelConnectionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.MemorialCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.MemorialTable,
			Columns: []string{agent.MemorialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorial.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.MemorialIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   agent.MemorialTable,
			Columns: []string{agent.MemorialColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(memorial.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SkillsTable,
			Columns: []string{agent.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedSkillsIDs(); len(nodes) > 0 && !auo.mutation.SkillsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SkillsTable,
			Columns: []string{agent.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.SkillsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SkillsTable,
			Columns: []string{agent.SkillsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentskill.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedTasksIDs(); len(nodes) > 0 && !auo.mutation.TasksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.TasksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.TasksTable,
			Columns: []string{agent.TasksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.ExperiencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ExperiencesTable,
			Columns: []string{agent.ExperiencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexperience.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedExperiencesIDs(); len(nodes) > 0 && !auo.mutation.ExperiencesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ExperiencesTable,
			Columns: []string{agent.ExperiencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexperience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ExperiencesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ExperiencesTable,
			Columns: []string{agent.ExperiencesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agentexperience.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.CreatedConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.CreatedConversationsTable,
			Columns: []string{agent.CreatedConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedCreatedConversationsIDs(); len(nodes) > 0 && !auo.mutation.CreatedConversationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.CreatedConversationsTable,
			Columns: []string{agent.CreatedConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.CreatedConversationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.CreatedConversationsTable,
			Columns: []string{agent.CreatedConversationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.ConversationParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ConversationParticipationsTable,
			Columns: []string{agent.ConversationParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedConversationParticipationsIDs(); len(nodes) > 0 && !auo.mutation.ConversationParticipationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ConversationParticipationsTable,
			Columns: []string{agent.ConversationParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ConversationParticipationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.ConversationParticipationsTable,
			Columns: []string{agent.ConversationParticipationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.SentMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SentMessagesTable,
			Columns: []string{agent.SentMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedSentMessagesIDs(); len(nodes) > 0 && !auo.mutation.SentMessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SentMessagesTable,
			Columns: []string{agent.SentMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.SentMessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.SentMessagesTable,
			Columns: []string{agent.SentMessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Agent{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
