// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/agenttask"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AgentTaskCreate is the builder for creating a AgentTask entity.
type AgentTaskCreate struct {
	config
	mutation *AgentTaskMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentTaskCreate) SetCreatedAt(v time.Time) *AgentTaskCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentTaskCreate) SetNillableCreatedAt(v *time.Time) *AgentTaskCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentTaskCreate) SetUpdatedAt(v time.Time) *AgentTaskCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentTaskCreate) SetNillableUpdatedAt(v *time.Time) *AgentTaskCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAgentID sets the "agent_id" field.
func (_c *AgentTaskCreate) SetAgentID(v uuid.UUID) *AgentTaskCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetTitle sets the "title" field.
func (_c *AgentTaskCreate) SetTitle(v string) *AgentTaskCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *AgentTaskCreate) SetDescription(v string) *AgentTaskCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *AgentTaskCreate) SetNillableDescription(v *string) *AgentTaskCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentTaskCreate) SetStatus(v string) *AgentTaskCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AgentTaskCreate) SetNillableStatus(v *string) *AgentTaskCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetPriority sets the "priority" field.
func (_c *AgentTaskCreate) SetPriority(v string) *AgentTaskCreate {
	_c.mutation.SetPriority(v)
	return _c
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_c *AgentTaskCreate) SetNillablePriority(v *string) *AgentTaskCreate {
	if v != nil {
		_c.SetPriority(*v)
	}
	return _c
}

// SetProgress sets the "progress" field.
func (_c *AgentTaskCreate) SetProgress(v int) *AgentTaskCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *AgentTaskCreate) SetNillableProgress(v *int) *AgentTaskCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AgentTaskCreate) SetDeletedAt(v time.Time) *AgentTaskCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AgentTaskCreate) SetNillableDeletedAt(v *time.Time) *AgentTaskCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentTaskCreate) SetID(v uuid.UUID) *AgentTaskCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentTaskCreate) SetNillableID(v *uuid.UUID) *AgentTaskCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_c *AgentTaskCreate) SetAgent(v *Agent) *AgentTaskCreate {
	return _c.SetAgentID(v.ID)
}

// Mutation returns the AgentTaskMutation object of the builder.
func (_c *AgentTaskCreate) Mutation() *AgentTaskMutation {
	return _c.mutation
}

// Save creates the AgentTask in the database.
func (_c *AgentTaskCreate) Save(ctx context.Context) (*AgentTask, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentTaskCreate) SaveX(ctx context.Context) *AgentTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentTaskCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentTaskCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentTaskCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agenttask.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agenttask.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := agenttask.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Priority(); !ok {
		v := agenttask.DefaultPriority
		_c.mutation.SetPriority(v)
	}
	if _, ok := _c.mutation.Progress(); !ok {
		v := agenttask.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agenttask.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentTaskCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AgentTask.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AgentTask.updated_at"`)}
	}
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "AgentTask.agent_id"`)}
	}
	if _, ok := _c.mutation.Title(); !ok {
		return &ValidationError{Name: "title", err: errors.New(`ent: missing required field "AgentTask.title"`)}
	}
	if v, ok := _c.mutation.Title(); ok {
		if err := agenttask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "AgentTask.title": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := agenttask.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentTask.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AgentTask.status"`)}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "AgentTask.progress"`)}
	}
	if v, ok := _c.mutation.Progress(); ok {
		if err := agenttask.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "AgentTask.progress": %w`, err)}
		}
	}
	if len(_c.mutation.AgentIDs()) == 0 {
		return &ValidationError{Name: "agent", err: errors.New(`ent: missing required edge "AgentTask.agent"`)}
	}
	return nil
}

func (_c *AgentTaskCreate) sqlSave(ctx context.Context) (*AgentTask, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentTaskCreate) createSpec() (*AgentTask, *sqlgraph.CreateSpec) {
	var (
		_node = &AgentTask{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agenttask.Table, sqlgraph.NewFieldSpec(agenttask.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agenttask.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agenttask.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(agenttask.FieldTitle, field.TypeString, value)
		_node.Title = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(agenttask.FieldDescription, field.TypeString, value)
		_node.Description = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agenttask.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Priority(); ok {
		_spec.SetField(agenttask.FieldPriority, field.TypeString, value)
		_node.Priority = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(agenttask.FieldProgress, field.TypeInt, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(agenttask.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if nodes := _c.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agenttask.AgentTable,
			Columns: []string{agenttask.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AgentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentTaskCreateBulk is the builder for creating many AgentTask entities in bulk.
type AgentTaskCreateBulk struct {
	config
	err      error
	builders []*AgentTaskCreate
}

// Save creates the AgentTask entities in the database.
func (_c *AgentTaskCreateBulk) Save(ctx context.Context) ([]*AgentTask, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AgentTask, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentTaskMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentTaskCreateBulk) SaveX(ctx context.Context) []*AgentTask {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentTaskCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentTaskCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
