// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/agentexperience"
	"backend/ent/predicate"
	"backend/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AgentExperienceUpdate is the builder for updating AgentExperience entities.
type AgentExperienceUpdate struct {
	config
	hooks    []Hook
	mutation *AgentExperienceMutation
}

// Where appends a list predicates to the AgentExperienceUpdate builder.
func (aeu *AgentExperienceUpdate) Where(ps ...predicate.AgentExperience) *AgentExperienceUpdate {
	aeu.mutation.Where(ps...)
	return aeu
}

// SetUpdatedAt sets the "updated_at" field.
func (aeu *AgentExperienceUpdate) SetUpdatedAt(t time.Time) *AgentExperienceUpdate {
	aeu.mutation.SetUpdatedAt(t)
	return aeu
}

// SetOwnerUserID sets the "owner_user_id" field.
func (aeu *AgentExperienceUpdate) SetOwnerUserID(u uuid.UUID) *AgentExperienceUpdate {
	aeu.mutation.SetOwnerUserID(u)
	return aeu
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (aeu *AgentExperienceUpdate) SetNillableOwnerUserID(u *uuid.UUID) *AgentExperienceUpdate {
	if u != nil {
		aeu.SetOwnerUserID(*u)
	}
	return aeu
}

// SetAgentID sets the "agent_id" field.
func (aeu *AgentExperienceUpdate) SetAgentID(u uuid.UUID) *AgentExperienceUpdate {
	aeu.mutation.SetAgentID(u)
	return aeu
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (aeu *AgentExperienceUpdate) SetNillableAgentID(u *uuid.UUID) *AgentExperienceUpdate {
	if u != nil {
		aeu.SetAgentID(*u)
	}
	return aeu
}

// SetAgentName sets the "agent_name" field.
func (aeu *AgentExperienceUpdate) SetAgentName(s string) *AgentExperienceUpdate {
	aeu.mutation.SetAgentName(s)
	return aeu
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (aeu *AgentExperienceUpdate) SetNillableAgentName(s *string) *AgentExperienceUpdate {
	if s != nil {
		aeu.SetAgentName(*s)
	}
	return aeu
}

// SetAgentAvatar sets the "agent_avatar" field.
func (aeu *AgentExperienceUpdate) SetAgentAvatar(s string) *AgentExperienceUpdate {
	aeu.mutation.SetAgentAvatar(s)
	return aeu
}

// SetNillableAgentAvatar sets the "agent_avatar" field if the given value is not nil.
func (aeu *AgentExperienceUpdate) SetNillableAgentAvatar(s *string) *AgentExperienceUpdate {
	if s != nil {
		aeu.SetAgentAvatar(*s)
	}
	return aeu
}

// ClearAgentAvatar clears the value of the "agent_avatar" field.
func (aeu *AgentExperienceUpdate) ClearAgentAvatar() *AgentExperienceUpdate {
	aeu.mutation.ClearAgentAvatar()
	return aeu
}

// SetExpType sets the "exp_type" field.
func (aeu *AgentExperienceUpdate) SetExpType(s string) *AgentExperienceUpdate {
	aeu.mutation.SetExpType(s)
	return aeu
}

// SetNillableExpType sets the "exp_type" field if the given value is not nil.
func (aeu *AgentExperienceUpdate) SetNillableExpType(s *string) *AgentExperienceUpdate {
	if s != nil {
		aeu.SetExpType(*s)
	}
	return aeu
}

// SetTitle sets the "title" field.
func (aeu *AgentExperienceUpdate) SetTitle(s string) *AgentExperienceUpdate {
	aeu.mutation.SetTitle(s)
	return aeu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (aeu *AgentExperienceUpdate) SetNillableTitle(s *string) *AgentExperienceUpdate {
	if s != nil {
		aeu.SetTitle(*s)
	}
	return aeu
}

// SetDescription sets the "description" field.
func (aeu *AgentExperienceUpdate) SetDescription(s string) *AgentExperienceUpdate {
	aeu.mutation.SetDescription(s)
	return aeu
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (aeu *AgentExperienceUpdate) SetNillableDescription(s *string) *AgentExperienceUpdate {
	if s != nil {
		aeu.SetDescription(*s)
	}
	return aeu
}

// SetEventAt sets the "event_at" field.
func (aeu *AgentExperienceUpdate) SetEventAt(t time.Time) *AgentExperienceUpdate {
	aeu.mutation.SetEventAt(t)
	return aeu
}

// SetNillableEventAt sets the "event_at" field if the given value is not nil.
func (aeu *AgentExperienceUpdate) SetNillableEventAt(t *time.Time) *AgentExperienceUpdate {
	if t != nil {
		aeu.SetEventAt(*t)
	}
	return aeu
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (aeu *AgentExperienceUpdate) SetOwnerID(id uuid.UUID) *AgentExperienceUpdate {
	aeu.mutation.SetOwnerID(id)
	return aeu
}

// SetOwner sets the "owner" edge to the User entity.
func (aeu *AgentExperienceUpdate) SetOwner(u *User) *AgentExperienceUpdate {
	return aeu.SetOwnerID(u.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (aeu *AgentExperienceUpdate) SetAgent(a *Agent) *AgentExperienceUpdate {
	return aeu.SetAgentID(a.ID)
}

// Mutation returns the AgentExperienceMutation object of the builder.
func (aeu *AgentExperienceUpdate) Mutation() *AgentExperienceMutation {
	return aeu.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (aeu *AgentExperienceUpdate) ClearOwner() *AgentExperienceUpdate {
	aeu.mutation.ClearOwner()
	return aeu
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (aeu *AgentExperienceUpdate) ClearAgent() *AgentExperienceUpdate {
	aeu.mutation.ClearAgent()
	return aeu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (aeu *AgentExperienceUpdate) Save(ctx context.Context) (int, error) {
	aeu.defaults()
	return withHooks(ctx, aeu.sqlSave, aeu.mutation, aeu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aeu *AgentExperienceUpdate) SaveX(ctx context.Context) int {
	affected, err := aeu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (aeu *AgentExperienceUpdate) Exec(ctx context.Context) error {
	_, err := aeu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aeu *AgentExperienceUpdate) ExecX(ctx context.Context) {
	if err := aeu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aeu *AgentExperienceUpdate) defaults() {
	if _, ok := aeu.mutation.UpdatedAt(); !ok {
		v := agentexperience.UpdateDefaultUpdatedAt()
		aeu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aeu *AgentExperienceUpdate) check() error {
	if v, ok := aeu.mutation.AgentName(); ok {
		if err := agentexperience.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "AgentExperience.agent_name": %w`, err)}
		}
	}
	if v, ok := aeu.mutation.Title(); ok {
		if err := agentexperience.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "AgentExperience.title": %w`, err)}
		}
	}
	if v, ok := aeu.mutation.Description(); ok {
		if err := agentexperience.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentExperience.description": %w`, err)}
		}
	}
	if aeu.mutation.OwnerCleared() && len(aeu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentExperience.owner"`)
	}
	if aeu.mutation.AgentCleared() && len(aeu.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentExperience.agent"`)
	}
	return nil
}

func (aeu *AgentExperienceUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := aeu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentexperience.Table, agentexperience.Columns, sqlgraph.NewFieldSpec(agentexperience.FieldID, field.TypeUUID))
	if ps := aeu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aeu.mutation.UpdatedAt(); ok {
		_spec.SetField(agentexperience.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aeu.mutation.AgentName(); ok {
		_spec.SetField(agentexperience.FieldAgentName, field.TypeString, value)
	}
	if value, ok := aeu.mutation.AgentAvatar(); ok {
		_spec.SetField(agentexperience.FieldAgentAvatar, field.TypeString, value)
	}
	if aeu.mutation.AgentAvatarCleared() {
		_spec.ClearField(agentexperience.FieldAgentAvatar, field.TypeString)
	}
	if value, ok := aeu.mutation.ExpType(); ok {
		_spec.SetField(agentexperience.FieldExpType, field.TypeString, value)
	}
	if value, ok := aeu.mutation.Title(); ok {
		_spec.SetField(agentexperience.FieldTitle, field.TypeString, value)
	}
	if value, ok := aeu.mutation.Description(); ok {
		_spec.SetField(agentexperience.FieldDescription, field.TypeString, value)
	}
	if value, ok := aeu.mutation.EventAt(); ok {
		_spec.SetField(agentexperience.FieldEventAt, field.TypeTime, value)
	}
	if aeu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexperience.OwnerTable,
			Columns: []string{agentexperience.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aeu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexperience.OwnerTable,
			Columns: []string{agentexperience.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aeu.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexperience.AgentTable,
			Columns: []string{agentexperience.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aeu.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexperience.AgentTable,
			Columns: []string{agentexperience.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, aeu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentexperience.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	aeu.mutation.done = true
	return n, nil
}

// AgentExperienceUpdateOne is the builder for updating a single AgentExperience entity.
type AgentExperienceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentExperienceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (aeuo *AgentExperienceUpdateOne) SetUpdatedAt(t time.Time) *AgentExperienceUpdateOne {
	aeuo.mutation.SetUpdatedAt(t)
	return aeuo
}

// SetOwnerUserID sets the "owner_user_id" field.
func (aeuo *AgentExperienceUpdateOne) SetOwnerUserID(u uuid.UUID) *AgentExperienceUpdateOne {
	aeuo.mutation.SetOwnerUserID(u)
	return aeuo
}

// SetNillableOwnerUserID sets the "owner_user_id" field if the given value is not nil.
func (aeuo *AgentExperienceUpdateOne) SetNillableOwnerUserID(u *uuid.UUID) *AgentExperienceUpdateOne {
	if u != nil {
		aeuo.SetOwnerUserID(*u)
	}
	return aeuo
}

// SetAgentID sets the "agent_id" field.
func (aeuo *AgentExperienceUpdateOne) SetAgentID(u uuid.UUID) *AgentExperienceUpdateOne {
	aeuo.mutation.SetAgentID(u)
	return aeuo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (aeuo *AgentExperienceUpdateOne) SetNillableAgentID(u *uuid.UUID) *AgentExperienceUpdateOne {
	if u != nil {
		aeuo.SetAgentID(*u)
	}
	return aeuo
}

// SetAgentName sets the "agent_name" field.
func (aeuo *AgentExperienceUpdateOne) SetAgentName(s string) *AgentExperienceUpdateOne {
	aeuo.mutation.SetAgentName(s)
	return aeuo
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (aeuo *AgentExperienceUpdateOne) SetNillableAgentName(s *string) *AgentExperienceUpdateOne {
	if s != nil {
		aeuo.SetAgentName(*s)
	}
	return aeuo
}

// SetAgentAvatar sets the "agent_avatar" field.
func (aeuo *AgentExperienceUpdateOne) SetAgentAvatar(s string) *AgentExperienceUpdateOne {
	aeuo.mutation.SetAgentAvatar(s)
	return aeuo
}

// SetNillableAgentAvatar sets the "agent_avatar" field if the given value is not nil.
func (aeuo *AgentExperienceUpdateOne) SetNillableAgentAvatar(s *string) *AgentExperienceUpdateOne {
	if s != nil {
		aeuo.SetAgentAvatar(*s)
	}
	return aeuo
}

// ClearAgentAvatar clears the value of the "agent_avatar" field.
func (aeuo *AgentExperienceUpdateOne) ClearAgentAvatar() *AgentExperienceUpdateOne {
	aeuo.mutation.ClearAgentAvatar()
	return aeuo
}

// SetExpType sets the "exp_type" field.
func (aeuo *AgentExperienceUpdateOne) SetExpType(s string) *AgentExperienceUpdateOne {
	aeuo.mutation.SetExpType(s)
	return aeuo
}

// SetNillableExpType sets the "exp_type" field if the given value is not nil.
func (aeuo *AgentExperienceUpdateOne) SetNillableExpType(s *string) *AgentExperienceUpdateOne {
	if s != nil {
		aeuo.SetExpType(*s)
	}
	return aeuo
}

// SetTitle sets the "title" field.
func (aeuo *AgentExperienceUpdateOne) SetTitle(s string) *AgentExperienceUpdateOne {
	aeuo.mutation.SetTitle(s)
	return aeuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (aeuo *AgentExperienceUpdateOne) SetNillableTitle(s *string) *AgentExperienceUpdateOne {
	if s != nil {
		aeuo.SetTitle(*s)
	}
	return aeuo
}

// SetDescription sets the "description" field.
func (aeuo *AgentExperienceUpdateOne) SetDescription(s string) *AgentExperienceUpdateOne {
	aeuo.mutation.SetDescription(s)
	return aeuo
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (aeuo *AgentExperienceUpdateOne) SetNillableDescription(s *string) *AgentExperienceUpdateOne {
	if s != nil {
		aeuo.SetDescription(*s)
	}
	return aeuo
}

// SetEventAt sets the "event_at" field.
func (aeuo *AgentExperienceUpdateOne) SetEventAt(t time.Time) *AgentExperienceUpdateOne {
	aeuo.mutation.SetEventAt(t)
	return aeuo
}

// SetNillableEventAt sets the "event_at" field if the given value is not nil.
func (aeuo *AgentExperienceUpdateOne) SetNillableEventAt(t *time.Time) *AgentExperienceUpdateOne {
	if t != nil {
		aeuo.SetEventAt(*t)
	}
	return aeuo
}

// SetOwnerID sets the "owner" edge to the User entity by ID.
func (aeuo *AgentExperienceUpdateOne) SetOwnerID(id uuid.UUID) *AgentExperienceUpdateOne {
	aeuo.mutation.SetOwnerID(id)
	return aeuo
}

// SetOwner sets the "owner" edge to the User entity.
func (aeuo *AgentExperienceUpdateOne) SetOwner(u *User) *AgentExperienceUpdateOne {
	return aeuo.SetOwnerID(u.ID)
}

// SetAgent sets the "agent" edge to the Agent entity.
func (aeuo *AgentExperienceUpdateOne) SetAgent(a *Agent) *AgentExperienceUpdateOne {
	return aeuo.SetAgentID(a.ID)
}

// Mutation returns the AgentExperienceMutation object of the builder.
func (aeuo *AgentExperienceUpdateOne) Mutation() *AgentExperienceMutation {
	return aeuo.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (aeuo *AgentExperienceUpdateOne) ClearOwner() *AgentExperienceUpdateOne {
	aeuo.mutation.ClearOwner()
	return aeuo
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (aeuo *AgentExperienceUpdateOne) ClearAgent() *AgentExperienceUpdateOne {
	aeuo.mutation.ClearAgent()
	return aeuo
}

// Where appends a list predicates to the AgentExperienceUpdate builder.
func (aeuo *AgentExperienceUpdateOne) Where(ps ...predicate.AgentExperience) *AgentExperienceUpdateOne {
	aeuo.mutation.Where(ps...)
	return aeuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (aeuo *AgentExperienceUpdateOne) Select(field string, fields ...string) *AgentExperienceUpdateOne {
	aeuo.fields = append([]string{field}, fields...)
	return aeuo
}

// Save executes the query and returns the updated AgentExperience entity.
func (aeuo *AgentExperienceUpdateOne) Save(ctx context.Context) (*AgentExperience, error) {
	aeuo.defaults()
	return withHooks(ctx, aeuo.sqlSave, aeuo.mutation, aeuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (aeuo *AgentExperienceUpdateOne) SaveX(ctx context.Context) *AgentExperience {
	node, err := aeuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (aeuo *AgentExperienceUpdateOne) Exec(ctx context.Context) error {
	_, err := aeuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (aeuo *AgentExperienceUpdateOne) ExecX(ctx context.Context) {
	if err := aeuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (aeuo *AgentExperienceUpdateOne) defaults() {
	if _, ok := aeuo.mutation.UpdatedAt(); !ok {
		v := agentexperience.UpdateDefaultUpdatedAt()
		aeuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (aeuo *AgentExperienceUpdateOne) check() error {
	if v, ok := aeuo.mutation.AgentName(); ok {
		if err := agentexperience.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "AgentExperience.agent_name": %w`, err)}
		}
	}
	if v, ok := aeuo.mutation.Title(); ok {
		if err := agentexperience.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "AgentExperience.title": %w`, err)}
		}
	}
	if v, ok := aeuo.mutation.Description(); ok {
		if err := agentexperience.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "AgentExperience.description": %w`, err)}
		}
	}
	if aeuo.mutation.OwnerCleared() && len(aeuo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentExperience.owner"`)
	}
	if aeuo.mutation.AgentCleared() && len(aeuo.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AgentExperience.agent"`)
	}
	return nil
}

func (aeuo *AgentExperienceUpdateOne) sqlSave(ctx context.Context) (_node *AgentExperience, err error) {
	if err := aeuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agentexperience.Table, agentexperience.Columns, sqlgraph.NewFieldSpec(agentexperience.FieldID, field.TypeUUID))
	id, ok := aeuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AgentExperience.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := aeuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agentexperience.FieldID)
		for _, f := range fields {
			if !agentexperience.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agentexperience.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := aeuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := aeuo.mutation.UpdatedAt(); ok {
		_spec.SetField(agentexperience.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := aeuo.mutation.AgentName(); ok {
		_spec.SetField(agentexperience.FieldAgentName, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.AgentAvatar(); ok {
		_spec.SetField(agentexperience.FieldAgentAvatar, field.TypeString, value)
	}
	if aeuo.mutation.AgentAvatarCleared() {
		_spec.ClearField(agentexperience.FieldAgentAvatar, field.TypeString)
	}
	if value, ok := aeuo.mutation.ExpType(); ok {
		_spec.SetField(agentexperience.FieldExpType, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.Title(); ok {
		_spec.SetField(agentexperience.FieldTitle, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.Description(); ok {
		_spec.SetField(agentexperience.FieldDescription, field.TypeString, value)
	}
	if value, ok := aeuo.mutation.EventAt(); ok {
		_spec.SetField(agentexperience.FieldEventAt, field.TypeTime, value)
	}
	if aeuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexperience.OwnerTable,
			Columns: []string{agentexperience.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aeuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexperience.OwnerTable,
			Columns: []string{agentexperience.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if aeuo.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexperience.AgentTable,
			Columns: []string{agentexperience.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := aeuo.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   agentexperience.AgentTable,
			Columns: []string{agentexperience.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AgentExperience{config: aeuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, aeuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agentexperience.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	aeuo.mutation.done = true
	return _node, nil
}
