// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/channelconnection"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ChannelConnectionCreate is the builder for creating a ChannelConnection entity.
type ChannelConnectionCreate struct {
	config
	mutation *ChannelConnectionMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ccc *ChannelConnectionCreate) SetCreatedAt(t time.Time) *ChannelConnectionCreate {
	ccc.mutation.SetCreatedAt(t)
	return ccc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ccc *ChannelConnectionCreate) SetNillableCreatedAt(t *time.Time) *ChannelConnectionCreate {
	if t != nil {
		ccc.SetCreatedAt(*t)
	}
	return ccc
}

// SetUpdatedAt sets the "updated_at" field.
func (ccc *ChannelConnectionCreate) SetUpdatedAt(t time.Time) *ChannelConnectionCreate {
	ccc.mutation.SetUpdatedAt(t)
	return ccc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ccc *ChannelConnectionCreate) SetNillableUpdatedAt(t *time.Time) *ChannelConnectionCreate {
	if t != nil {
		ccc.SetUpdatedAt(*t)
	}
	return ccc
}

// SetAgentID sets the "agent_id" field.
func (ccc *ChannelConnectionCreate) SetAgentID(u uuid.UUID) *ChannelConnectionCreate {
	ccc.mutation.SetAgentID(u)
	return ccc
}

// SetChannelType sets the "channel_type" field.
func (ccc *ChannelConnectionCreate) SetChannelType(s string) *ChannelConnectionCreate {
	ccc.mutation.SetChannelType(s)
	return ccc
}

// SetStatus sets the "status" field.
func (ccc *ChannelConnectionCreate) SetStatus(s string) *ChannelConnectionCreate {
	ccc.mutation.SetStatus(s)
	return ccc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ccc *ChannelConnectionCreate) SetNillableStatus(s *string) *ChannelConnectionCreate {
	if s != nil {
		ccc.SetStatus(*s)
	}
	return ccc
}

// SetHandle sets the "handle" field.
func (ccc *ChannelConnectionCreate) SetHandle(s string) *ChannelConnectionCreate {
	ccc.mutation.SetHandle(s)
	return ccc
}

// SetNillableHandle sets the "handle" field if the given value is not nil.
func (ccc *ChannelConnectionCreate) SetNillableHandle(s *string) *ChannelConnectionCreate {
	if s != nil {
		ccc.SetHandle(*s)
	}
	return ccc
}

// SetDeepLink sets the "deep_link" field.
func (ccc *ChannelConnectionCreate) SetDeepLink(s string) *ChannelConnectionCreate {
	ccc.mutation.SetDeepLink(s)
	return ccc
}

// SetNillableDeepLink sets the "deep_link" field if the given value is not nil.
func (ccc *ChannelConnectionCreate) SetNillableDeepLink(s *string) *ChannelConnectionCreate {
	if s != nil {
		ccc.SetDeepLink(*s)
	}
	return ccc
}

// SetConnectedAt sets the "connected_at" field.
func (ccc *ChannelConnectionCreate) SetConnectedAt(t time.Time) *ChannelConnectionCreate {
	ccc.mutation.SetConnectedAt(t)
	return ccc
}

// SetNillableConnectedAt sets the "connected_at" field if the given value is not nil.
func (ccc *ChannelConnectionCreate) SetNillableConnectedAt(t *time.Time) *ChannelConnectionCreate {
	if t != nil {
		ccc.SetConnectedAt(*t)
	}
	return ccc
}

// SetID sets the "id" field.
func (ccc *ChannelConnectionCreate) SetID(u uuid.UUID) *ChannelConnectionCreate {
	ccc.mutation.SetID(u)
	return ccc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ccc *ChannelConnectionCreate) SetNillableID(u *uuid.UUID) *ChannelConnectionCreate {
	if u != nil {
		ccc.SetID(*u)
	}
	return ccc
}

// SetAgent sets the "agent" edge to the Agent entity.
func (ccc *ChannelConnectionCreate) SetAgent(a *Agent) *ChannelConnectionCreate {
	return ccc.SetAgentID(a.ID)
}

// Mutation returns the ChannelConnectionMutation object of the builder.
func (ccc *ChannelConnectionCreate) Mutation() *ChannelConnectionMutation {
	return ccc.mutation
}

// Save creates the ChannelConnection in the database.
func (ccc *ChannelConnectionCreate) Save(ctx context.Context) (*ChannelConnection, error) {
	ccc.defaults()
	return withHooks(ctx, ccc.sqlSave, ccc.mutation, ccc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ccc *ChannelConnectionCreate) SaveX(ctx context.Context) *ChannelConnection {
	v, err := ccc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccc *ChannelConnectionCreate) Exec(ctx context.Context) error {
	_, err := ccc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccc *ChannelConnectionCreate) ExecX(ctx context.Context) {
	if err := ccc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ccc *ChannelConnectionCreate) defaults() {
	if _, ok := ccc.mutation.CreatedAt(); !ok {
		v := channelconnection.DefaultCreatedAt()
		ccc.mutation.SetCreatedAt(v)
	}
	if _, ok := ccc.mutation.UpdatedAt(); !ok {
		v := channelconnection.DefaultUpdatedAt()
		ccc.mutation.SetUpdatedAt(v)
	}
	if _, ok := ccc.mutation.Status(); !ok {
		v := channelconnection.DefaultStatus
		ccc.mutation.SetStatus(v)
	}
	if _, ok := ccc.mutation.ID(); !ok {
		v := channelconnection.DefaultID()
		ccc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ccc *ChannelConnectionCreate) check() error {
	if _, ok := ccc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ChannelConnection.created_at"`)}
	}
	if _, ok := ccc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "ChannelConnection.updated_at"`)}
	}
	if _, ok := ccc.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "ChannelConnection.agent_id"`)}
	}
	if _, ok := ccc.mutation.ChannelType(); !ok {
		return &ValidationError{Name: "channel_type", err: errors.New(`ent: missing required field "ChannelConnection.channel_type"`)}
	}
	if v, ok := ccc.mutation.ChannelType(); ok {
		if err := channelconnection.ChannelTypeValidator(v); err != nil {
			return &ValidationError{Name: "channel_type", err: fmt.Errorf(`ent: validator failed for field "ChannelConnection.channel_type": %w`, err)}
		}
	}
	if _, ok := ccc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ChannelConnection.status"`)}
	}
	if len(ccc.mutation.AgentIDs()) == 0 {
		return &ValidationError{Name: "agent", err: errors.New(`ent: missing required edge "ChannelConnection.agent"`)}
	}
	return nil
}

func (ccc *ChannelConnectionCreate) sqlSave(ctx context.Context) (*ChannelConnection, error) {
	if err := ccc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ccc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ccc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ccc.mutation.id = &_node.ID
	ccc.mutation.done = true
	return _node, nil
}

func (ccc *ChannelConnectionCreate) createSpec() (*ChannelConnection, *sqlgraph.CreateSpec) {
	var (
		_node = &ChannelConnection{config: ccc.config}
		_spec = sqlgraph.NewCreateSpec(channelconnection.Table, sqlgraph.NewFieldSpec(channelconnection.FieldID, field.TypeUUID))
	)
	if id, ok := ccc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ccc.mutation.CreatedAt(); ok {
		_spec.SetField(channelconnection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ccc.mutation.UpdatedAt(); ok {
		_spec.SetField(channelconnection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ccc.mutation.ChannelType(); ok {
		_spec.SetField(channelconnection.FieldChannelType, field.TypeString, value)
		_node.ChannelType = value
	}
	if value, ok := ccc.mutation.Status(); ok {
		_spec.SetField(channelconnection.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := ccc.mutation.Handle(); ok {
		_spec.SetField(channelconnection.FieldHandle, field.TypeString, value)
		_node.Handle = &value
	}
	if value, ok := ccc.mutation.DeepLink(); ok {
		_spec.SetField(channelconnection.FieldDeepLink, field.TypeString, value)
		_node.DeepLink = &value
	}
	if value, ok := ccc.mutation.ConnectedAt(); ok {
		_spec.SetField(channelconnection.FieldConnectedAt, field.TypeTime, value)
		_node.ConnectedAt = &value
	}
	if nodes := ccc.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   channelconnection.AgentTable,
			Columns: []string{channelconnection.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AgentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChannelConnectionCreateBulk is the builder for creating many ChannelConnection entities in bulk.
type ChannelConnectionCreateBulk struct {
	config
	err      error
	builders []*ChannelConnectionCreate
}

// Save creates the ChannelConnection entities in the database.
func (cccb *ChannelConnectionCreateBulk) Save(ctx context.Context) ([]*ChannelConnection, error) {
	if cccb.err != nil {
		return nil, cccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cccb.builders))
	nodes := make([]*ChannelConnection, len(cccb.builders))
	mutators := make([]Mutator, len(cccb.builders))
	for i := range cccb.builders {
		func(i int, root context.Context) {
			builder := cccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChannelConnectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cccb *ChannelConnectionCreateBulk) SaveX(ctx context.Context) []*ChannelConnection {
	v, err := cccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cccb *ChannelConnectionCreateBulk) Exec(ctx context.Context) error {
	_, err := cccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cccb *ChannelConnectionCreateBulk) ExecX(ctx context.Context) {
	if err := cccb.Exec(ctx); err != nil {
		panic(err)
	}
}
