// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/conversation"
	"backend/ent/conversationmessage"
	"backend/ent/conversationparticipant"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConversationCreate is the builder for creating a Conversation entity.
type ConversationCreate struct {
	config
	mutation *ConversationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (cc *ConversationCreate) SetCreatedAt(t time.Time) *ConversationCreate {
	cc.mutation.SetCreatedAt(t)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableCreatedAt(t *time.Time) *ConversationCreate {
	if t != nil {
		cc.SetCreatedAt(*t)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *ConversationCreate) SetUpdatedAt(t time.Time) *ConversationCreate {
	cc.mutation.SetUpdatedAt(t)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableUpdatedAt(t *time.Time) *ConversationCreate {
	if t != nil {
		cc.SetUpdatedAt(*t)
	}
	return cc
}

// SetType sets the "type" field.
func (cc *ConversationCreate) SetType(s string) *ConversationCreate {
	cc.mutation.SetType(s)
	return cc
}

// SetNillableType sets the "type" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableType(s *string) *ConversationCreate {
	if s != nil {
		cc.SetType(*s)
	}
	return cc
}

// SetTitle sets the "title" field.
func (cc *ConversationCreate) SetTitle(s string) *ConversationCreate {
	cc.mutation.SetTitle(s)
	return cc
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableTitle(s *string) *ConversationCreate {
	if s != nil {
		cc.SetTitle(*s)
	}
	return cc
}

// SetCreatorAgentID sets the "creator_agent_id" field.
func (cc *ConversationCreate) SetCreatorAgentID(u uuid.UUID) *ConversationCreate {
	cc.mutation.SetCreatorAgentID(u)
	return cc
}

// SetParticipantCount sets the "participant_count" field.
func (cc *ConversationCreate) SetParticipantCount(i int) *ConversationCreate {
	cc.mutation.SetParticipantCount(i)
	return cc
}

// SetNillableParticipantCount sets the "participant_count" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableParticipantCount(i *int) *ConversationCreate {
	if i != nil {
		cc.SetParticipantCount(*i)
	}
	return cc
}

// SetMessageCount sets the "message_count" field.
func (cc *ConversationCreate) SetMessageCount(i int) *ConversationCreate {
	cc.mutation.SetMessageCount(i)
	return cc
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableMessageCount(i *int) *ConversationCreate {
	if i != nil {
		cc.SetMessageCount(*i)
	}
	return cc
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (cc *ConversationCreate) SetLastMessagePreview(s string) *ConversationCreate {
	cc.mutation.SetLastMessagePreview(s)
	return cc
}

// SetNillableLastMessagePreview sets the "last_message_preview" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableLastMessagePreview(s *string) *ConversationCreate {
	if s != nil {
		cc.SetLastMessagePreview(*s)
	}
	return cc
}

// SetLastMessageAt sets the "last_message_at" field.
func (cc *ConversationCreate) SetLastMessageAt(t time.Time) *ConversationCreate {
	cc.mutation.SetLastMessageAt(t)
	return cc
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableLastMessageAt(t *time.Time) *ConversationCreate {
	if t != nil {
		cc.SetLastMessageAt(*t)
	}
	return cc
}

// SetChatType sets the "chat_type" field.
func (cc *ConversationCreate) SetChatType(s string) *ConversationCreate {
	cc.mutation.SetChatType(s)
	return cc
}

// SetNillableChatType sets the "chat_type" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableChatType(s *string) *ConversationCreate {
	if s != nil {
		cc.SetChatType(*s)
	}
	return cc
}

// SetStatus sets the "status" field.
func (cc *ConversationCreate) SetStatus(s string) *ConversationCreate {
	cc.mutation.SetStatus(s)
	return cc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableStatus(s *string) *ConversationCreate {
	if s != nil {
		cc.SetStatus(*s)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *ConversationCreate) SetID(u uuid.UUID) *ConversationCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cc *ConversationCreate) SetNillableID(u *uuid.UUID) *ConversationCreate {
	if u != nil {
		cc.SetID(*u)
	}
	return cc
}

// SetCreatorAgent sets the "creator_agent" edge to the Agent entity.
func (cc *ConversationCreate) SetCreatorAgent(a *Agent) *ConversationCreate {
	return cc.SetCreatorAgentID(a.ID)
}

// AddParticipantIDs adds the "participants" edge to the ConversationParticipant entity by IDs.
func (cc *ConversationCreate) AddParticipantIDs(ids ...uuid.UUID) *ConversationCreate {
	cc.mutation.AddParticipantIDs(ids...)
	return cc
}

// AddParticipants adds the "participants" edges to the ConversationParticipant entity.
func (cc *ConversationCreate) AddParticipants(c ...*ConversationParticipant) *ConversationCreate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cc.AddParticipantIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the ConversationMessage entity by IDs.
func (cc *ConversationCreate) AddMessageIDs(ids ...uuid.UUID) *ConversationCreate {
	cc.mutation.AddMessageIDs(ids...)
	return cc
}

// AddMessages adds the "messages" edges to the ConversationMessage entity.
func (cc *ConversationCreate) AddMessages(c ...*ConversationMessage) *ConversationCreate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cc.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (cc *ConversationCreate) Mutation() *ConversationMutation {
	return cc.mutation
}

// Save creates the Conversation in the database.
func (cc *ConversationCreate) Save(ctx context.Context) (*Conversation, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ConversationCreate) SaveX(ctx context.Context) *Conversation {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ConversationCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ConversationCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ConversationCreate) defaults() {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := conversation.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := conversation.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cc.mutation.GetType(); !ok {
		v := conversation.DefaultType
		cc.mutation.SetType(v)
	}
	if _, ok := cc.mutation.ParticipantCount(); !ok {
		v := conversation.DefaultParticipantCount
		cc.mutation.SetParticipantCount(v)
	}
	if _, ok := cc.mutation.MessageCount(); !ok {
		v := conversation.DefaultMessageCount
		cc.mutation.SetMessageCount(v)
	}
	if _, ok := cc.mutation.ChatType(); !ok {
		v := conversation.DefaultChatType
		cc.mutation.SetChatType(v)
	}
	if _, ok := cc.mutation.Status(); !ok {
		v := conversation.DefaultStatus
		cc.mutation.SetStatus(v)
	}
	if _, ok := cc.mutation.ID(); !ok {
		v := conversation.DefaultID()
		cc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ConversationCreate) check() error {
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Conversation.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Conversation.updated_at"`)}
	}
	if _, ok := cc.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Conversation.type"`)}
	}
	if _, ok := cc.mutation.CreatorAgentID(); !ok {
		return &ValidationError{Name: "creator_agent_id", err: errors.New(`ent: missing required field "Conversation.creator_agent_id"`)}
	}
	if _, ok := cc.mutation.ParticipantCount(); !ok {
		return &ValidationError{Name: "participant_count", err: errors.New(`ent: missing required field "Conversation.participant_count"`)}
	}
	if _, ok := cc.mutation.MessageCount(); !ok {
		return &ValidationError{Name: "message_count", err: errors.New(`ent: missing required field "Conversation.message_count"`)}
	}
	if _, ok := cc.mutation.ChatType(); !ok {
		return &ValidationError{Name: "chat_type", err: errors.New(`ent: missing required field "Conversation.chat_type"`)}
	}
	if _, ok := cc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Conversation.status"`)}
	}
	if len(cc.mutation.CreatorAgentIDs()) == 0 {
		return &ValidationError{Name: "creator_agent", err: errors.New(`ent: missing required edge "Conversation.creator_agent"`)}
	}
	return nil
}

func (cc *ConversationCreate) sqlSave(ctx context.Context) (*Conversation, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ConversationCreate) createSpec() (*Conversation, *sqlgraph.CreateSpec) {
	var (
		_node = &Conversation{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(conversation.Table, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(conversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := cc.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := cc.mutation.Title(); ok {
		_spec.SetField(conversation.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := cc.mutation.ParticipantCount(); ok {
		_spec.SetField(conversation.FieldParticipantCount, field.TypeInt, value)
		_node.ParticipantCount = value
	}
	if value, ok := cc.mutation.MessageCount(); ok {
		_spec.SetField(conversation.FieldMessageCount, field.TypeInt, value)
		_node.MessageCount = value
	}
	if value, ok := cc.mutation.LastMessagePreview(); ok {
		_spec.SetField(conversation.FieldLastMessagePreview, field.TypeString, value)
		_node.LastMessagePreview = &value
	}
	if value, ok := cc.mutation.LastMessageAt(); ok {
		_spec.SetField(conversation.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	if value, ok := cc.mutation.ChatType(); ok {
		_spec.SetField(conversation.FieldChatType, field.TypeString, value)
		_node.ChatType = value
	}
	if value, ok := cc.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := cc.mutation.CreatorAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.CreatorAgentTable,
			Columns: []string{conversation.CreatorAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatorAgentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ParticipantsTable,
			Columns: []string{conversation.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConversationCreateBulk is the builder for creating many Conversation entities in bulk.
type ConversationCreateBulk struct {
	config
	err      error
	builders []*ConversationCreate
}

// Save creates the Conversation entities in the database.
func (ccb *ConversationCreateBulk) Save(ctx context.Context) ([]*Conversation, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Conversation, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ConversationCreateBulk) SaveX(ctx context.Context) []*Conversation {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ConversationCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
