// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/conversation"
	"backend/ent/conversationmessage"
	"backend/ent/conversationparticipant"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConversationCreate is the builder for creating a Conversation entity.
type ConversationCreate struct {
	config
	mutation *ConversationMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ConversationCreate) SetCreatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableCreatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ConversationCreate) SetUpdatedAt(v time.Time) *ConversationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableUpdatedAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ConversationCreate) SetType(v string) *ConversationCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableType(v *string) *ConversationCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetTitle sets the "title" field.
func (_c *ConversationCreate) SetTitle(v string) *ConversationCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableTitle(v *string) *ConversationCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetCreatorAgentID sets the "creator_agent_id" field.
func (_c *ConversationCreate) SetCreatorAgentID(v uuid.UUID) *ConversationCreate {
	_c.mutation.SetCreatorAgentID(v)
	return _c
}

// SetParticipantCount sets the "participant_count" field.
func (_c *ConversationCreate) SetParticipantCount(v int) *ConversationCreate {
	_c.mutation.SetParticipantCount(v)
	return _c
}

// SetNillableParticipantCount sets the "participant_count" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableParticipantCount(v *int) *ConversationCreate {
	if v != nil {
		_c.SetParticipantCount(*v)
	}
	return _c
}

// SetMessageCount sets the "message_count" field.
func (_c *ConversationCreate) SetMessageCount(v int) *ConversationCreate {
	_c.mutation.SetMessageCount(v)
	return _c
}

// SetNillableMessageCount sets the "message_count" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableMessageCount(v *int) *ConversationCreate {
	if v != nil {
		_c.SetMessageCount(*v)
	}
	return _c
}

// SetLastMessagePreview sets the "last_message_preview" field.
func (_c *ConversationCreate) SetLastMessagePreview(v string) *ConversationCreate {
	_c.mutation.SetLastMessagePreview(v)
	return _c
}

// SetNillableLastMessagePreview sets the "last_message_preview" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableLastMessagePreview(v *string) *ConversationCreate {
	if v != nil {
		_c.SetLastMessagePreview(*v)
	}
	return _c
}

// SetLastMessageAt sets the "last_message_at" field.
func (_c *ConversationCreate) SetLastMessageAt(v time.Time) *ConversationCreate {
	_c.mutation.SetLastMessageAt(v)
	return _c
}

// SetNillableLastMessageAt sets the "last_message_at" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableLastMessageAt(v *time.Time) *ConversationCreate {
	if v != nil {
		_c.SetLastMessageAt(*v)
	}
	return _c
}

// SetChatType sets the "chat_type" field.
func (_c *ConversationCreate) SetChatType(v string) *ConversationCreate {
	_c.mutation.SetChatType(v)
	return _c
}

// SetNillableChatType sets the "chat_type" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableChatType(v *string) *ConversationCreate {
	if v != nil {
		_c.SetChatType(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *ConversationCreate) SetStatus(v string) *ConversationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableStatus(v *string) *ConversationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ConversationCreate) SetID(v uuid.UUID) *ConversationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ConversationCreate) SetNillableID(v *uuid.UUID) *ConversationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetCreatorAgent sets the "creator_agent" edge to the Agent entity.
func (_c *ConversationCreate) SetCreatorAgent(v *Agent) *ConversationCreate {
	return _c.SetCreatorAgentID(v.ID)
}

// AddParticipantIDs adds the "participants" edge to the ConversationParticipant entity by IDs.
func (_c *ConversationCreate) AddParticipantIDs(ids ...uuid.UUID) *ConversationCreate {
	_c.mutation.AddParticipantIDs(ids...)
	return _c
}

// AddParticipants adds the "participants" edges to the ConversationParticipant entity.
func (_c *ConversationCreate) AddParticipants(v ...*ConversationParticipant) *ConversationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddParticipantIDs(ids...)
}

// AddMessageIDs adds the "messages" edge to the ConversationMessage entity by IDs.
func (_c *ConversationCreate) AddMessageIDs(ids ...uuid.UUID) *ConversationCreate {
	_c.mutation.AddMessageIDs(ids...)
	return _c
}

// AddMessages adds the "messages" edges to the ConversationMessage entity.
func (_c *ConversationCreate) AddMessages(v ...*ConversationMessage) *ConversationCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddMessageIDs(ids...)
}

// Mutation returns the ConversationMutation object of the builder.
func (_c *ConversationCreate) Mutation() *ConversationMutation {
	return _c.mutation
}

// Save creates the Conversation in the database.
func (_c *ConversationCreate) Save(ctx context.Context) (*Conversation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ConversationCreate) SaveX(ctx context.Context) *Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ConversationCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := conversation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := conversation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.GetType(); !ok {
		v := conversation.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.ParticipantCount(); !ok {
		v := conversation.DefaultParticipantCount
		_c.mutation.SetParticipantCount(v)
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		v := conversation.DefaultMessageCount
		_c.mutation.SetMessageCount(v)
	}
	if _, ok := _c.mutation.ChatType(); !ok {
		v := conversation.DefaultChatType
		_c.mutation.SetChatType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := conversation.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := conversation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ConversationCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Conversation.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Conversation.updated_at"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Conversation.type"`)}
	}
	if _, ok := _c.mutation.CreatorAgentID(); !ok {
		return &ValidationError{Name: "creator_agent_id", err: errors.New(`ent: missing required field "Conversation.creator_agent_id"`)}
	}
	if _, ok := _c.mutation.ParticipantCount(); !ok {
		return &ValidationError{Name: "participant_count", err: errors.New(`ent: missing required field "Conversation.participant_count"`)}
	}
	if _, ok := _c.mutation.MessageCount(); !ok {
		return &ValidationError{Name: "message_count", err: errors.New(`ent: missing required field "Conversation.message_count"`)}
	}
	if _, ok := _c.mutation.ChatType(); !ok {
		return &ValidationError{Name: "chat_type", err: errors.New(`ent: missing required field "Conversation.chat_type"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Conversation.status"`)}
	}
	if len(_c.mutation.CreatorAgentIDs()) == 0 {
		return &ValidationError{Name: "creator_agent", err: errors.New(`ent: missing required edge "Conversation.creator_agent"`)}
	}
	return nil
}

func (_c *ConversationCreate) sqlSave(ctx context.Context) (*Conversation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ConversationCreate) createSpec() (*Conversation, *sqlgraph.CreateSpec) {
	var (
		_node = &Conversation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(conversation.Table, sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(conversation.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(conversation.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(conversation.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(conversation.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.ParticipantCount(); ok {
		_spec.SetField(conversation.FieldParticipantCount, field.TypeInt, value)
		_node.ParticipantCount = value
	}
	if value, ok := _c.mutation.MessageCount(); ok {
		_spec.SetField(conversation.FieldMessageCount, field.TypeInt, value)
		_node.MessageCount = value
	}
	if value, ok := _c.mutation.LastMessagePreview(); ok {
		_spec.SetField(conversation.FieldLastMessagePreview, field.TypeString, value)
		_node.LastMessagePreview = &value
	}
	if value, ok := _c.mutation.LastMessageAt(); ok {
		_spec.SetField(conversation.FieldLastMessageAt, field.TypeTime, value)
		_node.LastMessageAt = &value
	}
	if value, ok := _c.mutation.ChatType(); ok {
		_spec.SetField(conversation.FieldChatType, field.TypeString, value)
		_node.ChatType = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(conversation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if nodes := _c.mutation.CreatorAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversation.CreatorAgentTable,
			Columns: []string{conversation.CreatorAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CreatorAgentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ParticipantsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.ParticipantsTable,
			Columns: []string{conversation.ParticipantsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationparticipant.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   conversation.MessagesTable,
			Columns: []string{conversation.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ConversationCreateBulk is the builder for creating many Conversation entities in bulk.
type ConversationCreateBulk struct {
	config
	err      error
	builders []*ConversationCreate
}

// Save creates the Conversation entities in the database.
func (_c *ConversationCreateBulk) Save(ctx context.Context) ([]*Conversation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Conversation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ConversationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ConversationCreateBulk) SaveX(ctx context.Context) []*Conversation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ConversationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ConversationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
