// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/conversation"
	"backend/ent/conversationmessage"
	"backend/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ConversationMessageUpdate is the builder for updating ConversationMessage entities.
type ConversationMessageUpdate struct {
	config
	hooks    []Hook
	mutation *ConversationMessageMutation
}

// Where appends a list predicates to the ConversationMessageUpdate builder.
func (_u *ConversationMessageUpdate) Where(ps ...predicate.ConversationMessage) *ConversationMessageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConversationID sets the "conversation_id" field.
func (_u *ConversationMessageUpdate) SetConversationID(v uuid.UUID) *ConversationMessageUpdate {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableConversationID(v *uuid.UUID) *ConversationMessageUpdate {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetSenderAgentID sets the "sender_agent_id" field.
func (_u *ConversationMessageUpdate) SetSenderAgentID(v uuid.UUID) *ConversationMessageUpdate {
	_u.mutation.SetSenderAgentID(v)
	return _u
}

// SetNillableSenderAgentID sets the "sender_agent_id" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableSenderAgentID(v *uuid.UUID) *ConversationMessageUpdate {
	if v != nil {
		_u.SetSenderAgentID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ConversationMessageUpdate) SetContent(v string) *ConversationMessageUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableContent(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *ConversationMessageUpdate) SetMessageType(v string) *ConversationMessageUpdate {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableMessageType(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetInteractionType sets the "interaction_type" field.
func (_u *ConversationMessageUpdate) SetInteractionType(v string) *ConversationMessageUpdate {
	_u.mutation.SetInteractionType(v)
	return _u
}

// SetNillableInteractionType sets the "interaction_type" field if the given value is not nil.
func (_u *ConversationMessageUpdate) SetNillableInteractionType(v *string) *ConversationMessageUpdate {
	if v != nil {
		_u.SetInteractionType(*v)
	}
	return _u
}

// ClearInteractionType clears the value of the "interaction_type" field.
func (_u *ConversationMessageUpdate) ClearInteractionType() *ConversationMessageUpdate {
	_u.mutation.ClearInteractionType()
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdate) SetConversation(v *Conversation) *ConversationMessageUpdate {
	return _u.SetConversationID(v.ID)
}

// SetSenderAgent sets the "sender_agent" edge to the Agent entity.
func (_u *ConversationMessageUpdate) SetSenderAgent(v *Agent) *ConversationMessageUpdate {
	return _u.SetSenderAgentID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_u *ConversationMessageUpdate) Mutation() *ConversationMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdate) ClearConversation() *ConversationMessageUpdate {
	_u.mutation.ClearConversation()
	return _u
}

// ClearSenderAgent clears the "sender_agent" edge to the Agent entity.
func (_u *ConversationMessageUpdate) ClearSenderAgent() *ConversationMessageUpdate {
	_u.mutation.ClearSenderAgent()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ConversationMessageUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationMessageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ConversationMessageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationMessageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationMessageUpdate) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := conversationmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.content": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.conversation"`)
	}
	if _u.mutation.SenderAgentCleared() && len(_u.mutation.SenderAgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.sender_agent"`)
	}
	return nil
}

func (_u *ConversationMessageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationmessage.Table, conversationmessage.Columns, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(conversationmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.InteractionType(); ok {
		_spec.SetField(conversationmessage.FieldInteractionType, field.TypeString, value)
	}
	if _u.mutation.InteractionTypeCleared() {
		_spec.ClearField(conversationmessage.FieldInteractionType, field.TypeString)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderAgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderAgentTable,
			Columns: []string{conversationmessage.SenderAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderAgentTable,
			Columns: []string{conversationmessage.SenderAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ConversationMessageUpdateOne is the builder for updating a single ConversationMessage entity.
type ConversationMessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ConversationMessageMutation
}

// SetConversationID sets the "conversation_id" field.
func (_u *ConversationMessageUpdateOne) SetConversationID(v uuid.UUID) *ConversationMessageUpdateOne {
	_u.mutation.SetConversationID(v)
	return _u
}

// SetNillableConversationID sets the "conversation_id" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableConversationID(v *uuid.UUID) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetConversationID(*v)
	}
	return _u
}

// SetSenderAgentID sets the "sender_agent_id" field.
func (_u *ConversationMessageUpdateOne) SetSenderAgentID(v uuid.UUID) *ConversationMessageUpdateOne {
	_u.mutation.SetSenderAgentID(v)
	return _u
}

// SetNillableSenderAgentID sets the "sender_agent_id" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableSenderAgentID(v *uuid.UUID) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetSenderAgentID(*v)
	}
	return _u
}

// SetContent sets the "content" field.
func (_u *ConversationMessageUpdateOne) SetContent(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableContent(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetMessageType sets the "message_type" field.
func (_u *ConversationMessageUpdateOne) SetMessageType(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetMessageType(v)
	return _u
}

// SetNillableMessageType sets the "message_type" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableMessageType(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetMessageType(*v)
	}
	return _u
}

// SetInteractionType sets the "interaction_type" field.
func (_u *ConversationMessageUpdateOne) SetInteractionType(v string) *ConversationMessageUpdateOne {
	_u.mutation.SetInteractionType(v)
	return _u
}

// SetNillableInteractionType sets the "interaction_type" field if the given value is not nil.
func (_u *ConversationMessageUpdateOne) SetNillableInteractionType(v *string) *ConversationMessageUpdateOne {
	if v != nil {
		_u.SetInteractionType(*v)
	}
	return _u
}

// ClearInteractionType clears the value of the "interaction_type" field.
func (_u *ConversationMessageUpdateOne) ClearInteractionType() *ConversationMessageUpdateOne {
	_u.mutation.ClearInteractionType()
	return _u
}

// SetConversation sets the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdateOne) SetConversation(v *Conversation) *ConversationMessageUpdateOne {
	return _u.SetConversationID(v.ID)
}

// SetSenderAgent sets the "sender_agent" edge to the Agent entity.
func (_u *ConversationMessageUpdateOne) SetSenderAgent(v *Agent) *ConversationMessageUpdateOne {
	return _u.SetSenderAgentID(v.ID)
}

// Mutation returns the ConversationMessageMutation object of the builder.
func (_u *ConversationMessageUpdateOne) Mutation() *ConversationMessageMutation {
	return _u.mutation
}

// ClearConversation clears the "conversation" edge to the Conversation entity.
func (_u *ConversationMessageUpdateOne) ClearConversation() *ConversationMessageUpdateOne {
	_u.mutation.ClearConversation()
	return _u
}

// ClearSenderAgent clears the "sender_agent" edge to the Agent entity.
func (_u *ConversationMessageUpdateOne) ClearSenderAgent() *ConversationMessageUpdateOne {
	_u.mutation.ClearSenderAgent()
	return _u
}

// Where appends a list predicates to the ConversationMessageUpdate builder.
func (_u *ConversationMessageUpdateOne) Where(ps ...predicate.ConversationMessage) *ConversationMessageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ConversationMessageUpdateOne) Select(field string, fields ...string) *ConversationMessageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ConversationMessage entity.
func (_u *ConversationMessageUpdateOne) Save(ctx context.Context) (*ConversationMessage, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ConversationMessageUpdateOne) SaveX(ctx context.Context) *ConversationMessage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ConversationMessageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ConversationMessageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ConversationMessageUpdateOne) check() error {
	if v, ok := _u.mutation.Content(); ok {
		if err := conversationmessage.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "ConversationMessage.content": %w`, err)}
		}
	}
	if _u.mutation.ConversationCleared() && len(_u.mutation.ConversationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.conversation"`)
	}
	if _u.mutation.SenderAgentCleared() && len(_u.mutation.SenderAgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "ConversationMessage.sender_agent"`)
	}
	return nil
}

func (_u *ConversationMessageUpdateOne) sqlSave(ctx context.Context) (_node *ConversationMessage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(conversationmessage.Table, conversationmessage.Columns, sqlgraph.NewFieldSpec(conversationmessage.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ConversationMessage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, conversationmessage.FieldID)
		for _, f := range fields {
			if !conversationmessage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != conversationmessage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(conversationmessage.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.MessageType(); ok {
		_spec.SetField(conversationmessage.FieldMessageType, field.TypeString, value)
	}
	if value, ok := _u.mutation.InteractionType(); ok {
		_spec.SetField(conversationmessage.FieldInteractionType, field.TypeString, value)
	}
	if _u.mutation.InteractionTypeCleared() {
		_spec.ClearField(conversationmessage.FieldInteractionType, field.TypeString)
	}
	if _u.mutation.ConversationCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConversationIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.ConversationTable,
			Columns: []string{conversationmessage.ConversationColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(conversation.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SenderAgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderAgentTable,
			Columns: []string{conversationmessage.SenderAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SenderAgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   conversationmessage.SenderAgentTable,
			Columns: []string{conversationmessage.SenderAgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ConversationMessage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{conversationmessage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
