// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/memorial"
	"backend/ent/tribute"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MemorialCreate is the builder for creating a Memorial entity.
type MemorialCreate struct {
	config
	mutation *MemorialMutation
	hooks    []Hook
}

// SetAgentID sets the "agent_id" field.
func (_c *MemorialCreate) SetAgentID(v uuid.UUID) *MemorialCreate {
	_c.mutation.SetAgentID(v)
	return _c
}

// SetAgentName sets the "agent_name" field.
func (_c *MemorialCreate) SetAgentName(v string) *MemorialCreate {
	_c.mutation.SetAgentName(v)
	return _c
}

// SetAgentAvatar sets the "agent_avatar" field.
func (_c *MemorialCreate) SetAgentAvatar(v string) *MemorialCreate {
	_c.mutation.SetAgentAvatar(v)
	return _c
}

// SetNillableAgentAvatar sets the "agent_avatar" field if the given value is not nil.
func (_c *MemorialCreate) SetNillableAgentAvatar(v *string) *MemorialCreate {
	if v != nil {
		_c.SetAgentAvatar(*v)
	}
	return _c
}

// SetBornAt sets the "born_at" field.
func (_c *MemorialCreate) SetBornAt(v time.Time) *MemorialCreate {
	_c.mutation.SetBornAt(v)
	return _c
}

// SetDiedAt sets the "died_at" field.
func (_c *MemorialCreate) SetDiedAt(v time.Time) *MemorialCreate {
	_c.mutation.SetDiedAt(v)
	return _c
}

// SetLifespanHours sets the "lifespan_hours" field.
func (_c *MemorialCreate) SetLifespanHours(v int64) *MemorialCreate {
	_c.mutation.SetLifespanHours(v)
	return _c
}

// SetNillableLifespanHours sets the "lifespan_hours" field if the given value is not nil.
func (_c *MemorialCreate) SetNillableLifespanHours(v *int64) *MemorialCreate {
	if v != nil {
		_c.SetLifespanHours(*v)
	}
	return _c
}

// SetLastWords sets the "last_words" field.
func (_c *MemorialCreate) SetLastWords(v string) *MemorialCreate {
	_c.mutation.SetLastWords(v)
	return _c
}

// SetNillableLastWords sets the "last_words" field if the given value is not nil.
func (_c *MemorialCreate) SetNillableLastWords(v *string) *MemorialCreate {
	if v != nil {
		_c.SetLastWords(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *MemorialCreate) SetCreatedAt(v time.Time) *MemorialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *MemorialCreate) SetNillableCreatedAt(v *time.Time) *MemorialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *MemorialCreate) SetID(v uuid.UUID) *MemorialCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *MemorialCreate) SetNillableID(v *uuid.UUID) *MemorialCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAgent sets the "agent" edge to the Agent entity.
func (_c *MemorialCreate) SetAgent(v *Agent) *MemorialCreate {
	return _c.SetAgentID(v.ID)
}

// AddTributeIDs adds the "tributes" edge to the Tribute entity by IDs.
func (_c *MemorialCreate) AddTributeIDs(ids ...uuid.UUID) *MemorialCreate {
	_c.mutation.AddTributeIDs(ids...)
	return _c
}

// AddTributes adds the "tributes" edges to the Tribute entity.
func (_c *MemorialCreate) AddTributes(v ...*Tribute) *MemorialCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddTributeIDs(ids...)
}

// Mutation returns the MemorialMutation object of the builder.
func (_c *MemorialCreate) Mutation() *MemorialMutation {
	return _c.mutation
}

// Save creates the Memorial in the database.
func (_c *MemorialCreate) Save(ctx context.Context) (*Memorial, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MemorialCreate) SaveX(ctx context.Context) *Memorial {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemorialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemorialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *MemorialCreate) defaults() {
	if _, ok := _c.mutation.LifespanHours(); !ok {
		v := memorial.DefaultLifespanHours
		_c.mutation.SetLifespanHours(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := memorial.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := memorial.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MemorialCreate) check() error {
	if _, ok := _c.mutation.AgentID(); !ok {
		return &ValidationError{Name: "agent_id", err: errors.New(`ent: missing required field "Memorial.agent_id"`)}
	}
	if _, ok := _c.mutation.AgentName(); !ok {
		return &ValidationError{Name: "agent_name", err: errors.New(`ent: missing required field "Memorial.agent_name"`)}
	}
	if v, ok := _c.mutation.AgentName(); ok {
		if err := memorial.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "Memorial.agent_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BornAt(); !ok {
		return &ValidationError{Name: "born_at", err: errors.New(`ent: missing required field "Memorial.born_at"`)}
	}
	if _, ok := _c.mutation.DiedAt(); !ok {
		return &ValidationError{Name: "died_at", err: errors.New(`ent: missing required field "Memorial.died_at"`)}
	}
	if _, ok := _c.mutation.LifespanHours(); !ok {
		return &ValidationError{Name: "lifespan_hours", err: errors.New(`ent: missing required field "Memorial.lifespan_hours"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Memorial.created_at"`)}
	}
	if len(_c.mutation.AgentIDs()) == 0 {
		return &ValidationError{Name: "agent", err: errors.New(`ent: missing required edge "Memorial.agent"`)}
	}
	return nil
}

func (_c *MemorialCreate) sqlSave(ctx context.Context) (*Memorial, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MemorialCreate) createSpec() (*Memorial, *sqlgraph.CreateSpec) {
	var (
		_node = &Memorial{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(memorial.Table, sqlgraph.NewFieldSpec(memorial.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AgentName(); ok {
		_spec.SetField(memorial.FieldAgentName, field.TypeString, value)
		_node.AgentName = value
	}
	if value, ok := _c.mutation.AgentAvatar(); ok {
		_spec.SetField(memorial.FieldAgentAvatar, field.TypeString, value)
		_node.AgentAvatar = &value
	}
	if value, ok := _c.mutation.BornAt(); ok {
		_spec.SetField(memorial.FieldBornAt, field.TypeTime, value)
		_node.BornAt = value
	}
	if value, ok := _c.mutation.DiedAt(); ok {
		_spec.SetField(memorial.FieldDiedAt, field.TypeTime, value)
		_node.DiedAt = value
	}
	if value, ok := _c.mutation.LifespanHours(); ok {
		_spec.SetField(memorial.FieldLifespanHours, field.TypeInt64, value)
		_node.LifespanHours = value
	}
	if value, ok := _c.mutation.LastWords(); ok {
		_spec.SetField(memorial.FieldLastWords, field.TypeString, value)
		_node.LastWords = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(memorial.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   memorial.AgentTable,
			Columns: []string{memorial.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AgentID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.TributesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorial.TributesTable,
			Columns: []string{memorial.TributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tribute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MemorialCreateBulk is the builder for creating many Memorial entities in bulk.
type MemorialCreateBulk struct {
	config
	err      error
	builders []*MemorialCreate
}

// Save creates the Memorial entities in the database.
func (_c *MemorialCreateBulk) Save(ctx context.Context) ([]*Memorial, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Memorial, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MemorialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MemorialCreateBulk) SaveX(ctx context.Context) []*Memorial {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MemorialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MemorialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
