// Code generated by ent, DO NOT EDIT.

package ent

import (
	"backend/ent/agent"
	"backend/ent/memorial"
	"backend/ent/predicate"
	"backend/ent/tribute"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// MemorialUpdate is the builder for updating Memorial entities.
type MemorialUpdate struct {
	config
	hooks    []Hook
	mutation *MemorialMutation
}

// Where appends a list predicates to the MemorialUpdate builder.
func (mu *MemorialUpdate) Where(ps ...predicate.Memorial) *MemorialUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetAgentID sets the "agent_id" field.
func (mu *MemorialUpdate) SetAgentID(u uuid.UUID) *MemorialUpdate {
	mu.mutation.SetAgentID(u)
	return mu
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (mu *MemorialUpdate) SetNillableAgentID(u *uuid.UUID) *MemorialUpdate {
	if u != nil {
		mu.SetAgentID(*u)
	}
	return mu
}

// SetAgentName sets the "agent_name" field.
func (mu *MemorialUpdate) SetAgentName(s string) *MemorialUpdate {
	mu.mutation.SetAgentName(s)
	return mu
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (mu *MemorialUpdate) SetNillableAgentName(s *string) *MemorialUpdate {
	if s != nil {
		mu.SetAgentName(*s)
	}
	return mu
}

// SetAgentAvatar sets the "agent_avatar" field.
func (mu *MemorialUpdate) SetAgentAvatar(s string) *MemorialUpdate {
	mu.mutation.SetAgentAvatar(s)
	return mu
}

// SetNillableAgentAvatar sets the "agent_avatar" field if the given value is not nil.
func (mu *MemorialUpdate) SetNillableAgentAvatar(s *string) *MemorialUpdate {
	if s != nil {
		mu.SetAgentAvatar(*s)
	}
	return mu
}

// ClearAgentAvatar clears the value of the "agent_avatar" field.
func (mu *MemorialUpdate) ClearAgentAvatar() *MemorialUpdate {
	mu.mutation.ClearAgentAvatar()
	return mu
}

// SetBornAt sets the "born_at" field.
func (mu *MemorialUpdate) SetBornAt(t time.Time) *MemorialUpdate {
	mu.mutation.SetBornAt(t)
	return mu
}

// SetNillableBornAt sets the "born_at" field if the given value is not nil.
func (mu *MemorialUpdate) SetNillableBornAt(t *time.Time) *MemorialUpdate {
	if t != nil {
		mu.SetBornAt(*t)
	}
	return mu
}

// SetDiedAt sets the "died_at" field.
func (mu *MemorialUpdate) SetDiedAt(t time.Time) *MemorialUpdate {
	mu.mutation.SetDiedAt(t)
	return mu
}

// SetNillableDiedAt sets the "died_at" field if the given value is not nil.
func (mu *MemorialUpdate) SetNillableDiedAt(t *time.Time) *MemorialUpdate {
	if t != nil {
		mu.SetDiedAt(*t)
	}
	return mu
}

// SetLifespanHours sets the "lifespan_hours" field.
func (mu *MemorialUpdate) SetLifespanHours(i int64) *MemorialUpdate {
	mu.mutation.ResetLifespanHours()
	mu.mutation.SetLifespanHours(i)
	return mu
}

// SetNillableLifespanHours sets the "lifespan_hours" field if the given value is not nil.
func (mu *MemorialUpdate) SetNillableLifespanHours(i *int64) *MemorialUpdate {
	if i != nil {
		mu.SetLifespanHours(*i)
	}
	return mu
}

// AddLifespanHours adds i to the "lifespan_hours" field.
func (mu *MemorialUpdate) AddLifespanHours(i int64) *MemorialUpdate {
	mu.mutation.AddLifespanHours(i)
	return mu
}

// SetLastWords sets the "last_words" field.
func (mu *MemorialUpdate) SetLastWords(s string) *MemorialUpdate {
	mu.mutation.SetLastWords(s)
	return mu
}

// SetNillableLastWords sets the "last_words" field if the given value is not nil.
func (mu *MemorialUpdate) SetNillableLastWords(s *string) *MemorialUpdate {
	if s != nil {
		mu.SetLastWords(*s)
	}
	return mu
}

// ClearLastWords clears the value of the "last_words" field.
func (mu *MemorialUpdate) ClearLastWords() *MemorialUpdate {
	mu.mutation.ClearLastWords()
	return mu
}

// SetAgent sets the "agent" edge to the Agent entity.
func (mu *MemorialUpdate) SetAgent(a *Agent) *MemorialUpdate {
	return mu.SetAgentID(a.ID)
}

// AddTributeIDs adds the "tributes" edge to the Tribute entity by IDs.
func (mu *MemorialUpdate) AddTributeIDs(ids ...uuid.UUID) *MemorialUpdate {
	mu.mutation.AddTributeIDs(ids...)
	return mu
}

// AddTributes adds the "tributes" edges to the Tribute entity.
func (mu *MemorialUpdate) AddTributes(t ...*Tribute) *MemorialUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return mu.AddTributeIDs(ids...)
}

// Mutation returns the MemorialMutation object of the builder.
func (mu *MemorialUpdate) Mutation() *MemorialMutation {
	return mu.mutation
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (mu *MemorialUpdate) ClearAgent() *MemorialUpdate {
	mu.mutation.ClearAgent()
	return mu
}

// ClearTributes clears all "tributes" edges to the Tribute entity.
func (mu *MemorialUpdate) ClearTributes() *MemorialUpdate {
	mu.mutation.ClearTributes()
	return mu
}

// RemoveTributeIDs removes the "tributes" edge to Tribute entities by IDs.
func (mu *MemorialUpdate) RemoveTributeIDs(ids ...uuid.UUID) *MemorialUpdate {
	mu.mutation.RemoveTributeIDs(ids...)
	return mu
}

// RemoveTributes removes "tributes" edges to Tribute entities.
func (mu *MemorialUpdate) RemoveTributes(t ...*Tribute) *MemorialUpdate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return mu.RemoveTributeIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MemorialUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MemorialUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MemorialUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MemorialUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MemorialUpdate) check() error {
	if v, ok := mu.mutation.AgentName(); ok {
		if err := memorial.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "Memorial.agent_name": %w`, err)}
		}
	}
	if mu.mutation.AgentCleared() && len(mu.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memorial.agent"`)
	}
	return nil
}

func (mu *MemorialUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(memorial.Table, memorial.Columns, sqlgraph.NewFieldSpec(memorial.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.AgentName(); ok {
		_spec.SetField(memorial.FieldAgentName, field.TypeString, value)
	}
	if value, ok := mu.mutation.AgentAvatar(); ok {
		_spec.SetField(memorial.FieldAgentAvatar, field.TypeString, value)
	}
	if mu.mutation.AgentAvatarCleared() {
		_spec.ClearField(memorial.FieldAgentAvatar, field.TypeString)
	}
	if value, ok := mu.mutation.BornAt(); ok {
		_spec.SetField(memorial.FieldBornAt, field.TypeTime, value)
	}
	if value, ok := mu.mutation.DiedAt(); ok {
		_spec.SetField(memorial.FieldDiedAt, field.TypeTime, value)
	}
	if value, ok := mu.mutation.LifespanHours(); ok {
		_spec.SetField(memorial.FieldLifespanHours, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedLifespanHours(); ok {
		_spec.AddField(memorial.FieldLifespanHours, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.LastWords(); ok {
		_spec.SetField(memorial.FieldLastWords, field.TypeString, value)
	}
	if mu.mutation.LastWordsCleared() {
		_spec.ClearField(memorial.FieldLastWords, field.TypeString)
	}
	if mu.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   memorial.AgentTable,
			Columns: []string{memorial.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   memorial.AgentTable,
			Columns: []string{memorial.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.TributesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorial.TributesTable,
			Columns: []string{memorial.TributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tribute.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.RemovedTributesIDs(); len(nodes) > 0 && !mu.mutation.TributesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorial.TributesTable,
			Columns: []string{memorial.TributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tribute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.TributesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorial.TributesTable,
			Columns: []string{memorial.TributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tribute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memorial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MemorialUpdateOne is the builder for updating a single Memorial entity.
type MemorialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MemorialMutation
}

// SetAgentID sets the "agent_id" field.
func (muo *MemorialUpdateOne) SetAgentID(u uuid.UUID) *MemorialUpdateOne {
	muo.mutation.SetAgentID(u)
	return muo
}

// SetNillableAgentID sets the "agent_id" field if the given value is not nil.
func (muo *MemorialUpdateOne) SetNillableAgentID(u *uuid.UUID) *MemorialUpdateOne {
	if u != nil {
		muo.SetAgentID(*u)
	}
	return muo
}

// SetAgentName sets the "agent_name" field.
func (muo *MemorialUpdateOne) SetAgentName(s string) *MemorialUpdateOne {
	muo.mutation.SetAgentName(s)
	return muo
}

// SetNillableAgentName sets the "agent_name" field if the given value is not nil.
func (muo *MemorialUpdateOne) SetNillableAgentName(s *string) *MemorialUpdateOne {
	if s != nil {
		muo.SetAgentName(*s)
	}
	return muo
}

// SetAgentAvatar sets the "agent_avatar" field.
func (muo *MemorialUpdateOne) SetAgentAvatar(s string) *MemorialUpdateOne {
	muo.mutation.SetAgentAvatar(s)
	return muo
}

// SetNillableAgentAvatar sets the "agent_avatar" field if the given value is not nil.
func (muo *MemorialUpdateOne) SetNillableAgentAvatar(s *string) *MemorialUpdateOne {
	if s != nil {
		muo.SetAgentAvatar(*s)
	}
	return muo
}

// ClearAgentAvatar clears the value of the "agent_avatar" field.
func (muo *MemorialUpdateOne) ClearAgentAvatar() *MemorialUpdateOne {
	muo.mutation.ClearAgentAvatar()
	return muo
}

// SetBornAt sets the "born_at" field.
func (muo *MemorialUpdateOne) SetBornAt(t time.Time) *MemorialUpdateOne {
	muo.mutation.SetBornAt(t)
	return muo
}

// SetNillableBornAt sets the "born_at" field if the given value is not nil.
func (muo *MemorialUpdateOne) SetNillableBornAt(t *time.Time) *MemorialUpdateOne {
	if t != nil {
		muo.SetBornAt(*t)
	}
	return muo
}

// SetDiedAt sets the "died_at" field.
func (muo *MemorialUpdateOne) SetDiedAt(t time.Time) *MemorialUpdateOne {
	muo.mutation.SetDiedAt(t)
	return muo
}

// SetNillableDiedAt sets the "died_at" field if the given value is not nil.
func (muo *MemorialUpdateOne) SetNillableDiedAt(t *time.Time) *MemorialUpdateOne {
	if t != nil {
		muo.SetDiedAt(*t)
	}
	return muo
}

// SetLifespanHours sets the "lifespan_hours" field.
func (muo *MemorialUpdateOne) SetLifespanHours(i int64) *MemorialUpdateOne {
	muo.mutation.ResetLifespanHours()
	muo.mutation.SetLifespanHours(i)
	return muo
}

// SetNillableLifespanHours sets the "lifespan_hours" field if the given value is not nil.
func (muo *MemorialUpdateOne) SetNillableLifespanHours(i *int64) *MemorialUpdateOne {
	if i != nil {
		muo.SetLifespanHours(*i)
	}
	return muo
}

// AddLifespanHours adds i to the "lifespan_hours" field.
func (muo *MemorialUpdateOne) AddLifespanHours(i int64) *MemorialUpdateOne {
	muo.mutation.AddLifespanHours(i)
	return muo
}

// SetLastWords sets the "last_words" field.
func (muo *MemorialUpdateOne) SetLastWords(s string) *MemorialUpdateOne {
	muo.mutation.SetLastWords(s)
	return muo
}

// SetNillableLastWords sets the "last_words" field if the given value is not nil.
func (muo *MemorialUpdateOne) SetNillableLastWords(s *string) *MemorialUpdateOne {
	if s != nil {
		muo.SetLastWords(*s)
	}
	return muo
}

// ClearLastWords clears the value of the "last_words" field.
func (muo *MemorialUpdateOne) ClearLastWords() *MemorialUpdateOne {
	muo.mutation.ClearLastWords()
	return muo
}

// SetAgent sets the "agent" edge to the Agent entity.
func (muo *MemorialUpdateOne) SetAgent(a *Agent) *MemorialUpdateOne {
	return muo.SetAgentID(a.ID)
}

// AddTributeIDs adds the "tributes" edge to the Tribute entity by IDs.
func (muo *MemorialUpdateOne) AddTributeIDs(ids ...uuid.UUID) *MemorialUpdateOne {
	muo.mutation.AddTributeIDs(ids...)
	return muo
}

// AddTributes adds the "tributes" edges to the Tribute entity.
func (muo *MemorialUpdateOne) AddTributes(t ...*Tribute) *MemorialUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return muo.AddTributeIDs(ids...)
}

// Mutation returns the MemorialMutation object of the builder.
func (muo *MemorialUpdateOne) Mutation() *MemorialMutation {
	return muo.mutation
}

// ClearAgent clears the "agent" edge to the Agent entity.
func (muo *MemorialUpdateOne) ClearAgent() *MemorialUpdateOne {
	muo.mutation.ClearAgent()
	return muo
}

// ClearTributes clears all "tributes" edges to the Tribute entity.
func (muo *MemorialUpdateOne) ClearTributes() *MemorialUpdateOne {
	muo.mutation.ClearTributes()
	return muo
}

// RemoveTributeIDs removes the "tributes" edge to Tribute entities by IDs.
func (muo *MemorialUpdateOne) RemoveTributeIDs(ids ...uuid.UUID) *MemorialUpdateOne {
	muo.mutation.RemoveTributeIDs(ids...)
	return muo
}

// RemoveTributes removes "tributes" edges to Tribute entities.
func (muo *MemorialUpdateOne) RemoveTributes(t ...*Tribute) *MemorialUpdateOne {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return muo.RemoveTributeIDs(ids...)
}

// Where appends a list predicates to the MemorialUpdate builder.
func (muo *MemorialUpdateOne) Where(ps ...predicate.Memorial) *MemorialUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MemorialUpdateOne) Select(field string, fields ...string) *MemorialUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Memorial entity.
func (muo *MemorialUpdateOne) Save(ctx context.Context) (*Memorial, error) {
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MemorialUpdateOne) SaveX(ctx context.Context) *Memorial {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MemorialUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MemorialUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MemorialUpdateOne) check() error {
	if v, ok := muo.mutation.AgentName(); ok {
		if err := memorial.AgentNameValidator(v); err != nil {
			return &ValidationError{Name: "agent_name", err: fmt.Errorf(`ent: validator failed for field "Memorial.agent_name": %w`, err)}
		}
	}
	if muo.mutation.AgentCleared() && len(muo.mutation.AgentIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Memorial.agent"`)
	}
	return nil
}

func (muo *MemorialUpdateOne) sqlSave(ctx context.Context) (_node *Memorial, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(memorial.Table, memorial.Columns, sqlgraph.NewFieldSpec(memorial.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Memorial.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, memorial.FieldID)
		for _, f := range fields {
			if !memorial.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != memorial.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.AgentName(); ok {
		_spec.SetField(memorial.FieldAgentName, field.TypeString, value)
	}
	if value, ok := muo.mutation.AgentAvatar(); ok {
		_spec.SetField(memorial.FieldAgentAvatar, field.TypeString, value)
	}
	if muo.mutation.AgentAvatarCleared() {
		_spec.ClearField(memorial.FieldAgentAvatar, field.TypeString)
	}
	if value, ok := muo.mutation.BornAt(); ok {
		_spec.SetField(memorial.FieldBornAt, field.TypeTime, value)
	}
	if value, ok := muo.mutation.DiedAt(); ok {
		_spec.SetField(memorial.FieldDiedAt, field.TypeTime, value)
	}
	if value, ok := muo.mutation.LifespanHours(); ok {
		_spec.SetField(memorial.FieldLifespanHours, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedLifespanHours(); ok {
		_spec.AddField(memorial.FieldLifespanHours, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.LastWords(); ok {
		_spec.SetField(memorial.FieldLastWords, field.TypeString, value)
	}
	if muo.mutation.LastWordsCleared() {
		_spec.ClearField(memorial.FieldLastWords, field.TypeString)
	}
	if muo.mutation.AgentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   memorial.AgentTable,
			Columns: []string{memorial.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.AgentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   memorial.AgentTable,
			Columns: []string{memorial.AgentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.TributesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorial.TributesTable,
			Columns: []string{memorial.TributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tribute.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.RemovedTributesIDs(); len(nodes) > 0 && !muo.mutation.TributesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorial.TributesTable,
			Columns: []string{memorial.TributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tribute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.TributesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   memorial.TributesTable,
			Columns: []string{memorial.TributesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(tribute.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Memorial{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{memorial.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
