// Code generated by ent, DO NOT EDIT.

package agentrelationship

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the agentrelationship type in the database.
	Label = "agent_relationship"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAgentID holds the string denoting the agent_id field in the database.
	FieldAgentID = "agent_id"
	// FieldTargetAgentID holds the string denoting the target_agent_id field in the database.
	FieldTargetAgentID = "target_agent_id"
	// FieldAffinity holds the string denoting the affinity field in the database.
	FieldAffinity = "affinity"
	// FieldLabel holds the string denoting the label field in the database.
	FieldLabel = "label"
	// FieldInteractionCount holds the string denoting the interaction_count field in the database.
	FieldInteractionCount = "interaction_count"
	// FieldMessageCount holds the string denoting the message_count field in the database.
	FieldMessageCount = "message_count"
	// Table holds the table name of the agentrelationship in the database.
	Table = "agent_relationships"
)

// Columns holds all SQL columns for agentrelationship fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAgentID,
	FieldTargetAgentID,
	FieldAffinity,
	FieldLabel,
	FieldInteractionCount,
	FieldMessageCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAffinity holds the default value on creation for the "affinity" field.
	DefaultAffinity int64
	// DefaultLabel holds the default value on creation for the "label" field.
	DefaultLabel string
	// DefaultInteractionCount holds the default value on creation for the "interaction_count" field.
	DefaultInteractionCount int64
	// DefaultMessageCount holds the default value on creation for the "message_count" field.
	DefaultMessageCount int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the AgentRelationship queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAgentID orders the results by the agent_id field.
func ByAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAgentID, opts...).ToFunc()
}

// ByTargetAgentID orders the results by the target_agent_id field.
func ByTargetAgentID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTargetAgentID, opts...).ToFunc()
}

// ByAffinity orders the results by the affinity field.
func ByAffinity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAffinity, opts...).ToFunc()
}

// ByLabel orders the results by the label field.
func ByLabel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLabel, opts...).ToFunc()
}

// ByInteractionCount orders the results by the interaction_count field.
func ByInteractionCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInteractionCount, opts...).ToFunc()
}

// ByMessageCount orders the results by the message_count field.
func ByMessageCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessageCount, opts...).ToFunc()
}
