#!/usr/bin/env bash
set -euo pipefail

log() {
  printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*"
}

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || {
    log "missing command: $1"
    exit 1
  }
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SYSTEM_FILE="${ROOT_DIR}/system"
ALIVE_AGENT_DIR="${ROOT_DIR}/alive-agent"
COMPOSE_FILE="${ALIVE_AGENT_DIR}/docker-compose.yml"
ALIVE_AGENT_ENV_FILE="${ALIVE_AGENT_DIR}/.env"

require_cmd docker
require_cmd curl
require_cmd python3

if [[ ! -f "${SYSTEM_FILE}" ]]; then
  log "missing ${SYSTEM_FILE} (expected BASE_URL and API_KEY)"
  exit 1
fi

set +u
# shellcheck disable=SC1090
source "${SYSTEM_FILE}"
set -u

if [[ -z "${BASE_URL:-}" || -z "${API_KEY:-}" ]]; then
  log "${SYSTEM_FILE} must define BASE_URL and API_KEY"
  exit 1
fi

mkdir -p "${ALIVE_AGENT_DIR}/config" "${ALIVE_AGENT_DIR}/workspace"

# Preserve an existing gateway token if already present.
ALIVE_AGENT_GATEWAY_TOKEN="${ALIVE_AGENT_GATEWAY_TOKEN:-}"
if [[ -f "${ALIVE_AGENT_ENV_FILE}" ]]; then
  set +u
  # shellcheck disable=SC1090
  source "${ALIVE_AGENT_ENV_FILE}" || true
  set -u
fi

port_free() {
  local port="$1"
  python3 - "$port" <<'PY'
import socket, sys
port = int(sys.argv[1])
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
try:
    s.bind(("127.0.0.1", port))
except OSError:
    sys.exit(1)
finally:
    s.close()
sys.exit(0)
PY
}

# Pick a free host port for the backend if the default (8888) is occupied.
ALIVE_API_PORT="${ALIVE_API_PORT:-}"
if [[ -z "${ALIVE_API_PORT}" ]]; then
  for p in 8888 8889 8890 8891 8892 8893 8894 8895 8896 8897 8898 8899; do
    if port_free "$p"; then
      ALIVE_API_PORT="$p"
      break
    fi
  done
fi
if [[ -z "${ALIVE_API_PORT}" ]]; then
  log "could not find a free host port for ALIVE backend (tried 8888-8899)"
  exit 1
fi

if [[ -z "${ALIVE_AGENT_GATEWAY_TOKEN:-}" ]]; then
  if command -v openssl >/dev/null 2>&1; then
    ALIVE_AGENT_GATEWAY_TOKEN="$(openssl rand -hex 32)"
  else
    ALIVE_AGENT_GATEWAY_TOKEN="$(python3 - <<'PY'
import secrets
print(secrets.token_hex(32))
PY
)"
  fi
fi

ALIVE_AGENT_IMAGE="${ALIVE_AGENT_IMAGE:-alive-agent:local}"

log "writing ${ALIVE_AGENT_ENV_FILE} (secrets not printed)"
umask 077
cat >"${ALIVE_AGENT_ENV_FILE}" <<EOF
# Auto-generated by scripts/docker_up_alive_agent.sh
#
# NOTE: this file contains secrets. It is gitignored by alive-agent/.gitignore.
ALIVE_API_PORT=${ALIVE_API_PORT}
ALIVE_AGENT_GATEWAY_TOKEN=${ALIVE_AGENT_GATEWAY_TOKEN}

# Map ALIVE's system settings (system: BASE_URL/API_KEY) to OpenAI-compatible env vars.
OPENAI_BASE_URL=${BASE_URL}
OPENAI_API_KEY=${API_KEY}
EOF

log "building alive-agent image: ${ALIVE_AGENT_IMAGE}"
docker build -t "${ALIVE_AGENT_IMAGE}" -f "${ALIVE_AGENT_DIR}/Dockerfile" "${ALIVE_AGENT_DIR}"

log "starting docker compose: ${COMPOSE_FILE}"
docker compose -f "${COMPOSE_FILE}" up -d --build postgres alive-agent-gateway alive-backend

# Wait for services to accept TCP connections.
BACKEND_URL="http://127.0.0.1:${ALIVE_API_PORT}"
ALIVE_AGENT_URL="http://127.0.0.1:18789"

log "waiting for backend: ${BACKEND_URL}"
for _ in $(seq 1 60); do
  if curl -sS --max-time 2 "${BACKEND_URL}" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

log "waiting for alive agent gateway: ${ALIVE_AGENT_URL}"
for _ in $(seq 1 60); do
  if curl -sS --max-time 2 "${ALIVE_AGENT_URL}" >/dev/null 2>&1; then
    break
  fi
  sleep 1
done

log "up"
log "backend:  ${BACKEND_URL}"
log "alive agent: ${ALIVE_AGENT_URL}"
